### ISSUE TITLE
Should Layotto support SQL queries and how? Layotto是否应该支持SQL查询，如何支持？

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#101]
## Should Layotto support SQL queries and how?
The current state API is essentially a key/value model API and does not support SQL query. 

So should L8 support sql query? We open this issue to see your opinions

### User scenario:
1. DB sharding: If users have done mysql sharding, the application needs routing when querying mysql.It is necessary for apps to import a data middleware SDK(such as shardingsphere-JDBC) or query through a db proxy (such as ShardingSphere-Proxy), or through a db mesh sidecar (such as ShardingSphere-Sidecar)
2. Portability: If users want to deploy their apps across different clouds, or do some migration such as migrating from mysql cluster to a distributed relational database (TiDB, Oceanbase, etc.), as long as the new db supports the mysql protocol, users don't have to modify their code.Portability like this can be achieved by using db proxy or db mesh.

### Question:
1. Should L8 function as a db mesh sidecar? In other words, do you have any needs in sql query through L8?
2. If we want L8 to support sql query, what kind of API should be provided?
	a. Binding API like Dapr
	b. Support Mysql protocal

Welcome to express your opinion!

chinese:
## Layotto是否应该支持SQL查询，如何支持？
目前的state API本质上是key/value模型的存储、不支持灵活的传SQL。那么L8要不要支持sql查询呢？发个issue看看大家的意见

### 用户场景：
1. 分库分表：假如用户做了mysql分库分表，应用在查询mysql的时候需要路由，就要集成数据中间件的sdk（例如shardingsphere-JDBC）或者经过独立进程的db proxy（例如ShardingSphere-Proxy），或者经过作为sidecar的db mesh（例如ShardingSphere-Sidecar）
2. 可移植：假如用户要跨云部署，要做一些移植，比如从mysql分库分表换成用分布式关系库（TiDB,Oceanbase等），只要新的库也支持mysql协议，使用db proxy或db mesh的应用就可以无需修改代码、具备随时移植到新环境的能力

### 问题:
1. runtime要不要做db mesh的功能呢？或者说，您有通过runtime支持sql查询的需求么？
2. 如果要支持sql查询，是提供什么样的API呢？
	a. 像Dapr一样的binding API
	b. 直接支持SQL查询

欢迎大家发表自己的看法~~

**Comment by seeflood** [comment]
pros:
1. A single sidecar serve as service mesh+db mesh+runtime.Easy to operate

cons:
1. Complex to implement

**Comment by nobodyiam** [comment]
I think it's meaninful to support sql statements, however sql is complex, e.g. transaction support. Also there are minor syntax differences between different databases, which means it might be hard to change from one database to another.

**Comment by wenxuwan** [comment]
attach some discussion:

https://github.com/dapr/dapr/issues/3339
https://github.com/dapr/dapr/issues/1339

**Comment by seeflood** [comment]
https://github.com/dapr/dapr/issues/3354
