### ISSUE TITLE
官方文档中关于 configuration api 的功能介绍文档缺失

### ISSUE THREAD

**Issue by wushiling50** [mosn/layotto#1045]
如图：  
![configuration](https://github.com/mosn/layotto/assets/120616893/c008fb0b-b10a-4b09-9a61-f9f35fe0a02d)   
想请问一下configuration api的这部分文档现在有人在写吗  
(因为看了一下 docs 里的 git 记录也是三年前的了，查了 issue 好像也没人提，不太清楚什么情况)

**Comment by wushiling50** [comment]
没人在写的话可以让我来试一下吗

**Comment by seeflood** [comment]
> 没人在写的话可以让我来试一下吗

目前没人在写，欢迎贡献!

**Comment by wushiling50** [comment]
> > 没人在写的话可以让我来试一下吗
> 
> 目前没人在写，欢迎贡献! @wushiling50
好的，我会尽快完成

**Comment by wushiling50** [comment]
> > 没人在写的话可以让我来试一下吗
> 
> 目前没人在写，欢迎贡献! @wushiling50

好的，我会尽快完成
