### ISSUE TITLE
Add unit tests for WASM related code; 为wasm模块补充单测

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#105]
**What would you like to be added**:
Add unit tests for WASM related code: 
understand the implementation of the wasm module and add unit tests for it. The unit test coverage of the module should reach 60%. 
If you encounter any problems in the process, you can ask @zhenjunMa  for help. 
The code path is pkg/wasm/

By doing this improvement,you will learn that how Layotto supports multilingual programming based on WASM

chinese:
看明白wasm模块的实现原理并补充单测，使模块的单测覆盖率达到60%
过程中遇到问题可以问 @zhenjunMa 
代码路径为 pkg/wasm/

做完这些优化后，你将学习到Layotto如何通过wasm支持多语言编程

**Why is this needed**:
Currently the test coverage of wasm is low:
![image](https://user-images.githubusercontent.com/26001097/124229034-95591d00-db3f-11eb-8860-d370841bdf4d.png)

**Comment by seeflood** [comment]
For your reference:
[quickstart demo for using WASM](https://github.com/mosn/layotto/blob/main/docs/en/start/wasm/start.md)
or
[quickstart demo for using WASM(中文)](https://github.com/mosn/layotto/blob/main/docs/zh/start/wasm/start.md)

**Comment by oneyue610** [comment]
OK

**Comment by seeflood** [comment]
> OK

Ok,already assigned.

**Comment by seeflood** [comment]
@oneyue610 Hi, are you still working on it?

**Comment by seeflood** [comment]
@oneyue610 Hi,are you still working on it?
Since you didn't response,I will reassign this task to someone else :<
If you still want to do this,just tell me and i will assign to u again

**Comment by Xunzhuo** [comment]
@assign

**Comment by seeflood** [comment]
@Xunzhuo Hi, shall we reassign it to others?
Since we are going to do a new round of activities, I think we can treat it as an activity task

**Comment by Xunzhuo** [comment]
Yes of course, @seeflood, maybe I should focus more on integration with istio

**Comment by ChloroplastYu** [comment]
@assign

**Comment by Xunzhuo** [comment]
Closed by https://github.com/mosn/layotto/pull/1013
