### ISSUE TITLE
Add unit tests for RPC related code

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#106]
**What would you like to be added**:
Understand the implementation of the rpc module and add unit tests for it, so that the test coverage of the module reaches 80%
You can ask @MoonShining for help if you encounter any problems in the process.
The code path is in components/rpc
In addition, there are rpc related codes in pkg/grpc/api.go and pkg/runtime/runtime.go files

Reference materials:[rpc design document](https://github.com/mosn/layotto/blob/main/docs/en/design/rpc/rpc-design-doc.md)

After completing this improvement, you will learn the principle of Layotto supporting rpc, how Layotto and mosn are integrated to reuse service mesh capabilities

**chinese:**
看明白rpc模块的实现原理并为rpc相关模块补充单测，使模块的单测覆盖率达到80%
过程中遇到问题可以问 @MoonShining 。
代码路径在 components/rpc  
另外pkg/grpc/api.go  和pkg/runtime/runtime.go 文件里也有rpc相关的代码

参考资料：[rpc设计文档](https://github.com/mosn/layotto/blob/main/docs/zh/design/rpc/rpc%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3.md)

完成这项优化后，你将学习到Layotto支持rpc的原理、Layotto是如何和mosn整合到一起复用service mesh能力的

**Why is this needed**:
Currently the test coverage of rpc component is not high:
![image](https://user-images.githubusercontent.com/26001097/124231182-86c03500-db42-11eb-9205-5c04b45cd3a3.png)

**Comment by seeflood** [comment]
@tianjipeng Hi,you can reply here
It seems a github rule that I can't assign it to you until you reply here

**Comment by tianjipeng** [comment]
Ok，please assign to me

**Comment by seeflood** [comment]
Ok, already assigned.
