### ISSUE TITLE
add comment to exported function/method/interface/variable

### ISSUE THREAD

**Issue by tianjipeng** [mosn/layotto#112]
**What would you like to be added**:
Add comment to exported function/method/interface/variable.

**Why is this needed**:
There are many exported function/method/interface/variable that have no comment, it would be helpful if have comment.

**Comment by seeflood** [comment]
Thanks for your feedback!
Lack of comments makes developers' experience very bad  :< 
We will assign different tasks and ask the developers to add comments to their code.
By the way,which part of code currently annoys you the most? We can add comments to that part first

**Comment by seeflood** [comment]
- [ ] add comments to RPC related code @MoonShining 
- [ ] add comments to pubsub related code @seeflood 
- [ ] add comments to lock related code @seeflood 
- [ ] add comments to state API related code @seeflood 
- [ ] add comments to actuator related code @seeflood 
- [ ] add comments to tcpdump related code @seeflood 
- [ ] add comments to WASM related code @zhenjunMa 
- [ ] add comments to flow-control related code @zhenjunMa  
- [ ] add comments to configuration API related code @wenxuwan

**Comment by wudi-666272** [comment]
hi，Can you leave this task “add comments to RPC related code” to me to complete

**Comment by seeflood** [comment]
> hi，Can you leave this task “add comments to RPC related code” to me to complete

Cool!
Already assigned.Welcome to the Layotto Community and feel free to ask for help during when u encounter some problems.

**Comment by LXPWing** [comment]
Recently learning WASM , I want to try the task 'add comments to WASM related code'

**Comment by seeflood** [comment]
> Recently learning WASM , I want to try the task 'add comments to WASM related code'

Cool ! assigned to u

**Comment by Holdonbei** [comment]
您的邮件我已收到。
