### ISSUE TITLE
Use Consul to implement Distributed Lock API

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#129]
**What would you like to be added**:
Use Consul to implement Distributed Lock API

**Why is this needed**:
see #104

**Comment by seeflood** [comment]
@ZLBer hi,please reply here and then i can assign it to you

**Comment by ZLBer** [comment]
@seeflood 
fine, i  will try .

**Comment by ZLBer** [comment]
@seeflood 
关于consul实现的探讨：
1. consul api封装了lock 接口, 可以实现阻塞锁，对session不断renew续约达到持续持有锁的目的，功能比较丰富，可以设置重试次数，获取锁等待时间等。但sidecar情形下，client断开，lock在sidecar端还会不断进性renew，导致锁不能释放。
2. 抛弃lock实现，利用session+acquire+release实现(consul lock内部也是如此), 每次trylock 都新建session，令session ttl=expire time,  不对session进性renew，只让其存活ttl时间，保证锁的正确性。

**Comment by ZLBer** [comment]
@seeflood 
遇到了点问题：
1.acquire和release操作要求必须是同一个session，那就没法每次lock都新建一个session了。
2. 想着直接用put 操作，但consul的put会直接更新kv,  没有类似setnx的操作。

**Comment by seeflood** [comment]
> @seeflood
> 关于consul实现的探讨：
> 
> 1. consul api封装了lock 接口, 可以实现阻塞锁，对session不断renew续约达到持续持有锁的目的，功能比较丰富，可以设置重试次数，获取锁等待时间等。但sidecar情形下，client断开，lock在sidecar端还会不断进性renew，导致锁不能释放。

"client断开，lock在sidecar端还会不断进性renew，导致锁不能释放。"
目前的API是tryLock传expire，其实sidecar起个新协程、expire到期后关闭session即可，不至于出现死锁。
但是这个方案和zk面临一样的问题：如果用户申请的是一把“粗粒度锁”，expire传的比较大，相比之下consul的session ttl很短，那可能sidecar心跳很快就断掉、丢锁，但是app还以为自己持有锁

方案2对粗粒度锁稍微好一些（前提是调研清楚，consul对session ttl传入的值有没有限制，会不会限制不让传太大）

**Comment by seeflood** [comment]
> @seeflood
> 遇到了点问题：
> 1.acquire和release操作要求必须是同一个session，那就没法每次lock都新建一个session了。

这个在内存里维护一个session池即可（说白了就是个map)抢锁成功后往map里放session.key是resource_id和owner_id信息,value是session。需要注意并发控制，需要注意session过期后能自动删除map，免得内存泄漏

> 2. 想着直接用put 操作，但consul的put会直接更新kv, 没有类似setnx的操作。

这个要查一下了 我搜下 你也可以先查下文档

**Comment by seeflood** [comment]
@ZLBer 我查了下consul有check-and-set能力，看下这个能用不
https://alesnosek.com/blog/2017/07/25/check-and-set-operation-and-transactions-in-consul/

**Comment by ZLBer** [comment]
@seeflood 
consul的session ttl到期不会自动删除key，所以CAS这个貌似也会存在问题，client崩溃没法删除节点。session ttl 到期只会使lock失效，那还得借助consul的lock机制(acquire和release)。
