### ISSUE TITLE
Add unit tests for runtime/runtime.go and grpc/api.go

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#138]
**What would you like to be added**:
Add unit tests for runtime/runtime.go and grpc/api.go. 
These two files are the core engine code of Layotto, responsible for component lifecycle management and grpc request processing respectively.

chinese:
为runtime/runtime.go和grpc/api.go添加单元测试。这两个文件是layotto的核心引擎代码，各自负责组件生命周期管理（启动、注册、初始化）和grpc请求处理，完成此任务可以很好的了解Layotto架构

**Why is this needed**:
Currently our test coverage is not high :(

**Comment by seeflood** [comment]
Assigned to @tianjipeng 
Thanks for your passion!

**Comment by tianjipeng** [comment]
OK

**Comment by seeflood** [comment]
@tianjipeng  Hi, are you still working on it?

**Comment by tianjipeng** [comment]
I wiil commit a pr this weekend

**Comment by seeflood** [comment]
> I wiil commit a pr this weekend

Fine.If you find some code or module difficult to understand,just tell me and I will add comments and document for that module first.
