### ISSUE TITLE
Add more features for java sdk

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#148]
**What would you like to be added**:
Add more sdk api into java sdk
(currently there are only protobuf files,but some users ask us to add more feature in sdk)

**Why is this needed**:

**Comment by seeflood** [comment]
@ZLBer Hi,you can reply here so that i can assign it to u
@MoonShining is developing a rpc method for java client, I think you can add any other features for java sdk

**Comment by seeflood** [comment]
刚问了下 @MoonShining ，他没在写client，只是发现Java client里面的proto文件没生成全，所以他开发内部需求的时候重新生成了一下~
@ZLBer 如果决定开发java client的话，可以重新编译生成下proto，毕竟自上次更新后有新的API~

**Comment by ZLBer** [comment]
ok 的
