### ISSUE TITLE
Sequencer API impl: mongo & Leaf

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#149]
**What would you like to be added**:
Add Sequencer API component: 
- [ ] mongo . assigned to @LXPWing 
- [ ] Leaf
See #108 

You can refer to the [sequencer API design document](https://mosn.io/layotto/#/zh/design/sequencer/design)

**Why is this needed**:

**Comment by seeflood** [comment]
This task will be assigned to @stulzq

**Comment by stulzq** [comment]
ok 
![image](https://user-images.githubusercontent.com/13200155/126760848-cae7fe04-2848-4cda-b957-0de1070abb5e.png)

**Comment by seeflood** [comment]
ok
![](https://user-images.githubusercontent.com/13200155/126760848-cae7fe04-2848-4cda-b957-0de1070abb5e.png)

**Comment by seeflood** [comment]
Hi @stulzq ,are u still working on it ? Or should I reassign it to others if you don't want to do it?

**Comment by stulzq** [comment]
> Hi @stulzq ,are u still working on it ? Or should I reassign it to others if you don't want to do it?

reassign it to others
