### ISSUE TITLE
Implement the segment caching feature of Sequencer API

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#158]
**What would you like to be added**:
Implement the segment caching feature of Sequencer API
You can refer to Leaf to do double buffer optimization
The function to be implemented is at https://github.com/mosn/layotto/blob/main/pkg/runtime/sequencer/cache.go

The design doc(in chinese) is at https://mosn.io/layotto/#/zh/design/sequencer/design

**Why is this needed**:

**Comment by seeflood** [comment]
This task will be assigned to @ZLBer

**Comment by ZLBer** [comment]
建议给sequencer增加是否支持segment的方法，现在GetSegment方法功能不够单一, 在写catch的时候发现有时候只想查看sequencer是否支持segment,并不想直接申请一段。

**Comment by seeflood** [comment]
@ZLBer 本来考虑过加个isSupportCache()  后来改成GetSegment了
GetSegment也能解决你说的问题呀，只想取号、不想判断的话，size传0，GetSegment(0)

**Comment by ZLBer** [comment]
这样啊 怪怪的

**Comment by seeflood** [comment]
> 这样啊 怪怪的

是有点
其实我原来第一版就写的一个单独的判断函数（叫supportSegement还是啥来着忘了） 
后来和其他人讨论，别人觉得没必要单独加一个函数，我看了下Dapr state组件的BulkGet 设计风格也是往返回结果里加个support，就改成这样了。当时觉得这种其实是个人喜好问题，没啥对与错，既然Dapr之前是这风格那就保持一致吧，就改了
或者你也可以把你的想法写下，我们下周讨论下

**Comment by seeflood** [comment]
现在实现的话可以先写GetSegment(0) 后面真要改成supportSegment也简单

**Comment by ZLBer** [comment]
fine
