### ISSUE TITLE
Community Governance Proposal

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#167]
# 前言
Layotto刚刚发布了第一个版本，社区各位同学做出了很多贡献。为了回报大家的努力，最好的方式就是把社区越做越大（毕竟大家都希望自己写的代码对世界产生更大的影响力，而不仅仅是一两个公司的自high项目)

那么怎么才能把社区做大呢？其中一件能做的事情就是制定好的社区规则。个人理解，好的社区规则要足够透明、开放，允许每个感兴趣的人加入、提建议、参与决策；好的社区规则要让大家能看到投入后的回报，回报有很多种，例如学到感兴趣的知识，实践感兴趣的技术，获得更酷的荣誉 title，获得社区影响力，自己写的代码跑在很多公司的机器上从而获得成就感，成为社区的决策者，获得求职时的亮眼项目履历，参与社区活动获得奖品IDE License……

Layotto 是 MOSN 社区的项目，而 SOFAStack 社区和 MOSN 社区之前用的都是同一套组织架构（如果我理解的不对请指正哈），针对过去的一些问题，本草案试着对规则提出一些变化，希望调动大家积极性，让项目 owner 觉得是在为个人爱好/个人荣誉而参与社区，让每个感兴趣的技术同学都能参与到社区核心决策中，学到自己感兴趣的知识、做自己感兴趣的项目，成为项目的决策者之一，and finally impact the world!

# 目前 SOFAStack 组织架构
[https://www.sofastack.tech/community/](https://www.sofastack.tech/community/)

![image.png](https://cdn.nlark.com/yuque/0/2019/png/226702/1577327906629-43c94574-2f7e-4c49-b27a-de9a836a54f2.png)

存在的问题

1. 虽有 User Group 但活跃度不足
1. Contributor 晋升路线过长、模糊
1. 项目 owner 投入开源的时间有限（加班多，也没办法……）、动力不足（最直接的表现是，离职或转岗后缺少继续贡献社区的动力）

# v2.0 草案
![image](https://user-images.githubusercontent.com/26001097/128465670-a3ef1ef2-b4e9-4359-8bc8-df841be4e1e0.png)

新增角色用红色标识。
解释：
## 1. Title 社区化：所有社区 title、权限和参与者所属公司无关
此条为了调动大家积极性，让项目 owner 觉得是为了个人爱好/个人荣誉而参与社区，不管去哪家公司都还是SOFAStack PMC member/Co-founder; 让每个感兴趣的技术同学都能参与到社区核心决策中，促进社区活跃
### Co-founder（项目创始人）终身荣誉制
作为终身荣誉，但没有实权。比如某位开发者创建了项目A，多年后即使他不再参与社区维护、辗转跳槽多家公司，经历了风风雨雨、起起落落，决定转行不做程序员了、开了家火锅店，他也依然是项目A的 Co-founder

### PMC(Project Management Committee) member
PMC member 作为项目核心管理团队，有项目的决策权，**和所属公司无关，仅看社区活跃度**。比如，某 Co-founder 如果多年不参与社区维护，就不再是PMC member了。比如某位编程爱好者主业是火锅店老板、不是程序员，只要他对项目的贡献足够，他也可以是PMC member。至于如何成为 PMC member，见下面的晋升规则

### 欢迎各位项目 owner 给自己和其他人发 title
只有让项目 owner 和社区贡献者有动力持续维护，社区才会越做越大，因此欢迎大家给自己和其他人发 title，不需要谦虚。

​

### Active Contributor 和 Reviewer
Active Contributor 是一年贡献超过xxx 个 PR 的 Contributor。（每个项目自己定）
Reviewer 从 Active Contributor 中诞生，具有 Review PR 的义务，并且对某个项目/模块的 PR 的点赞（LGTM）有效。
​

### Core Team 核心开发者团队

SOFAStack & MOSN 社区的每个项目可以拉个独立的核心团队群(钉钉/微信都行)。
Core Team 负责某个项目的开发和维护工作，对代码的质量负责。
我们将邀请 Active Contributor 加入Core Team，开发者们将在 Core Team 中获得其他开发者的持续帮助、交流，一边锻炼技术能力，一边优化和完善项目。社区开发者们可通过 Core Team 逐渐从初始的 Active Contributor 成长为受到社区认可的 Reviewer、Committer 和 PMC member。
一般而言每个专项兴趣小组都会周期性的组织会议，讨论最近进展和遇到的问题，所有的会议讨论都公开在社区上，方便感兴趣的同学一起参与和讨论。
​

注：此项设计参考了Tidb社区的 [ Special Interest Group](https://pingcap.com/blog-cn/tidb-community-upgrade/#%E5%8F%98%E5%8C%96-3special-interest-group)

### 完善社区成员晋级的规则、指导机制
社区成员做出怎样的贡献后可以晋级？要有透明、具体的规则，让社区同学从 Contributor 成长到 Committer 或 Maintainer 有路可循，**让大家觉得“投入就一定有回报”**
具体晋升机制由每个项目的 Core Team 讨论决定

### 评审社区化：需求和技术方案公开评审
重要需求的评审、技术方案的评审应该在社区内**以开放的方式做评审，而不是蚂蚁员工开内部评审会**
例如要做技术方案评审时，社区成员可以在自己的用户群或者 Core Team 群里组织线上会议、开直播，允许每一个感兴趣的人观看、参与。如果觉得直播太重，issue 区发 proposal 也行。
​

否则，试想：某项目 owner 离开蚂蚁后，虽然他是 PMC member，但是方案评审都不带他，他还会有动力继续参与社区么？
​

### 晋升社区化
晋升由社区成员在群内组织投票，具体晋升规则由每个项目的核心团队自行协商决定
​

### 其他社区规则
例如冲突解决规则，code review 要几票才能通过等，由每个项目的核心团队自行协商决定
# 参考资料
Apollo 
[https://github.com/ctripcorp/apollo/pull/3670](https://github.com/ctripcorp/apollo/pull/3670)
​[https://github.com/ctripcorp/apollo/issues/3684](https://github.com/ctripcorp/apollo/issues/3684)
[https://github.com/ctripcorp/apollo/discussions/categories/announcements](https://github.com/ctripcorp/apollo/discussions/categories/announcements)
​

Tidb的社区组织架构 [https://pingcap.com/blog-cn/tidb-community-upgrade/](https://pingcap.com/blog-cn/tidb-community-upgrade/)

# 怎么落地？
如果大家讨论觉得没问题了，可以先从 Layotto 和 SOFA-registry 开始试运行该制度。
一开始，先由项目 owner 根据社区贡献程度来确定初始团队(给大家发 title)，再由初始团队讨论细化晋升规则、title 提名。
​

# 这是草案、不是结论，欢迎提出不同意见
本文仅作抛砖引玉、试着发出来看看大家意见，欢迎提出您的不同意见~
本人经验不足，上次正儿八经写这种组织规则还是在小学三年级玩网游《传奇》时创建公会，所以如有不妥快来指正
​

**Comment by seeflood** [comment]
English version will be added soon

**Comment by seeflood** [comment]
记录下钉群里的讨论：

这次设计的目的：
1. 激励活跃贡献者，有个比contributor更酷的title
2. 决策社区化，code review可以由活跃贡献者来，不想只有一两个人有review权限
3. 调动SOFAStack社区各个项目owner积极性，让大家觉得是为了个人爱好/个人荣誉而贡献社区
4. 让社区参与者能看到“确定性回报”，就比如tidb“一年提交8个pr就能晋升active contributor”。
逻辑是：国内程序员时间有限，最好能有个明确的规则、让大家看到“我牺牲业余时间做这些事，做完我就能得到确定性的回报”，如果规则比较模糊、晋升commiter的规则外人看不到，有经验的人可能就要在心里算笔账：值不值得牺牲业余时间写这个项目的代码？


反对观点：
1. 社区没tidb那么多，怕拆太细了人不够、尴尬

另一种思路：
不新增角色了，还是从contributor直接到commiter，只不过早期定一个明确的commiter晋升规则，门槛低一些，以后人多了再考虑提高commiter门槛

**Comment by seeflood** [comment]
记录下一位不愿透露姓名的优秀开发者的意见：
1. 同意反对观点，人少没必要；觉得头衔无所谓，skywalking的那种证书更酷
2. 担心自己review不动别人代码
3. 我们的证书不好看
（我去问问现在改证书还来得及么

**Comment by seeflood** [comment]
记录一位优秀贡献者的意见（终于有人支持这个方案了：
![image](https://user-images.githubusercontent.com/26001097/129328907-8c77017f-38f0-48bd-9dc2-dce65b61f5bd.png)

**Comment by seeflood** [comment]
参考上述意见，做了些修改：

## Draft 2
![image](https://user-images.githubusercontent.com/26001097/129526593-d68939e1-7465-4f39-8629-9d39837210e2.png)

1. 去掉了Active Contribuotor；
2. 保留Reviewer，但是该角色可选，各项目可以按自己项目的情况决定是否加入该角色；
Reviewer具有 Review PR 的义务，并且对某个项目/模块的 PR 的点赞（LGTM）有效。Review贡献也算在晋升commiter的考虑之内。
添加这个角色的目的：
- 希望能让MOSN和SOFAStack社区响应速度更快一些（提升活跃度）
- 决策社区化，code review可以由活跃贡献者来，不想只有一两个人有review权限



欢迎各位继续提意见！

**Comment by seeflood** [comment]
记录另一位优秀贡献者的意见：
![image](https://user-images.githubusercontent.com/26001097/129537707-f05d5984-6b65-4f58-b443-6960ddc7ad3d.png)

**Comment by seeflood** [comment]
记录一位高情商的优秀贡献者观点：证书好看！
![image](https://user-images.githubusercontent.com/26001097/129541941-b43c1ea4-c4a8-44c1-ab8f-c4f601d79a48.png)

关于证书：
![image](https://user-images.githubusercontent.com/26001097/129542318-cb1b4fa3-bcc6-4d68-b8f6-9d48d5c265fd.png)

**Comment by Xunzhuo** [comment]
其实在Contributor之上可以加一层Member的title，活跃的Member可以成为Reviewer，具体来说：
如何成为Member，这个在初期不能门槛太高，比如提交过PR被merge了，或者有价值的issue的，就可以邀请GitHub id 到社区成为member，成为member之后，他的职责是code review以及处理issue，如果发现member处理issue和code review的频率很高，比如连续一个月，每周至少处理过3个issue或1个PR，就可以成为Reviewer；
成为Reviewer之后，职责相比member要更明确，就是处理issue和PR，而且必须保持每周至少处理3个issue或1个PR，如果连续一个月，有两周处理的频率没有达到标准，会回退到Member；
而Commitor我个人人为，晋升规则可以有两条，一个是连续6个月的reviewer处理频率达标了，可以考虑有一次晋升；或者给社区做了重要的feature的PR贡献，并成功merge之后，他可以成为那部分代码的code owner，同时也成为commitor，负责他那块代码的issue和PR处理；
关于角色权限问题：
1. member可以处理issue，比如加label，assign任务，code review的LGTM权限
2. reviewer与member有相同权力可以处理issue，比如加label，assign任务，code review的LGTM权限
3. commitor 具有merge的权力，但是何时merge，需要除了他本人之外，有两个人以上的code review，然后他就能merge
4. PMC 具有决策能力，委任commitor，以及新PMC选举的投票权，当然他具有merge的能力，不过为了防止错误，即使PMC，也需要两位以上的code review，才能merge。

其实这就是Kubernetes社区的思想，具体有些晋升的指标可能不太一样哈，比如成为member需要5个PR被merge，同时需要2个以上的member的sponsor 
也就是他需要在community repo提issue，达到基础标准之后，两个以上member去issue下评论sponsor，他就会被commitor邀请进入kubernetes
当然他们成功的原因有他在cloud native地位的原因，不过其实他优秀的社区规则，以及合理利用GitHub action建立robot去指引contributor以及处理基础的委派issue和一些自动化的操作

包括它表明，一年以内member没做任何贡献，会被踢出去，然后如果要进来，需要重新竞选

当然还有更细节的，比如在处理issue时，多去引导contributor，多鼓励然后加一些emoji，会潜在的提高社区贡献者的热情，包括把一些issue当作 good first issue，引导想贡献的contributor去做贡献

当然要更universal，建议尽量在issue和PR使用英语，沟通平台除了钉钉，多样化一点，比如slack；

**Comment by seeflood** [comment]
@Xunzhuo 感谢建议！！
1. 关于Member:我觉得加入Member角色这个点子很棒，因为让贡献者可以在github profile显示组织logo（如果我没理解错的话），很cooooool
2. 关于Member晋升Reviewer :因为社区目前人不多，我本来想着来了就是朋友、哪位Contributor想当Reviewer的话直接就能当,但是按你的思路其实member也要负责处理issue和code review，那么Member和Reviewer核心区别是啥？看起来好像没啥区别，两个角色都是负责处理issue和code review

**Comment by seeflood** [comment]
@stulzq @zu1k @tianjipeng @ZLBer @zhenjunMa @TreeLin @taoyuanyuan @nobodyiam @JervyShi 
手动艾特一下，各位老师看下上述建议如何~

**Comment by Xunzhuo** [comment]
@seeflood  
1. 是的，这算是 basic recognized；
2. member里面有活跃的，也有不活跃的，有喜欢code review 也有不喜欢的，并不能保证快速的响应，如果有人能保持高活跃度，那就可以给他reviewer的title，如果能保持长时间的code review 这会是成为commitor的一条途径，也就是成为reviewer就有活跃度的要求，有更多的职责了，这样能保证社区快速响应，带给reviewer的是更深入对项目源码的剖析，以及晋升commitor的机会，毕竟对源码更深入也应该是commitor的基本要求，也是commitor具有merge权限的前提。

**Comment by seeflood** [comment]
感谢@Xunzhuo的建议，参考 @Xunzhuo 和其他同学的意见，我试着做了修改：

## Draft 3
![image](https://user-images.githubusercontent.com/26001097/129829768-86e5c687-4337-4607-9017-7582d8e65ddb.png)
### 1. Member
#### 角色说明
新增Member角色，其实就是邀请加入组织。
当然，考虑到过往一些项目是只有Committer才能拉组织，该角色可选、不强制要求，各项目可以按自己项目的情况决定是否加入该角色。
目前的想法是先在Layotto和SOFA-Registry试验加入该角色。
但：Layotto的组织目前用的是MOSN，所以其实加入Layotto组织，就是加入MOSN

#### 添加这个角色的目的?
加入组织后，贡献者的github profile页显示组织logo，这很酷，可以激励大家加入社区、做出贡献。

#### Member的职责
Member职责是code review以及处理issue，如果发现member处理issue和code review的频率很高，就可以成为Reviewer（详见下）；

#### 成为Member的条件（加入组织的条件）
每个项目自己定吧。目前收集到大家的不同意见有：
a. 提交过有价值的PR
b. 提交过2个有价值的PR
c. 变更过100行（代码或文档）
d. 愿意帮忙review代码和issue的Contributor都可以拉进组织，来了就是朋友

我个人的想法是按项目活跃度定门槛，比如SOFA-Registry可以把标准定低些，比如选择d（因为很缺人来快速响应仓库啊！！！）；Layotto可以把标准定稍微高一些？比如a或b
这个具体等每个项目有首届PMC后投票吧

### 2. Reviewer
#### 角色职责
和Committer一样，也是负责code review以及处理issue。长期review贡献多可以晋升Committer
某个issue/Pull request涉及某个模块，项目维护者可以request这个模块的Reviewer进行Review、负责把关。比如有人给Layotto的WASM模块提bug，可以request 模块reviewer @zhenjunMa

该角色可选，各项目可以按自己项目的情况决定是否加入该角色；

#### 成为Reviewer的条件
如果发现member处理issue和code review的频率很高，比如连续一个月，每周至少处理过2个issue或1个PR，就可以成为Reviewer；
比如contributor对某个模块提供了2次重要PR后，可以邀请担任该模块的Reviewer（举个例子，邀请@zu1k 担任WASM模块的Reviewer）
具体条件每个项目的PMC决定

#### Reviewer是否会回退到Member
每个项目自己定。目前收集到的不同意见：
a. 成为Reviewer之后，职责相比member要更明确，就是处理issue和PR，而且必须保持每周至少处理2个issue或1个PR，如果一个月内，有两周处理的频率没有达到标准，会回退到Member；
b. 认为给Reviewer定目标太有KPI味了，工作背KPI就够难了别给社区搞KPI

#### 添加这个角色的目的?
1. 希望能让MOSN和SOFAStack社区响应速度更快一些，响应pr快一些（至于如何提高issue响应速度，我还没想到啥办法，欢迎提建议
2. 决策社区化，code review可以由活跃贡献者来，不想只有一两个人有review权限
3. 很多爱好者可能一段时间有空、一段时间没空（国内程序员现状.....)，没空的时候通过Review PR和issue，可以只花少量时间就能参与项目、做出贡献、知道项目这段时间发生的变化


#### code review时，一票LGTM还是两票LGTM才能合并？
A: 目前想法是参考vue社区，reviewer如果review通过可以回复LGTM，但是没有merge权限，项目维护者（有写权限的人）负责实际合并。
项目维护者如果很信任reviewer，可以简单看下pr，没问题就合并；如果pr改动比较大、不太放心，就要自己也认真看一下pr。
所以，约等于两票合并制

### 3. 其他
- 尽量在issue和PR使用英语
  对于Layotto，因为我们的目标是和Dapr社区共建API，有国际化的诉求，因此希望大家尽量用英文

- IM群每个项目自行讨论决定，包括微信群，Slack,gitter
  Layotto的话，我们可以等首届PMC成立后PMC讨论决定

- 社区会议
  每个项目自己定。欢迎各位Layotto贡献者联系我加入Layotto Contributor群，我们好商量下啥时间开会 :>

欢迎各位继续提意见！

**Comment by seeflood** [comment]
Hi guys, according to above discussion ,I submit a PR #203 to announce our community roles,promotion rules and initial PMC member list
Welcome to give your advice or different opinions!
Meanwhile,if you are interested to join in as special roles like Member, Reviewer or Committer, please contact me

**Comment by Xunzhuo** [comment]
Hi @seeflood, I am interested in the membership of member or reviewer, would you like to sponsor me?
