### ISSUE TITLE
Translate chinese documents into english

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#202]
**What would you like to be added**:

Translate these chinese documents into english:
将文档贡献指南翻译成英文
将组件开发指南翻译成英文
将新增API时的开发规范翻译成英文

**Why is this needed**:
Make Layotto an international project :)

**Comment by seeflood** [comment]
This issue will be assigned to @x-shadow-man
Thks for your contribution!

**Comment by x-shadow-man** [comment]
> This issue will be assigned to @x-shadow-man
> Thks for your contribution!

thx, i'll do it!
