### ISSUE TITLE
Add usage document for go sdk; 为 go sdk 添加使用文档

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#213]
**What would you like to be added**:
Add usage document for go sdk.
Currently we don't have user document for go-sdk,see [chinese doc](http://mosn.io/layotto/#/zh/sdk_reference/go/start) and [english doc](http://mosn.io/layotto/#/en/sdk_reference/go/start).
The content of the document is not restricted,as long as we can teach users how to use it. You can take [Dapr's document](https://docs.dapr.io/developing-applications/sdks/go/) as a good example and reference.

**Why is this needed**:
Users don't know how to use Layotto without document

**Comment by arcosx** [comment]
Please assign it to me, I will be happy to write this document and this work will be completed within a week.

**Comment by seeflood** [comment]
Cool !
@arcosx Already assigned.Thanks for your passion

**Comment by arcosx** [comment]
I'm very sorry for the delay in getting the development team to track this, and I haven't had the time and energy to continue to finish this issue recently.

**Comment by seeflood** [comment]
@arcosx That's fine!
Can we reassign it to others?
Since we are going to do a new round of activities, if you don't have time to do it, we want to treat it as an activity task

**Comment by arcosx** [comment]
> @arcosx That's fine! Can we reassign it to others? Since we are going to do a new round of activities, if you don't have time to do it, we want to treat it as an activity task

You are too kind😁, of course you can.
Good luck with the activity.

**Comment by cyb0225** [comment]
Hi @seeflood.  I'm sorry to bother you so late.
I would like to confirm if someone is working on this issue or if the requirement has been abandoned. If not, I am willing to take on this assignment. I am not particularly busy with my studies at this time, so I have sufficient time to complete this job. If I do not submit a PR or comment within a week, you may reassign the task.

**Comment by seeflood** [comment]
@cyb0225 It's still available. PR welcome !

**Comment by cyb0225** [comment]
Great! I will complete the Chinese version of docs firstly. After you reviewing it, I will then proceed to translate it into English.

**Comment by wenxuwan** [comment]
> Great! I will complete the Chinese version of docs firstly. After you reviewing it, I will then proceed to translate it into English.

The current golang sdk is too simple, more like a demo display, you can try to refactor the golang sdk like Dapr. Simplify the user's use

**Comment by cyb0225** [comment]
> > Great! I will complete the Chinese version of docs firstly. After you reviewing it, I will then proceed to translate it into English.
> 
> The current golang sdk is too simple, more like a demo display, you can try to refactor the golang sdk like Dapr. Simplify the user's use

I am willing to give it a try and translate it. But I think I may need some time to have a deeper understanding of dapr, layotto, and Mosn. Do I need to complete the tutorial on using the current version of the go-sdk  firstly?  Or jump right into refactoring work on the go-sdk.

**Comment by wenxuwan** [comment]
> > > Great! I will complete the Chinese version of docs firstly. After you reviewing it, I will then proceed to translate it into English.
> > 
> > 
> > The current golang sdk is too simple, more like a demo display, you can try to refactor the golang sdk like Dapr. Simplify the user's use
> 
> I am willing to give it a try. But I think I may need some time to have a deeper understanding of dapr, layotto, and Mosn. Do I need to complete the tutorial on using the current version of the go-sdk firstly? Or jump right into refactoring work on the go-sdk.

We can complete the construction of the document first, and then try to reconstruct Layotto's Golang sdk after you have a deeper understanding of Layotto。😊

**Comment by cyb0225** [comment]
I see.

**Comment by wenxuwan** [comment]
> Hey, after serveral days of reading code, I have found that it's easy for users to use go-sdk connect to layotto and use the a serious of services with interface functions. go-sdk has not expose many interfaces to users. But it's difficult for me to write a config file especially it's my first time contact with service mesh. So I think we may need a document on how to complete a useable config more than a go-sdk using doc.

Do you mean the configuration file of Layotto?

**Comment by cyb0225** [comment]
yeah，most of my current configuration items refer to the config of mosn docs and demos.

**Comment by cyb0225** [comment]
> > Hey, after serveral days of reading code, I have found that it's easy for users to use go-sdk connect to layotto and use the a serious of services with interface functions. go-sdk has not expose many interfaces to users. But it's difficult for me to write a config file especially it's my first time contact with service mesh. So I think we may need a document on how to complete a useable config more than a go-sdk using doc.
> 
> Do you mean the configuration file of Layotto?

Yeah, most of my current configuration items refer to the config of mosn and demo

**Comment by cyb0225** [comment]
> > > > Hey, after serveral days of reading code, I have found that it's easy for users to use go-sdk connect to layotto and use the a serious of services with interface functions. go-sdk has not expose many interfaces to users. But it's difficult for me to write a config file especially it's my first time contact with service mesh. So I think we may need a document on how to complete a useable config more than a go-sdk using doc.
> > > 
> > > 
> > > Do you mean the configuration file of Layotto?
> > 
> > 
> > Yeah, most of my current configuration items refer to the config of mosn and demo
> 
> So what you want to do is provide a document that states the configuration options for Layotto？

Yes. Most of the configuration options can refer to the [docs of mosn](https://mosn.io/docs/products/configuration-overview/). 
I think we can explain how to write the configuration of various middleware for layotto and build the environment, etc. But I'm not sure if this is necessary.

**Comment by wenxuwan** [comment]
> > > > > Hey, after serveral days of reading code, I have found that it's easy for users to use go-sdk connect to layotto and use the a serious of services with interface functions. go-sdk has not expose many interfaces to users. But it's difficult for me to write a config file especially it's my first time contact with service mesh. So I think we may need a document on how to complete a useable config more than a go-sdk using doc.
> > > > 
> > > > 
> > > > Do you mean the configuration file of Layotto?
> > > 
> > > 
> > > Yeah, most of my current configuration items refer to the config of mosn and demo
> > 
> > 
> > So what you want to do is provide a document that states the configuration options for Layotto？
> 
> Yes. Most of the configuration options can refer to the [docs of mosn](https://mosn.io/docs/products/configuration-overview/). I think we can explain how to write the configuration of various middleware for layotto and build the environment, etc. But I'm not sure if this is necessary.

You are right, contributions are welcome 👏👏

**Comment by cyb0225** [comment]
> > > > > > Hey, after serveral days of reading code, I have found that it's easy for users to use go-sdk connect to layotto and use the a serious of services with interface functions. go-sdk has not expose many interfaces to users. But it's difficult for me to write a config file especially it's my first time contact with service mesh. So I think we may need a document on how to complete a useable config more than a go-sdk using doc.
> > > > > 
> > > > > 
> > > > > Do you mean the configuration file of Layotto?
> > > > 
> > > > 
> > > > Yeah, most of my current configuration items refer to the config of mosn and demo
> > > 
> > > 
> > > So what you want to do is provide a document that states the configuration options for Layotto？
> > 
> > 
> > Yes. Most of the configuration options can refer to the [docs of mosn](https://mosn.io/docs/products/configuration-overview/). I think we can explain how to write the configuration of various middleware for layotto and build the environment, etc. But I'm not sure if this is necessary.
> 
> You are right, contributions are welcome 👏👏

Thanks for your patience, I'll try to get it done this weekend. :smile::smile:

**Comment by cyb0225** [comment]
@wenxuwan, I have already understanding the process of how layotto running and ready to write the docs. Can I add some docker-compose and config files to the repo for newcomers getting started faster？

**Comment by wenxuwan** [comment]
> @wenxuwan, I have already understanding the process of how layotto running and ready to write the docs. Can I add some docker-compose and config files to the repo for newcomers getting started faster？

Of course, looking forward to your PR
