### ISSUE TITLE
[Proposal]Secret API design

### ISSUE THREAD

**Issue by MentosL** [mosn/layotto#214]
Add Layotto secret API. To generate key dependent interface definitions, similar to  [dapr](https://docs.dapr.io/developing-applications/building-blocks/secrets/)
 
 English explanation will be added later
 
 # Secret API设计文档
 本文档讨论"密钥相关"的API
 
 ## 1. 需求
 ### 1.1. 密钥管理
 Q: 为何需要密钥管理？

 A: 应用程序在执行过程中大多数会使用专门的密钥去访问外部服务，通常需要建议一个对应的密钥存储来管理。
  
 Q: Layotto Secret API充当的角色？

 A: 提供管理密钥以及允许开发人员通过API获得密钥的功能，充当密钥管理者角色。
  
 ## 2. 产品调研
 | 平台方  | 提供功能  |
 |--|--|
 |dapr|访问权限（可依赖各自云产品支持），密钥管理，检索密钥|
 |云密钥产品相关|访问权限，密钥管理，检索密钥|
 
 ## 3. grpc API设计
 在制定对应API时，需要考虑每个密钥的唯一资源定位因素有哪些？

* 存放空间地址
* 密钥对应名称
* 密钥对应版本
* 密钥对应状态

&emsp;&emsp;其中最为主要的则是前两个。版本默认latest，而状态则默认取生效，如没有生效的密钥，则需要业务去判断下一步操作。

 ### 3.1. proto定义
```proto
  // Gets secrets from secret stores.
  rpc GetSecret(GetSecretRequest) returns (GetSecretResponse) {}

  // Gets a bulk of secrets
  rpc GetBulkSecret(GetBulkSecretRequest) returns (GetBulkSecretResponse) {}
  
  // GetSecretRequest is the message to get secret from secret store.   
message GetSecretRequest {
  // The name of secret store.
  string store_name = 1;

  // The name of secret key.
  string key = 2;

  // The metadata which will be sent to secret store components.
  // Contains version, status, and so on...
  map<string,string> metadata = 3;
}

// GetSecretResponse is the response message to convey the requested secret.
message GetSecretResponse {
  // data is the secret value. Some secret store, such as kubernetes secret
  // store, can save multiple secrets for single secret key.
  map<string, string> data = 1;
}


// GetBulkSecretRequest is the message to get the secrets from secret store.
message GetBulkSecretRequest {
  // The name of secret store.
  string store_name = 1;

  // The metadata which will be sent to secret store components.
  map<string,string> metadata = 2;
}


// GetBulkSecretResponse is the response message to convey the requested secrets.
message GetBulkSecretResponse {
  // data hold the secret values. Some secret store, such as kubernetes secret
  // store, can save multiple secrets for single secret key.
  map<string, SecretResponse> data = 1;
}


// SecretResponse is a map of decrypted string/string values
message SecretResponse {
  map<string, string> secrets = 1;
}
```
 
 **Q: 是否由Layotto帮用户实现对应密钥获取实现？**
 
 A: API和Layotto运行时不管这事，由sdk或者用户自己处理，或者某个特殊组件想实现这个feature也可以。
 
 ## 4. 组件API
 ```go
 package secretstores
 
 type SecretStore interface {
 		// Init authenticates with the actual secret store and performs other init operation
	Init(metadata Metadata) error
	// GetSecret retrieves a secret using a key and returns a map of decrypted string/string values
	GetSecret(req GetSecretRequest) (GetSecretResponse, error)
	// BulkGetSecrets retrieves all secrets in the store and returns a map of decrypted string/string values
	BulkGetSecret(req BulkGetSecretRequest) (BulkGetSecretResponse, error)
 }
 
// GetSecretRequest describes a get secret request from a secret store.
type GetSecretRequest struct {
	Name     string            `json:"name"`
	Metadata map[string]string `json:"metadata"`
}

// BulkGetSecretRequest describes a bulk get secret request from a secret store.
type BulkGetSecretRequest struct {
	Metadata map[string]string `json:"metadata"`
}

// GetSecretResponse describes the response object for a secret returned from a secret store.
type GetSecretResponse struct {
	Data map[string]string `json:"data"`
}

// BulkGetSecretResponse describes the response object for all the secrets returned from a secret store.
type BulkGetSecretResponse struct {
	Data map[string]map[string]string `json:"data"`
}

// DefaultSecretRefKeyName is the default key if secretKeyRef.key is not given.
const DefaultSecretRefKeyName = "_value"

// Metadata contains a secretstore specific set of metadata properties.
type Metadata struct {
	Properties map[string]string `json:"properties,omitempty"`
}
 ```
 
 
 ## 参考资料
 [dapr密钥管理概览](https://docs.dapr.io/zh-hans/developing-applications/building-blocks/secrets/secrets-overview/)
 
 [AWS Secrets Manager](https://aws.amazon.com/cn/secrets-manager/features/)
 
 [Microsoft Key Vault](https://docs.microsoft.com/zh-cn/rest/api/keyvault)
 
 [Azure Key Vault](https://docs.azure.cn/zh-cn/key-vault/general/overview)
 
 [阿里云密钥管理服务](https://help.aliyun.com/document_detail/28935.html)

**Comment by MentosL** [comment]
关联对应task     #212

**Comment by nobodyiam** [comment]
Looks good!

**Comment by seeflood** [comment]
Thanks for your contribution!

**Comment by seeflood** [comment]
>Q: 是否由Layotto帮用户实现对应密钥获取实现？
>A: API和Layotto运行时不管这事，由sdk或者用户自己处理，或者某个特殊组件想实现这个feature也可以。

这句话是啥意思呀

个人观点：
1.  API看着没问题哈，满足以下要求即可：
   - grpc secret API和Dapr的一样
   - 组件直接复用Dapr的组件（直接import Dapr的组件包，类似于State API)，这样即使有新的组件需求，直接给Dapr提pr即可
2. API之外，其实还有一些secret相关的功能需要做下设计，这些功能我们没必要这次就做（可以分成几个迭代、以后再做，或者以后可能由社区其他人做），但是需要提前设计下、想清楚后面怎么加功能（免得这次代码写好了、以后加新功能的时候发现不好改了）。具体需要考虑的功能包括：
   - 让其他API的组件在配置文件中可以引用密文。比如state API的redis组件，它在配置里要配连redis时候的账号密码，密码配置可以直接引用secret。见 https://docs.dapr.io/operations/components/component-secrets/
   - 密钥的访问控制，比如限制app1能访问的密钥的白名单、黑名单等，见 https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-scopes/

Again，这些功能加起来工作量太大，这次只实现secret API即可，但是最好考虑下这些功能以后想做的话咋做~

**Comment by MentosL** [comment]
> > Q: 是否由Layotto帮用户实现对应密钥获取实现？
> > A: API和Layotto运行时不管这事，由sdk或者用户自己处理，或者某个特殊组件想实现这个feature也可以。
> 
> 这句话是啥意思呀
> 
> 个人观点：
> 
> 1. API看着没问题哈，满足以下要求即可：
>    
>    * grpc secret API和Dapr的一样
>    * 组件直接复用Dapr的组件（直接import Dapr的组件包，类似于State API)，这样即使有新的组件需求，直接给Dapr提pr即可
> 2. API之外，其实还有一些secret相关的功能需要做下设计，这些功能我们没必要这次就做（可以分成几个迭代、以后再做，或者以后可能由社区其他人做），但是需要提前设计下、想清楚后面怎么加功能（免得这次代码写好了、以后加新功能的时候发现不好改了）。具体需要考虑的功能包括：
>    
>    * 让其他API的组件在配置文件中可以引用密文。比如state API的redis组件，它在配置里要配连redis时候的账号密码，密码配置可以直接引用secret。见 https://docs.dapr.io/operations/components/component-secrets/
>    * 密钥的访问控制，比如限制app1能访问的密钥的白名单、黑名单等，见 https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-scopes/    这个我们也可以配置在Layotto的json配置文件里
> 
> Again，这些功能加起来工作量太大，这次只实现secret API即可，但是最好考虑下这些功能以后想做的话咋做~
> 这涉及的东西比较多，我帮你一起想下

上面的QA想表达的是  当前API设计  只是设计接口，具体的实现由底下第三方或者业务自身去实现。


观点一 ： 当前API接口的定义也是根据Dapr来的。
观点二：
 ① ： 以上设计只是涉及到对应的传输接口，如果涉及到对应密钥的坐标获取，则可能需要了解当前坐标获取密钥的几种途径，例如直接deploy一个pod去获取，或通过注册中心获取等。
②： 同意优先考虑关于权限控制的这块设计，这个设计应该在我们功能设计API接口之前进行优先完成。哪怕简单的RBAC去控制权限也很好。

**Comment by seeflood** [comment]
@MentosL Hi大佬 你还在搞这个么~过程中有没有遇到啥问题

**Comment by MentosL** [comment]
> @MentosL Hi大佬 你还在搞这个么~过程中有没有遇到啥问题

咳咳 大佬  是在搞的  就差个单元测试。然后目前我这边工作有点变动..... 所以  可能还需要晚一些时间提交上去

**Comment by seeflood** [comment]
@MentosL 噢噢明白！老哥跳槽了吗，先花时间熟悉新工作环境吧,工作恰饭更重要哈哈

**Comment by MentosL** [comment]
> @MentosL 噢噢明白！老哥跳槽了吗，先花时间熟悉新工作环境吧,工作恰饭更重要哈哈

😂   还在找还在找
