### ISSUE TITLE
Can not build -tags wander in Apple Silicon chip.

### ISSUE THREAD

**Issue by khotyn** [mosn/layotto#216]
According to the [document](https://mosn.io/layotto/#/en/start/wasm/start), run the following command to build WASM on Layotto:

```
go build -tags wasmer -o ./layotto ./cmd/layotto/main.go
```

build failed and got an error:

```
➜  layotto git:(update_wasmer_go) ✗ go build -v -tags wasmer -o ./layotto ./cmd/layotto/main.go
github.com/wasmerio/wasmer-go/wasmer
# github.com/wasmerio/wasmer-go/wasmer
ld: library not found for -lwasmer
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wenxuwan** [comment]
@khotyn i use the same command with u , doesn't occur the error, can you provider the verison of layotto and golang, by the way the wasmer-go to 1.0.4 package imported by mosn, add this package in layotto with indirect maybe no good method, an pr for mosn should be better.
