### ISSUE TITLE
Ignore the build result binary

### ISSUE THREAD

**Issue by khotyn** [mosn/layotto#218]
If you run the command

```
go build -tags wasmer -o ./layotto ./cmd/layotto/main.go
```

you will got and `layotto` binary in the working directory and is not ignored by git. People could commit the binary to the git repo by accident.

**Comment by khotyn** [comment]
When run the redis example, also got an binary `demo/state/redis/client`

**Comment by seeflood** [comment]
Thanks for your feedback!
Since these pr have been merged,I will close this issue. You can reopen it if something missed
