### ISSUE TITLE
Add components for file interface

### ISSUE THREAD

**Issue by wenxuwan** [mosn/layotto#236]
**What would you like to be added:**
 
Layotto support file interface now, and have implemented the [alioss](https://help.aliyun.com/product/31815.html?spm=5176.22414175.sslink.2.19d9d8a6z4eRDE) component.

So this issue want to support other file system, eg, 

- [x] [awsOss](https://aws.amazon.com/cn/campaigns/free/?sc_channel=PS&sc_campaign=acquisition_CN&sc_publisher=google&sc_category=pc&sc_medium=Google_%E5%93%81%E7%89%8C_%E6%A0%B8%E5%BF%83%E5%93%81%E7%89%8C%E8%AF%8D_b&sc_content=%E6%A0%B8%E5%BF%83%E5%93%81%E7%89%8C%E8%AF%8D&sc_detail=aws&sc_segment=2021092300256&sc_matchtype=exact&sc_country=CN&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all) assigned to @zach030
- [ ] local file system(file on local disk)
- [ ] [HDFS](https://hadoop.apache.org/)
- [x] [minIo](http://www.minio.org.cn/)  assigned to @zach030
- [ ] ftp
- many other file systems...

You can refer the interface design document of file [component interface design](https://mosn.io/layotto/#/zh/design/file/file-design),[api design](https://mosn.io/layotto/#/zh/api_reference/file/file)

**Comment by zach030** [comment]
I wanna take this issue

**Comment by seeflood** [comment]
We can use existing sdk-lib to integrate with different file systems. For example, @zu1k once recommended https://github.com/beyondstorage/go-storage  ,it can serve as clients for many backend storages:
![image](https://user-images.githubusercontent.com/26001097/135383531-7a09bf8a-5494-4697-b0dc-2a0bb7f9b5f6.png)

**Comment by seeflood** [comment]
> I wanna take this issue

Cool!
Which file system component would u like to implement?

**Comment by zach030** [comment]
> > I wanna take this issue
> 
> Cool! Which file system component would u like to implement?

I wanna implement aws Oss first!
Since it's easy to integrate with sdk go-storage, I will try to implement other file system then.

**Comment by seeflood** [comment]
@zach030 Good! 
I assigned the task of aws Oss  to you. We look forward to your valuable contributions!

**Comment by seeflood** [comment]
Some tips for who want to implement File API component:
Currently the [usage document of File API](https://mosn.io/layotto/#/en/api_reference/file/file) is WRONG and you can check the [proto file](https://github.com/mosn/layotto/blob/main/spec/proto/runtime/v1/runtime.proto) as the real definition of File grpc API. We are waiting for @wenxuwan to fix it :)
![image](https://user-images.githubusercontent.com/26001097/135389220-93ff178c-974e-4f7f-9dcb-809bdcbb7c38.png)

**Comment by wenxuwan** [comment]
> Some tips for who want to implement File API component: Currently the [usage document of File API](https://mosn.io/layotto/#/en/api_reference/file/file) is WRONG and you can check the [proto file](https://github.com/mosn/layotto/blob/main/spec/proto/runtime/v1/runtime.proto) as the real definition of File grpc API. We are waiting for @wenxuwan to fix it :) ![image](https://user-images.githubusercontent.com/26001097/135389220-93ff178c-974e-4f7f-9dcb-809bdcbb7c38.png)

done https://github.com/mosn/layotto/pull/245

**Comment by bokket** [comment]
> @bokket Cool,where can we join in the matrix room? Besides, @zach030 is also preparing to integrate Layotto with beyondstorage.So which version of beyondstorage should we use?Is v5 version compatible with legacy systems based on v4 or even older version?

sorry for my problem.Here is the [link](https://matrix.to/#/#beyondstorage@campfire:matrix.org).`v5.0` is mainly a restructuring of the project, not moving API.Next week it will basically work.
