### ISSUE TITLE
feat: add commit message lint to workflow

### ISSUE THREAD

**Issue by Xunzhuo** [mosn/layotto#243]
## **What would you like to be added**:

New workflow to check commit message standard

## **Why is this needed**:

In the layotto commit history, we can see the commit message without any standard and it is hard to read. As projects grow up, there will be more and more commits with messages, if we don not any commit lint, it will be a trouble to check and review history commits.

### Advantages:
+ 提供更多的历史信息，方便快速浏览。
+ 可以过滤某些commit（比如文档改动），便于快速查找信息
+ 可以直接从commit生成Change log。
+ 可读性好，清晰，不必深入看代码即可了解当前commit的作用。
+ 为 Code Reviewing做准备
+ 方便跟踪工程历史
+ 提高项目的整体质量，提高个人工程素质

### Demo

![demo](https://user-images.githubusercontent.com/48784001/135706144-cd3e3335-1ae0-422a-bd43-e8099b1ffdd2.png)

Commit Message Format
Each commit message consists of a header, a body and a footer. The header has a special format that includes a type, a scope and a subject:

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

Details: https://github.com/conventional-changelog/commitlint

**Comment by nobodyiam** [comment]
good point

**Comment by Xunzhuo** [comment]
There is a tool to create commit message in standard called `Commitizen`, which I am using
Refer link is https://github.com/commitizen-tools/commitizen.
In MacOS, we can easily install it with `brew install commitizen`, and we can use `cz c` instead of `git commit -m`
These are the screenshots of demos:
<img width="1172" alt="截屏2021-10-03 上午11 38 24" src="https://user-images.githubusercontent.com/48784001/135738697-06924f08-a0e8-49a7-b901-028b65d57343.png">


<img width="690" alt="截屏2021-10-03 上午11 38 42" src="https://user-images.githubusercontent.com/48784001/135738703-2c1bb883-0102-452e-837f-6ce47a09f103.png">

**Comment by ZLBer** [comment]
@seeflood  do we need  pr title check now? find an action,  i  have tested it,  we can add. 
https://github.com/thehanimo/pr-title-checker

**Comment by seeflood** [comment]
@ZLBer It sounds good ! I think we need it. 
We can add some guideline on "how to format the PR title and pass the PR title check" in [the document](https://mosn.io/layotto/#/zh/development/explanation-for-github-workflow). 
When users have trouble fixing the CI ,we can send them the document link and help them

**Comment by ZLBer** [comment]
@seeflood fine,  late commit
