### ISSUE TITLE
Make File API easy to debug locally

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#296]
**What would you like to be added**:
Make File API easy to debug locally,including:
- [ ] Add config.json file and component references for minio and awsoss. Take alicloudOss' [config file](https://github.com/mosn/layotto/blob/main/configs/config_file.json) and [the existing component references](https://mosn.io/layotto/#/zh/component_specs/lock/redis) as examples
- [ ] Add a local file system component for File API,so that users don't have to start a minio server.

**Why is this needed**:
According to feedback from our developer ,currently the File API is hard to debug and test locally.
![image](https://user-images.githubusercontent.com/26001097/139589193-bff878ad-e2c0-4532-99a3-573df53add6c.png)

**Comment by seeflood** [comment]
@zach030 Hi,could u help add config.json and component doc for Minio and AwsOss? Since u are familiar with these two components

**Comment by zach030** [comment]
> @zach030 Hi,could u help add config.json and component doc for Minio and AwsOss? Since u are familiar with these two components

Great, I will implement it.

**Comment by wenxuwan** [comment]
@zach030 i add local file system implementation ,  you can check if it's help for understand and debug,. https://github.com/mosn/layotto/pull/297
