### ISSUE TITLE
bug: unauthorized access in Alicloud OSS component

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#301]
**What happened**:
If an app pass a directoryName which is not configurated in the config file,it can access that bucket although it shouldn't.
Currently the code doesn't do the access control checking.
![image](https://user-images.githubusercontent.com/26001097/139809924-1472f25f-6faf-4fca-92db-c0f01547241b.png)

![image](https://user-images.githubusercontent.com/26001097/139809950-ab0e8190-7769-4817-bbf4-2c3d2b894ab9.png)

**What you expected to happen**:
Forbid unauthorized access

**How to reproduce it (as minimally and precisely as possible)**:
@fengmk2 found it by code review 

**Anything else we need to know?**:

**Comment by ZLBer** [comment]
@seeflood   alicloud/aws/minio components  both  have this problem.  I'll  fix this .
The meaning of the bukect field is not clearly stated in the `fileAPI qucick start` file, a little fuzzy, 
![image](https://user-images.githubusercontent.com/20033804/140285276-bdf9b313-50d8-4755-be8e-d46d511f5997.png)

`_sidebar.md`  quick start lack `fileAPI`.

**Comment by seeflood** [comment]
> @seeflood alicloud/aws/minio components both have this problem. I'll fix this .

Sorry for not explaining in advance, @wenxuwan just told me that he is working on it and decides to remove this `bucket` configuration and do some refactor for File API. So this issue will be assigned to him. 
Actually the `accessKeyID` and `accessKeySecret` fields are enough to do access control,so the `bucket` field is redundent. 
Hope he will add a quickstart for File API after the refactor :)

**Comment by ZLBer** [comment]
@seeflood  Okay, I get it

**Comment by wenxuwan** [comment]
@ZLBer Hi man, as the current file interface capabilities are not enough to support users,https://github.com/mosn/layotto/issues/98, I am redesigning the interface and modifying the implementation, you can help review it together.https://github.com/mosn/layotto/pull/305
