### ISSUE TITLE
Ut fails in `components` package

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#363]
**What happened**:
Ut fails when testing `components` package.
I fixed the compilation errors of the ut in #362 .
But there are still some test failures:
![image](https://user-images.githubusercontent.com/26001097/145932087-fa58fe56-6990-4a4a-ae05-85e634c1ae1f.png)

- [x] fix ut for zookeeper lock . assigned to @ZLBer 
- [x] fix ut for etcd sequencer. assigned to @whalesongAndLittleFish 
- [x] modify the configuration to test `components` package in our CI pipeline
- [x] fix ut for RPC

**What you expected to happen**:
All code pass ut successfully

**How to reproduce it (as minimally and precisely as possible)**:
```
go test components
```

**Anything else we need to know?**:

**Comment by seeflood** [comment]
@ZLBer Hi, could you help fix the zookeeperLock test cases?

**Comment by whalesongAndLittleFish** [comment]
I want to try to fix the unit test of etcd sequencer,please assign to me

**Comment by seeflood** [comment]
@whalesongAndLittleFish Cool,Thanks!
assigned to you

**Comment by ZLBer** [comment]
@seeflood  sure  i will fix zk lock ut

**Comment by seeflood** [comment]
![image](https://user-images.githubusercontent.com/26001097/145970354-b1266c36-6b57-41f9-b87e-e22c1166fbfd.png)
update: I just found that RPC tests are not stable and sometimes fail

**Comment by seeflood** [comment]
All fixed
