### ISSUE TITLE
feat: layotto spring-boot

### ISSUE THREAD

**Issue by ZLBer** [mosn/layotto#371]
**What would you like to be added**:
I found layotto spring-boot in the community tasks, and want to implement it.
I went to understand the implementation of dapr spring-boot and found that it is more complicated. 
When a method is annotated by `@Topic` (it needs to be annotated by `@PostMaping` at the same time), the route (maybe a url) of this method will be saved and exposed through `/dapr/subscribe`. When dapr runtime starts, it will go to `dapr/subscribe` to pull subscription information, and then subscribe( the code logic in the dapr), when subscription occurs, it will call back the route.

Does layotto spring-boot need to be implemented like this? In a simple way, when the method is annotated by @Topic, just subscribe to this topic in the java-sdk. But but... this puts the code logic in the sdk again!

**Why is this needed**:

**Comment by seeflood** [comment]
There was an issue discussing java-sdk and layotto-sdk-springboot,see https://github.com/mosn/layotto/issues/206

>Does layotto spring-boot need to be implemented like this? In a simple way, when the method is annotated by @Topic, just subscribe to this topic in the java-sdk. But but... this puts the code logic in the sdk again!

The layotto-sdk-springboot can be implemented as a seperate module which imports java-sdk and has a `@Topic` annotation and some auto-subscription logic in it. 
It's ok that we put some logic in layotto-sdk-springboot module as long as we we keep the java-sdk module simple.
The `layotto-sdk-springboot` can be regarded as a sugar for springboot users :)

**Comment by ZLBer** [comment]
@seeflood I know, I will do it, then I will put the code logic in the`layotto-spring-boot` sdk.

**Comment by seeflood** [comment]
@ZLBer niu b

**Comment by ZLBer** [comment]
@seeflood why `registerPubSubCallback` params only contains pubsubname?
![image](https://user-images.githubusercontent.com/20033804/147094770-4746a8fd-e0bf-4da4-a85a-12a838a85d9c.png)

**Comment by seeflood** [comment]
@ZLBer Users can write different Subscriber callback for different pubsub component ,e.g. RocketMQSubscriber for RocketMQ, ActiveMQSubscriber for ActiveMQ.

![image](https://user-images.githubusercontent.com/26001097/147114300-c6c2f0c0-4ade-4bd5-b7df-dd5a96c6f643.png)

For example, RocketMQSubscriber.listTopicAndSubscriptions may invoke a rocketmq client,while ActiveMQSubscriber.listTopicAndSubscriptions not

**Comment by ZLBer** [comment]
@seeflood  so I'm a little confused, why not provide a method `registerCallback(pubsubName, topic, callback)`?

**Comment by RayneHwang** [comment]
> @seeflood so I'm a little confused, why not provide a method `registerCallback(pubsubName, topic, callback)`?

The `Subscriber` interface here is actually not the `subscriber`  commonly referenced in messaging systems that subscribes to topics. This subscriber could have been more precisely named as "deliver request dispatcher" that dispatches deliver message requests to pubsub SDKs according to pubsub component name, hence `registerPubSubCallback` only accepts a `pubsubNam` argument. It it the concrete pubsub component's stuff to determine which user-defined listener should be invoked according to topic or other metadata in TopicEventRequest.

**Comment by seeflood** [comment]
> @seeflood so I'm a little confused, why not provide a method `registerCallback(pubsubName, topic, callback)`?

Is @RayneHwang 's explanation enough? He is the author of it.
To my understanding ,  @RayneHwang 's concern was : some mq dispatch messages not according to `topic`,but some other field like `eventCode` and `xxx`, so he decide that it should be `registerCallback(pubsubName, callback) ` instead of `registerCallback(pubsubName, topic, callback) `.


Emmmmmm, for me, both design styles are fine :)

**Comment by ZLBer** [comment]
@RayneHwang @seeflood  I understand, but every user who wants to subscribe to a topic has to implement the distribution logic in his own method. a little bit difficult  but not a big problem . I will implement it according to this logic

**Comment by seeflood** [comment]
You are right.Maybe we can add a defaultSubscriber to make it easier to use?

**Comment by ZLBer** [comment]
@seeflood can i move this from example  to sdk and change it to defaultSubscriber ？
![image](https://user-images.githubusercontent.com/20033804/147317316-6fb9bc22-d62a-45e2-9871-57ff8a4facf0.png)

**Comment by seeflood** [comment]
yes you can
