### ISSUE TITLE
Why is `OpenGenerator.GetSpanId` the same as `OpenGenerator.GetParentSpanId`

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#381]
### Your question

I just found that `OpenGenerator.GetSpanId` is the same as `OpenGenerator.GetParentSpanId`.
To my understanding, the spanId should be different with `parentSpanId`. Is it a bug ?
![image](https://user-images.githubusercontent.com/26001097/149537224-f87f3ae1-2fd4-4f4a-9cf1-4a11d1515ae0.png)

### Environment

- Layotto Version
main branch

### Logs

- Paste the logs you see.

**Comment by wenxuwan** [comment]
now layotto as the sidecar with app, and no ingress flow, so here use same logic
