### ISSUE TITLE
[Proposal] Add an `extends` field in the config.json for extendibility

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#383]
**What would you like to be added**:
Add an `extends` field in the `config.json` , so that users can add their own configuration items and corrosponding parser function. 

For example ,  a user is doing some extensions based on layotto and he wants to add a dump feature. To do that, he should configurate a local files system path telling layotto where to dump. In this scenario, he can modify the `config.json` file and change it to this:
```
{
  "server_name": "runtime",
  "grpc_config": {
    "extends": {
      "dump": {
        "path": "/home/admin/layotto/dump"
      }
    },
    "hellos": {
      "helloworld": {
        "hello": "greeting"
      }
    },
    //......
  }
}
```

After that, he should write his own parser function parsing this `dump` configuration:
```
func Parse(data json.RawMessage) error {
  // parse the dump configuration
  // ......
}
```
And then register this parser function in `main.go`

**Why is this needed**:
For extendibility

**Comment by zhenjunMa** [comment]
+1

**Comment by stulzq** [comment]
+1
