### ISSUE TITLE
Dapr启动的时候，不是蚂蚁和微软一起发起的？为什么现在不支持dapr了？

### ISSUE THREAD

**Issue by xewn** [mosn/layotto#389]
Dapr第一次了解，就是从蚂蚁和微软合作开始的。
为什么不继续完善Dapr，而是又搞一套新的。这样会不会让学习成本更高呢？
Dapr支持的语言比较多，会不会更有优势呢？

**Comment by seeflood** [comment]
Dapr是微软发起的哈，Layotto的目标是在service mesh的数据面上去支持dapr api，通过共建把api做成一个社区标准，见 https://github.com/dapr/dapr/issues/2817#issuecomment-1021415191
可以理解成“dapr api的另一种实现”
