### ISSUE TITLE
Connect Apollo Server Fail

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#420]
**What happened**:
A `Connect Apollo Server Fail` error sometimes appears when running our demo. It might be [apollo demo server](106.54.227.205)'s problem or someone modified some configuration in that server.
We have to make our demo more robust.
>2022-03-18 14:50:10,97 [ERROR] request [[configs/testApplication_yang/default/sidecar_config_tags?releaseKey=&ip=30.46.242.196 over Max Retry Still Error]] fail, error:%!v(MISSING)
2022-03-18 14:50:12,192 [ERROR] Connect Apollo Server Fail,url:[[http://106.54.227.205:8080/configs/testApplication_yang/default/sidecar_config_tags?releaseKey=&ip=30.46.242.196 %!s(int=404)]],StatusCode:%!s(MISSING)

**What you expected to happen**:
Run demo succesfully

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by seeflood** [comment]
pubsub API demo will use redis instead, See #423

**Comment by nobodyiam** [comment]
it looks like the namespace `sidecar_config_tags` was deleted by someone

http://106.54.227.205/config.html?#/appid=testApplication_yang

![image](https://user-images.githubusercontent.com/837658/159105134-f957a58c-5511-4f1d-931f-855aa124a48a.png)

**Comment by seeflood** [comment]
fixed.
@nobodyiam Layotto apollo component will create the namespace automatically. But the token was somehow invalid.
I authorized the token again according to [the document](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform?id=_22-%e7%bb%99%e5%b7%b2%e6%b3%a8%e5%86%8c%e7%9a%84%e7%ac%ac%e4%b8%89%e6%96%b9%e5%ba%94%e7%94%a8%e6%8e%88%e6%9d%83) and the error disappeared
