### ISSUE TITLE
源码解析: 处理 rpc 请求

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#424]
Note: since this is a Chinese community activity,I wrote it in Chinese.
 
### 介绍
阅读源码，分析 Layotto 处理rpc请求的流程。

Layotto “寄生”在 MOSN 里，rpc请求到达sidecar时，其实是先经过 MOSN、MOSN通过[grpcFilter](https://github.com/mosn/mosn/blob/master/pkg/filter/network/grpc/filter.go) 把流量转给 Layotto ，Layotto 解包、处理之后，再通过一对虚拟连接(net.Pipe) 将流量转给MOSN, MOSN做流量转发

### 参考解析

- 处理 rpc 请求的流程是什么样的

###  参考阅读
[进行RPC调用--helloworld](https://mosn.io/layotto/#/zh/start/rpc/helloworld)
[进行RPC调用--Dubbo JSON RPC Example](https://mosn.io/layotto/#/zh/start/rpc/dubbo_json_rpc)
https://mosn.io/layotto/#/zh/building_blocks/rpc/reference
https://mosn.io/layotto/#/zh/design/rpc/rpc%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3

### 源码解析文章的格式
可以参考之前 “MOSN 源码解析活动”的文章格式 https://mosn.io/blog/code/

**Comment by rayowang** [comment]
assign

**Comment by seeflood** [comment]
@rayowang 欢迎加入社区~ 过程中遇到问题随时讨论哈，微信 钉钉 github都可以联系
