### ISSUE TITLE
源码解析: 4层流量治理，tcp流量dump

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#425]
Note: since this is a Chinese community activity,I wrote it in Chinese.
 
### 介绍
阅读源码，分析 Layotto 是怎么做 tcp流量dump的

Layotto “寄生”在 MOSN 里, 可以通过 MOSN的[4层filter扩展机制](https://mosn.io/docs/concept/extensions/) 写filter、做流量治理
Layotto 项目里自带了一个filter、做tcp流量dump，用于演示如何扩展4层filter，见 https://mosn.io/layotto/#/zh/start/network_filter/tcpcopy

###  参考阅读
https://mosn.io/layotto/#/zh/start/network_filter/tcpcopy
`pkg/filter/network/tcpcopy` 这个目录下的代码

### 源码解析文章的格式
可以参考之前 “MOSN 源码解析活动”的文章格式 https://mosn.io/blog/code/

**Comment by GOODBOY008** [comment]
assign

**Comment by seeflood** [comment]
@GOODBOY008  欢迎~~有问题可以随时聊哈，群里或者github都行
