### ISSUE TITLE
源码解析: 7层流量治理,接口限流

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#426]
Note: since this is a Chinese community activity,I wrote it in Chinese.
 
### 介绍
阅读源码，分析 Layotto 是怎么做接口限流的

Layotto “寄生”在 MOSN 里, 可以通过 MOSN的[7层stream filter扩展机制](https://mosn.io/docs/concept/extensions/) 写stream filter、做流量治理
[Layotto 官方文档中提供了一个接口限流的示例](https://mosn.io/layotto/#/zh/start/stream_filter/flow_control)，用于演示如何扩展7层流量治理功能，其中用到的 stream filter在 MOSN 项目中。

###  参考阅读
[Layotto 官方文档中提供了一个接口限流的示例](https://mosn.io/layotto/#/zh/start/stream_filter/flow_control)

代码在 https://github.com/mosn/mosn/tree/master/pkg/filter/stream/flowcontrol

### 源码解析文章的格式
可以参考之前 “MOSN 源码解析活动”的文章格式 https://mosn.io/blog/code/

**Comment by kuaile-zc** [comment]
assign

**Comment by seeflood** [comment]
@kuaile-zc 欢迎~~有问题可以随时聊哈，群里或者github都行

**Comment by kuaile-zc** [comment]
[flowcontrol_code_analyze_.md](https://github.com/mosn/layotto/files/8501116/flowcontrol_code_analyze_.md)

**Comment by seeflood** [comment]
@kuaile-zc 感谢贡献！可以直接提pull request、修改 [layotto 的官方文档](https://mosn.io/layotto/#/zh/blog/exploration-and-practice-of-antcloud-native-application-runtime-archsummit-shanghai) 哈
可以参照[文档贡献指南](https://mosn.io/layotto/#/zh/development/contributing-doc) 
可以放在"博客"目录下
![image](https://user-images.githubusercontent.com/26001097/163778399-7333f38d-7781-41d3-a514-1e593d4dfe65.png)
