### ISSUE TITLE
源码解析: WebAssembly相关

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#427]
Note: since this is a Chinese community activity,I wrote it in Chinese.
 
### 介绍
阅读源码，分析 Layotto中 WebAssembly 相关功能

Layotto 支持加载并运行以 wasm 为载体的 Function，并支持Function之间互相调用以及访问基础设施，如Redis。应用可以通过http请求访问Layotto、调用相应的 Function。

###  参考阅读
https://mosn.io/layotto/#/zh/start/wasm/start
https://mosn.io/layotto/#/zh/start/faas/start
[WebAssembly 在 MOSN 中的实践 - 基础框架篇](https://mosn.io/blog/posts/mosn-wasm-framework/)

### 源码解析文章的格式
可以参考之前 “MOSN 源码解析活动”的文章格式 https://mosn.io/blog/code/

**Comment by rayowang** [comment]
assign

**Comment by seeflood** [comment]
@rayowang Cool . Assigned to u
