### ISSUE TITLE
Proposal: 文档治理工程化

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#443]
本提案讨论：设计一套流程，由流程来告诉我们如何优化文档、优化哪些文档中的哪些细节，避免过早优化、避免重写已经能解决问题的文档，提高优化文档的 ROI

### 思路1: 机器测试文档。在 CI/CD 流程中，自动测试 quickstart 文档
1. 可以用工具，自动执行 quickstart 文档中的命令，相当于自动测试 quickstart，保证 quickstart 能快速跑通
比如 https://github.com/bashup/mdsh 

2. 自动扫描死链接
https://github.com/tcort/markdown-link-check

3. 自动检查 markdown语法错误

### 思路2：机器生成文档
比如用模板语言编写 markdown，其中部分内容（比如“引用代码块”）由代码生成
比如 .proto 文件自动生成接口文档

### 思路3: 人类测试，测试驱动优化
We have a test-driven documation improvement strategy:
>If we can't answer a user question by just sending him/her a link, then we need to consider whether the answer should be written into a document.

每次用户提问时，如果不能通过发一个链接解答问题，就是一次 test fail，需要考虑是不是可以把答案写到文档上。
这也是“收益管理”的思想：总归要打字解释，不如花很小的成本把打的字粘贴到文档上，获得较大的额外收益。收益是：
- 让搜索引擎能搜到
- 答疑时发个链接就行
- 文档优化后，可能用户看了文档就不会产生这个问题了

### 如何量化评价一个项目的文档质量
a. 答疑时的“文档覆盖率”。需要人肉统计

b. 自助客服、机器人客服领域，会统计“解决率”、“转人工率”指标作为评价指标。
个人做过相关系统，这种指标有很多问题。因此更倾向于使用a

#### 方法1. 众包测试法
pin 一个issue，例如 https://github.com/sofastack/sofa-registry/issues/211

试下来的效果：并不会有人留言，因为这不是开源的玩法。大家要么群里问，要么发issue

#### 方法2. 组织文档测试
玩法可重可轻，轻的可以开发团队交叉测试，或者邀请已有用户测评；
重一点的可以参考tidb之前的活动，让用户来测：
[左手尝鲜、右手周边？TiDB 4.0 捉“虫"竞赛来袭！](https://pingcap.com/zh/blog/tidb-bug-hunting-guide)

缺点是成本较高、难以长期实施

#### 方法3.  主动记录答疑过程、统计答疑时的文档覆盖率
既然 “众包测试法” 不会有人留言，那就换一种思路，我们主动记录答疑过程、统计答疑时的文档覆盖率
比如，我把微信和钉钉的答疑记录在 https://github.com/mosn/layotto/issues/436
每次答疑对话都可以复制粘贴上去

有了这些答疑记录，我们就能：
- 方便统计答疑时的“文档覆盖率”
- 根据答疑记录去优化文档
凡是不能通过发链接来解决的用户问题，都可以考虑补充到文档上。

#### 选择哪种方法
个人觉得方法3更好。

#### 以什么样的形式将答疑记录补充到文档
有几种策略：

##### A. append 策略:  
在官方文档中新建一个 FAQ 文档，每次答疑记录粘贴进去、加一条。
或者干脆开个 issue，记录所有答疑过程，即 https://github.com/mosn/layotto/issues/436
逻辑是： “只要能被搜索引擎搜到就行；如果他没搜到，那就发他一个链接”。毕竟 google 和 bing 比语雀搜索要好用。
pros:  成本非常低
cons: 并没有优化官方文档，只是补充了 FAQ、答疑时方便解答

##### B. random-access策略，每次有新用户问题就去优化文档
每次新解答了一个问题，如果这个问题没法用发链接解决，就去优化文档。
优化的目标是：“想办法完善文档，让用户不会产生这样的问题；如果以后其他人有同样问题来问，就发他一个链接”

pros: 优化了官方文档
cons: 成本较高

##### C. LSM-tree 策略: 
每次答疑记录都记下来（打一次 log）
在官方文档中新建个 FAQ 文档，每周把本周答疑过程提个PR粘贴进去，让用户通过搜索引擎能搜到（批量 append log）
每两周做一次 merge log , 根据两周内的答疑log 优化文档，优化的目标是：“想办法完善文档，让用户不会产生这样的问题；如果以后其他人有同样问题来问，就发他一个链接”

#### 自动化文档治理
比如运营同学每次把群聊里的答疑过程粘贴到 issue，我们可以写个机器人：
每周把新答疑过程提 PR 合并到 FAQ 文档；
每两周推动项目维护者 根据答疑记录优化文档。

优化：如果觉得 提 PR 、把答疑记录合并到官方文档太麻烦，可以在官方文档中新建一个 FAQ 链接，点击跳到记录 FAQ的issue
但这样做的缺点是：官方网站的搜索功能就搜不到该 FAQ 了

### TODO
个人建议 Layotto 先这么玩，但 Layotto 的用户问题不多；SOFA-RPC 非常适合采用这种流程

**Comment by nobodyiam** [comment]
> If we can't answer a user question by just sending him/her a link, then we need to consider whether the answer should be written into a document.

Can't agree more.

**Comment by seeflood** [comment]
update: 
可以用工具，自动执行 quickstart 文档中的命令，相当于自动测试 quickstart，保证 quickstart 能快速跑通
比如 https://github.com/bashup/mdsh

**Comment by seeflood** [comment]
update:
自动扫描死链接
https://github.com/tcort/markdown-link-check
