### ISSUE TITLE
dubbo demo fails

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#458]
**What happened**:
The quickstart of [Dubbo JSON RPC Example](https://mosn.io/layotto/#/zh/start/rpc/dubbo_json_rpc?id=dubbo-json-rpc-example) fails:

```
Cloning into 'dubbo-go-samples'...
: line 8: cd: attachment/go-server: No such file or directory
```

It's because the directory doesn't exist any more:
![image](https://user-images.githubusercontent.com/26001097/162612843-074cb51b-5413-4b30-ad0c-0acb2165b237.png)

**What you expected to happen**:
No error 

**How to reproduce it (as minimally and precisely as possible)**:
Follow the  [Dubbo JSON RPC Example](https://mosn.io/layotto/#/zh/start/rpc/dubbo_json_rpc?id=dubbo-json-rpc-example) and you will find the error.

**Anything else we need to know?**:

**Comment by rayowang** [comment]
assign

**Comment by seeflood** [comment]
@rayowang Thanks for your help!
