### ISSUE TITLE
Use in-memory component to implement the Actuator API

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#463]
**What would you like to be added**:
Currently our [Actuator quickstart demo](https://mosn.io/layotto/#/zh/start/actuator/start) use the apollo component,which connects to the apollo server by default.
![image](https://user-images.githubusercontent.com/26001097/162747043-1a3e69b1-592c-4b5e-82ee-e57d6bcd82f4.png)

However, due to the GFW, the github workflow can not connect to the apollo server when running the tests:
![image](https://user-images.githubusercontent.com/26001097/162670480-db4818bb-e4fc-4e6f-9302-429cb6981dc5.png)

see https://github.com/mosn/layotto/pull/456 

To solve this issue, we can:
- Use some in-memory component to implement the Actuator API.
We can choose any one of the in-memory components, such as the state component, such as the pubsub component, etc.

- modify the quickstart and use the `configs/config_in_memory.json` instead, so that the demo won't try to connect to the remote server.

**Why is this needed**:
To solve the issue above, and make the quickstart more stable and testable

**Comment by akkw** [comment]
我想做这个，我们怎么沟通

**Comment by seeflood** [comment]
@akkw 啊不好意思，这个功能我已经做好合并进去了，因为还在写文档 所以这个issue 没关……
可以看下其他感兴趣的事情哈，见 #108 和 #470
