### ISSUE TITLE
how to tranlate the "stale bot" into chinese?

### ISSUE THREAD

**Issue by jieeny** [mosn/layotto#468]
hello,l have a question that how to tranlate the "stale bot" into chinese?

**Comment by jieeny** [comment]
Good Morning.
Thanks for your help.
I have another question about What does  the "Lint" mean in the "explanation-for-github-workflow"?

**Comment by seeflood** [comment]
About "what is Lint":
>Linting is the process of running a program that will analyse code for potential errors.
https://stackoverflow.com/questions/8503559/what-is-linting
https://www.perforce.com/blog/qac/what-lint-code-and-why-linting-important

For example, when u submit a PR, the github workflow find out that your code style does not meet the project specification and give you an error, that's linting

About "how to translate it":
I don't know either......maybe use the english name ?

**Comment by jieeny** [comment]
ok,thank you for your help!
