### ISSUE TITLE
make Secret API ready for production

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#472]
**What would you like to be added**:
Layotto already has the feature of Secret API, see https://github.com/mosn/layotto/pull/343
However, there are still many problems to be solved before it can be used in a production environment, including:
  - [x] Demos and docs. see https://github.com/mosn/layotto/issues/460
  - [ ] Let the components of other APIs refer to the secret component in the configuration file. 
For example, currently if users want to use the redis component for the state API, they should write the password of redis in the configuration file, which is insecure.
To solve this problem, we should allow users to "refer to" the secret component in the configuration and have the secret component automatically obtain the password.
See https://docs.dapr.io/operations/components/component-secrets/

  - [ ] Access control. For example, we should retrict which keys can be accessed by app1, see  https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-scopes/ 

**Why is this needed**:
To make Secret API ready for production

---

chinese:

虽然 Layotto 支持了 secret API，见 https://github.com/mosn/layotto/pull/343
但是距离在生产环境用，还需要:
  - [ ] 文档补充. https://github.com/mosn/layotto/issues/460
  - [ ] 让其他API的组件在配置文件中可以引用密文。比如，当前用户想用 state API的redis组件时，必须在配置文件中配置 redis 的密码，这不安全。作为解决方案，可以允许用户在配置里”引用“secret 组件，由 secret 组件自动获取密码。见 https://docs.dapr.io/operations/components/component-secrets/
  - [ ] 密钥的访问控制，比如限制app1能访问的密钥的白名单、黑名单等，见 https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-scopes/ 这个我们也可以配置在Layotto的json配置文件里

**Comment by ZLBer** [comment]
@seeflood  anyone do this ? if not assign me.

**Comment by seeflood** [comment]
@ZLBer No one working on it yet.
Need your help 🚀

**Comment by ZLBer** [comment]
our meta can not  parse such data:

```
"metadata”:{
  "redisPassword":{
    "secretKeyRef":{
    	"name":"redis-secret"
        "key":  "redis-password"
}
}
}
```
so i think we can change the structure of this：
```
"metadata”:{
"secretKeyRef":"redisPassword",
"secretKeyRef-name":"redis-secret",
  "secretKeyRef-key":"redis-password"
}
}

```
our meta: 
![image](https://user-images.githubusercontent.com/20033804/164985506-c9287f3e-3f11-406f-b4d9-35b972952bae.png)

dapr meta:
![image](https://user-images.githubusercontent.com/20033804/164985443-dbc3bf49-b02a-4ac3-ae62-05dfce41178b.png)

**Comment by seeflood** [comment]
@ZLBer that's really a problem :( 
The existing key-value string pair is not expressive.
For example, if we use the structure you proposed:
```
"metadata”:{
  "secretKeyRef":"redisPassword",
  "secretKeyRef-name":"redis-secret",
  "secretKeyRef-key":"redis-password"
}
```
It seems ok. But if we want to add a new secret reference here, e.g. a `redisToken`, it won't work:

```
"metadata”:{
  "secretKeyRef":"redisPassword",
  "secretKeyRef-name":"redis-secret",
  "secretKeyRef-key":"redis-password",  

  "secretKeyRef":"redisToken",
  "secretKeyRef-name":"redis-secret",
  "secretKeyRef-key":"redis-token"
}
```

**Comment by zhenjunMa** [comment]
I prefer `Solution A`, cause our project is still at an early stage, therefore, maintainability is more important than compatibility

**Comment by seeflood** [comment]
agreed.
Then we should make this incompatible changes in v0.5, and release v0.5 as soon as possible, so that we won't affect more users.

**Comment by ZLBer** [comment]
@seeflood @zhenjunMa 我觉得我们可以在meta之外加一个refs字段，初始化的时候把refs里的字段注入到meta里就可以了，我觉得这样的改动是最小的了。不然改动真的挺大的，配置解析、配置文件、每种组件的config都得改。
<img src="https://user-images.githubusercontent.com/20033804/166195041-ff2eb0b3-7143-4326-a61d-81451218aeb4.png" width="50%" ></img>

**Comment by seeflood** [comment]
当前讨论进展见:
https://github.com/mosn/layotto/issues/500#issuecomment-1122964509

```
  "state": {
    "redis": {
      "metadata": {
        "redisHost": "localhost:6380",
        "redisPassword": ""
      },
      "secretRef": [
        {
          "name": "xxx",
          "key": "yyy"
        }
      ]
    }
  },
```
如果用这个结构的话，就可以向下兼容啦，看看合适么
