### ISSUE TITLE
Implement Sequencer API component: mysql

### ISSUE THREAD

**Issue by GimmeCyy** [mosn/layotto#489]
**What would you like to be added**:
Add Sequencer API component: mysql #438

**Comment by seeflood** [comment]
感谢帮助！


参考资料:
[组件开发指南](https://mosn.io/layotto/#/zh/development/developing-component?id=%e7%bb%84%e4%bb%b6%e5%bc%80%e5%8f%91%e6%8c%87%e5%8d%97)
[快速开始：使用Sequencer API生成分布式唯一、自增id](https://mosn.io/layotto/#/zh/start/sequencer/start?id=%e4%bd%bf%e7%94%a8sequencer-api%e7%94%9f%e6%88%90%e5%88%86%e5%b8%83%e5%bc%8f%e5%94%af%e4%b8%80%e3%80%81%e8%87%aa%e5%a2%9eid)
[Sequencer API设计文档](https://mosn.io/layotto/#/zh/design/sequencer/design?id=sequencer-api%e8%ae%be%e8%ae%a1%e6%96%87%e6%a1%a3)
[组件配置说明](https://mosn.io/layotto/#/zh/component_specs/sequencer/common?id=%e5%88%86%e5%b8%83%e5%bc%8f%ef%bc%88%e8%87%aa%e5%a2%9e%ef%bc%89%e5%94%af%e4%b8%80id%e7%bb%84%e4%bb%b6)

**Comment by seeflood** [comment]
action
- [ ] review and merge @seeflood
