### ISSUE TITLE
配置下发通道与配置热加载

### ISSUE THREAD

**Issue by unionhu** [mosn/layotto#500]
希望提供一个通用的配置下发的grpc协议通道，用于layotto与控制面的交互（可以参考[go-control-plane](https://github.com/envoyproxy/go-control-plane)），
可以随意定义用户可以，随意的定义下发配置的策略内容

用途：
1.redis、kafka客户端流量管理控制，可能需要容灾切换、灰度发布策略切换
2.redis连接参数调整、安全弱密码自动切换

**Comment by seeflood** [comment]
Cool. 个人一直期望在layotto runtime 层支持 流量治理规则、支持规则动态下发（像 envoy 那样），这样能帮助所有组件都获得强大的流量治理能力。

不过您的描述比较简单，我有一些疑问，比如：
- 是希望下发 key-value 结构的“配置”，还是类似于 xds 那样、有一定结构的“规则”呢？
- redis 的组件现在有一些failover之类的配置，这些配置项能否满足您的需求，见 https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/
- 启动配置文件里，现在有一些key/value配置项（见下图），layotto 会用这些配置项去初始化组件。如果加入动态规则下发后，您希望layotto 启动后，用哪里的配置做初始化，是启动后立刻读控制面的配置、用控制面的配置覆盖掉配置文件里的配置、然后再初始化么？
![image](https://user-images.githubusercontent.com/26001097/165683881-36913b1c-ca86-4a8c-90ba-938a4d800123.png)

所以，您能否写个设计proposal，比如写下您希望 layotto 对控制面开什么样的 api 出来、api 字段有哪些，因为由别人来设计的话，很可能设计出来的字段满足不了您的需求~

**Comment by unionhu** [comment]
> Cool. 个人一直期望在layotto runtime 层支持 流量治理规则、支持规则动态下发（像 envoy 那样），这样能帮助所有组件都获得强大的流量治理能力。
> 
> 不过您的描述比较简单，我有一些疑问，比如：
> 
> * 是希望下发 key-value 结构的“配置”，还是类似于 xds 那样、有一定结构的“规则”呢？
> * redis 的组件现在有一些failover之类的配置，这些配置项能否满足您的需求，见 https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/
> * 启动配置文件里，现在有一些key/value配置项（见下图），layotto 会用这些配置项去初始化组件。如果加入动态规则下发后，您希望layotto 启动后，用哪里的配置做初始化，是启动后立刻读控制面的配置、用控制面的配置覆盖掉配置文件里的配置、然后再初始化么？
>   ![image](https://user-images.githubusercontent.com/26001097/165683881-36913b1c-ca86-4a8c-90ba-938a4d800123.png)
> 
> 所以，您能否写个设计proposal，写下“您希望这个功能被设计成什么样”，比如写下您希望 layotto 对控制面开什么样的 api 出来、api 字段有哪些。因为由别人来设计的话，很可能设计出来的字段/功能满足不了您的需求~

如果要抽象到xds级别的结构的规则，可能相对困难
比如不同的mq，协议结构都不太一样，需要设计人员对每种mq的配置属性十分熟悉，才能抽象好
所以能否先以key-value形式发布，主要是针对企业自定义的组件api功能的规则

redis这种简单的容灾切换应该能满足，但是可能会考虑的更多


通常来说，layotto本地只会有控制面地址配置，其他配置均可以替换，当然也可以从本地配置获取
优先级为：控制面>本地配置

**Comment by seeflood** [comment]
# 动态配置下发
## 需求
组件能查询、订阅配置中心的 kv 配置（比如 apollo 中的配置）。

## 产品设计
### User story
1. 用户在 apollo 页面改一下 Redis 的容灾切换配置，Redis 组件就能接收到新配置，把流量切到灾备集群

### 编程界面
允许组件依赖 `config_store` 组件，通过 `config_store` 组件查询、订阅配置数据。
组件之间的依赖关系如图:

![image](https://user-images.githubusercontent.com/26001097/167097668-e5e95eff-9427-4071-bf0a-4138cfe67f90.png)

如果组件有这种需求，需要做以下改动：

1. 组件的配置文件里，添加`import`配置项，声明希望引用的 `config_store` 组件名:
```json
  "state": {
    "redis": {
      "metadata": {
        "redisHost": "localhost:6380",
        "redisPassword": ""
      },
      "import": {
        "config_store": {
          "name": "xxx"
        }
      }
    }
  },
```

2. 组件要实现 `configstores.Setter` interface, 以便 runtime 把`config_store` 注入进去
```go
type Setter interface {
	SetConfigStore(store Store)
}
```

## 方案设计
1. 启动时，优先初始化所有 `config_store` 组件、再创建其他组件
2. runtime 创建组件时，如果组件配置了`import`,则检查组件有没有实现 `Setter` 接口，实现了的话就注入对应的 `config_store` 组件
3. 调组件的 Init 接口，初始化组件

生命周期为：

![image](https://user-images.githubusercontent.com/26001097/167097990-1f675c22-3906-4da9-9eb4-1b12615be1d8.png)
## 其他
1. 有没有密钥动态下发的需求？

**Comment by seeflood** [comment]
@unionhu 看下这样能否满足需求~以及是否有密钥动态下发的需求？

**Comment by unionhu** [comment]
> @unionhu 看下这样能否满足需求~以及是否有密钥动态下发的需求？

好巧，今天团队内部讨论到，真好我们也有apollo，也希望config组件能在启动过程中最先加载拉取配置，然后提供给其他组件用
这个特性对我们十分重要，你们优先安排吗？

有密钥动态下发的需求，而且我们可能希望密钥能动态更换，因为存在弱密码场景，安全要求整改

**Comment by ZLBer** [comment]
建议config和secret都放在 import标签里做，大一统

**Comment by seeflood** [comment]
或者用 kind 标识种类， type 标识子类
```
  "state": {
    "redis": {
      "metadata": {
        "redisHost": "localhost:6380",
        "redisPassword": ""
      },
      "ref": [
        {
          "kind": "component",
          "type": "config_store",
          "name": "apollo"
        },
        {
          "kind": "component",
          "type": "custom.super_pubsub",
          "name": "my_super_pubsub"
        },
        {
          "kind": "secret",
          "name": "xxx",
          "key": "yyy"
        }
      ]
    }
  },
```

**Comment by seeflood** [comment]
@unionhu 这个 feature 实现起来应该很简单，你们有开发感兴趣认领么~

**Comment by ZLBer** [comment]
默认secret是只获取一次？ config是获取一次+订阅的吗？

**Comment by seeflood** [comment]
@ZLBer 以这个配置结构为例：
```json
  "state": {
    "redis": {
      "metadata": {
        "redisHost": "localhost:6380",
        "redisPassword": ""
      },
      "componentRef": [
        {
          "type": "config_store",
          "name": "apollo"
        }
      ],
      "secretRef": [
        {
          "name": "xxx",
          "key": "yyy"
        }
      ]
    }
  },
```
secretRef 代表“启动时只获取一次这个secret”
componentRef 代表“需要在启动时注入组件”，组件type 是 "config_store"，name 是"apollo"
而且 redis 组件要实现 configstores.Setter interface, 以便 runtime 把config_store 注入进去
```
type Setter interface {
	SetConfigStore(store Store)
}
```

**Comment by seeflood** [comment]
> > @unionhu 这个 feature 实现起来应该很简单，你们有开发同学感兴趣认领么~
> 
> 感兴趣，只是我们最近忙着上线mosn以及配套设施，估计要下下周，我周末有空的时候看看应该怎么搞

@unionhu 欢迎~ 可以先看下，如果不太明白的话我可以投屏和你说下改哪

**Comment by seeflood** [comment]
@ZLBer 
>redis 组件让我理解了半天... 就相当于 state.redis 持有了componentRef的引用，框架侧只需要启动的时候注入进去？(有spring那味了) 

是的，就是 spring 那味 👃 

> 听起来还是不自动啊，那我只想注入点配置，你给我直接注入到meta里我直接用不行吗？

澄清一下，我们可以把下发的配置分为两类:
- 静态配置：启动时候用，启动完了就不再改动了
- 动态配置：比如 state.redis 组件监听某个配置项 `openFeatureA`（用于开关某个功能），一但有变更，立刻能够获取到，然后打开/关闭相关功能

所以这里“注入一个组件”是为了满足“动态配置”的需求；
而静态配置可以这样:
```
  "state": {
    "redis": {
      "metadata": {
        "redisHost": "localhost:6380",
        "redisPassword": ""
      },
      "configurationRef": [
        {
          "name": "apollo",
          "key": "xxxxx"
        }
      ]
    }
  },
```

**Comment by seeflood** [comment]
>还有组件启动权重？ 是我们手动调整下代码顺序？

是的，调整启动顺序，先启动、初始化 config_store， 再启动别的类型的组件

**Comment by ZLBer** [comment]
@seeflood  动态配置这个，那用户还是需要修改layotto的代码吗 ？

**Comment by seeflood** [comment]
我们把框架开发好（把依赖注入的逻辑开发好），用户不用修改layotto 代码，但是用户要写自己的组件、自己订阅配置变更、做打开开关之类的功能

---
这只是我目前想到的方案， 不代表就一定要这样哈，就更好的方案的话都可以讨论

**Comment by ZLBer** [comment]
忽然又意识到了sdk的好处，直接写回调函数
很cool的功能，没人写可以@我

**Comment by seeflood** [comment]
@ZLBer 感觉你说的是个问题哦，想用这个功能必须写自己的组件，有点不通用？

**Comment by ZLBer** [comment]
干脆就静态配置我们就加载一次，动态配置搞成订阅塞到meta里，但这样缺点就是没法加用户自己的逻辑。

**Comment by seeflood** [comment]
>动态配置搞成订阅塞到meta里

这个是啥意思，是说组件配置的metadata 里，配想要订阅的 key，是这样么:
```
  "state": {
    "redis": {
      "metadata": {
        "redisHost": "localhost:6380",
        "redisPassword": ""
      },
      "subscriptionRef": [
        {
          "name": "apollo",
          "key": ["switchA","switchB"]
        }
      ]
    }
  },

```

**Comment by ZLBer** [comment]
我意思是，就只是订阅，然后把监听到的配置更新再写回meta，比较粗犷

**Comment by unionhu** [comment]
> * 在

我反而倾向思路B，在spring boot的设计思想是类似B方案，
这样有个好处，redis等组件只关注自建的配置数据结构模型，类似微服务设计的反腐层，不会跟Apollo强绑定，后续layotto需要对接其他配置中心会变得非常方便

能否评估方案B的工作量？若耗时比较久，可以先走A方案，后续支持B方案

**Comment by unionhu** [comment]
> 5.13 社区会议讨论action:
> 
> * 需要“默认订阅”功能（某个租户/组 下面会默认订阅一批 kv）， @unionhu 可以详细描述下场景、建议的设计;  这个功能应该有现成的，apollo 组件可以配 namespace 等参数，按参数取默认订阅的配置
> * 先按当前方案做个 alpha版，后续 @unionhu 可以基于生产需求来改 alpha 版

目前看应该是没有问题的，我们生产的时间点是希望尽量六月底，先这么走吧，我也刚刚开始介入这块的事项

**Comment by seeflood** [comment]
# 配置下发、组件热重载方案 v0.3
## 1. 解决的问题
- 现在生产用户有一套定制的启动时初始化配置的方案：有一些配置配在 app 里，app 启动后、调 sidecar，让 sidecar 基于这些配置做初始化。方案不够通用，想做的更通用些

![image](https://user-images.githubusercontent.com/26001097/168947177-6a26397e-4648-47f0-a8df-e898285cd8f9.png)
  
- 现在 json 文件要打包进镜像。如果跨云部署，改一个配置（比如改 AWS 某个配置项）就要重新打镜像，不合理。
  - 一种思路是让配置文件和镜像解耦，通过磁盘挂载进容器。比如 Dapr 的配置项放进 Configuration CRD, CRD 变更后，需要运维人员通过 k8s 滚动重启集群。
  - 另一种思路是像 envoy 一样，把配置分两类：bootstrap 配置（静态配置）、动态配置，前者放不放进镜像都行，后者支持配置动态下发、根据配置做热重载。  
- [依赖注入 config_store 方案](https://github.com/mosn/layotto/issues/500#issuecomment-1119390497) 有一些缺点:
  - 用户如果想用“动态配置下发”功能，没法当伸手党，没有社区现成的组件用，得开发自己的组件。
    最好是 runtime 层做一些通用功能，“赋能”所有组件，社区维护现成的组件、支持动态配置下发，方便用户当伸手党，开箱即用。

## 2. 产品设计
### User story
1. 用户在 apollo 页面改一下 Redis 的容灾切换配置，Redis 组件就能接收到新配置，把流量切到灾备集群
2. 已有生产用户可以把初始化流程迁移到新的模型，向下兼容。

### 编程界面
比如，现在 state.redis 的启动配置有下面这些（截图取自 [dapr 文档](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/) )
![image](https://user-images.githubusercontent.com/26001097/168946975-9804d792-8851-463f-80ee-26231468f0aa.png)

现状是：redis 组件启动时，用这些配置kv做初始化；所有配置都是静态配置、只在启动时取一次，不监听后续配置变更。

但是我们可以改成：
- 这些 kv 可以动态下发
- layotto 监听这些 kv 的变更，一但有变化，**用最新的配置重新初始化组件**
- 如果组件觉得重新初始化太小题大做了，可以实现动态更新接口

优缺点分析：
- pros
    - runtime 层可以做一些通用功能，“赋能”所有组件；方便用户当伸手党，社区维护现成的组件、支持动态配置下发，用户开箱即用
- cons
    - 实现起来复杂。比如重新初始化期间，怎么保证流量无损？ 
    - 我不清楚这能不能满足用户生产需求，担心过早设计、过度设计
## 3. High-level design
![image](https://user-images.githubusercontent.com/26001097/168949648-3f440a84-45d3-45c1-89ef-79cb25d49713.png)

### UpdateConfiguration API
Sidecar 启动还是用 json 文件，启动完成、readiness check 通过后，对外暴露一个新的 API，用于做配置热变更:

```protobuf
rpc UpdateConfiguration( RuntimeConfig) returns (UpdateResponse)
```

### Agent 负责和控制面交互
也就是说，Sidecar 只是开个接口、等别人推配置。而具体和控制面交互、订阅配置变更的事情可以封装 agent 来做，比如图上的 agent 2，负责订阅 apollo 的配置变更，有变更了就调 Sidecar 的接口，让 Sidecar 热更新。

对于已有的生产用户，可以像图上封装 agent 1, 监听 app 喂的配置、dump 配置、重启时加载配置，然后把配置推给 Sidecar。

再比如可以写个 File agent 问题，监听文件变化，有变化就读取新配置、通知 Sidecar 热重载。

agent 不一定要单独进程，在 main 里启动一个独立协程也行。

### 组件热重载
Sidecar 被调 UpdateConfiguration API 后，会:
1. 判断组件有没有实现"增量更新"接口:
```go
updateConfig( configmap map[string]string) (success bool, err error)
```
2. 如果组件有实现该接口，runtime 尝试让其增量更新 
3. 如果增量更新失败，或者没实现该接口，则 runtime 根据全量配置重新初始化组件
4. 新组件重新初始化完成后(通过 readiness check)，接管原组件的流量

## 4. 详细设计
// TODO
- UpdateConfiguration API 接受全量配置还是增量配置
- 重新初始化过程中，怎么保证流量无损
- 怎么处理 readiness 状态
- 配置优先级：有一些配置是某个 app 定制的配置，有一些配置是所有 app 公用的通用配置，两者优先级是啥

**Comment by seeflood** [comment]
## 生产用户情况
7月底 8月初用；

建议调研 spring boot ；@unionhu 提供下源码地址  

可能的生产场景：apollo 下发配置

可能的业务场景：
- 动态改 redis 的密码配置（动态配置下发）
- 分布式id
- 分布式锁
- configuration api 目前没找到业务场景
- 自定义 api （认证鉴权）

**Comment by unionhu** [comment]
> ## 生产用户情况
> 7月底 8月初用；
> 
> 建议调研 spring boot ；@unionhu 提供下源码地址
> 
> 可能的生产场景：apollo 下发配置
> 
> 可能的业务场景：
> 
> * 动态改 redis 的密码配置（动态配置下发）
> * 分布式自增 id
> * 分布式锁
> * configuration api 目前没找到业务场景
> * 自定义 api （认证鉴权）
> * 后续再考虑 redis 和 pulsar

spring cloud consul源码地址：https://github.com/spring-cloud/spring-cloud-consul
查看[spring-cloud-consul-config](https://github.com/spring-cloud/spring-cloud-consul/tree/main/spring-cloud-consul-config)

**Comment by seeflood** [comment]
更新下进展:
- 关于componentRef 的方案
@ZLBer 最近做了个 密钥注入，想要通过 componentRef 注入的话很快就能支持；

- 关于"把组件做成CRD、CR 变更后透明热加载组件"方案:  
现在的卡点是：不知道用什么控制面去下发 CR 变更。我看了下 xDS 是没法下发这些自定义配置的?
感觉这个问题很通用: envoy 用户自己写的 filter 想动态改规则，怎么下发规则？现在 xDS 各种 filter 的规则是强类型的
(听说 ASM 是改了 istio)
这个问题是 @rayowang 提的，可以一块调研下

**Comment by rayowang** [comment]
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: flowcontrol
  namespace: brpc-rank 
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND 
      patch:
        operation: INSERT_BEFORE
        value:
          name: testfilter
          typed_config:
            "@type": type.googleapis.com/google.protobuf.StringValue
            value: |
              {
              	"app_name": "ratelimiter",
              	"log_path": "stdout",
              	"global_switch": true,
              	"monitor": true,
              	"limit_key_type": "PATH",
              	"action": {
              		"status": 2004,
              		"body": ""
              	},
              	"rules": [{
              		"resource": "searchEngine.rankService",
              		"limitApp": "searchEngine",
              		"threshold": 1000,
              		"grade": 1,
              		"strategy": 0,
              		"StatIntervalInMs": 500
              	}],
              	"system_rules": [{
              		"metricType": 4,
              		"strategy": 0,
              		"triggerCount": 0.85
              	}]
              }

**Comment by seeflood** [comment]
action:
-  @unionhu  能否接受通过 xds 下发组件配置（而不是通过apollo下发配置），配置示例就是上面 @rayowang 帖的

**Comment by unionhu** [comment]
> action:
> 
> * @unionhu  能否接受通过 xds 下发组件配置（而不是通过apollo下发配置），配置示例就是上面 @rayowang 帖的

可以的，这样我们也不用新增一个组件了，因为我们这边暂时config mesh的需求场景

**Comment by seeflood** [comment]
会议结论

1. 可能的业务场景:
- 发短信
- 长链转短链
- mq

2. 不需要配置中心下发配置了，希望xds下发（所以不需要 component 注入这种方案
3. 时间节奏:
争取8月中旬定下来配置下发的方案

**Comment by unionhu** [comment]
> 如果type_config 的type是StringValue或ANY是可以下发一段Json或一个Object，如下例：
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: flowcontrol
>   namespace: brpc-rank 
> spec:
>   configPatches:
>     - applyTo: NETWORK_FILTER
>       match:
>         context: SIDECAR_INBOUND 
>       patch:
>         operation: INSERT_BEFORE
>         value:
>           name: testfilter
>           typed_config:
>             "@type": type.googleapis.com/google.protobuf.StringValue
>             value: |
>               {
>               	"app_name": "ratelimiter",
>               	"log_path": "stdout",
>               	"global_switch": true,
>               	"monitor": true,
>               	"limit_key_type": "PATH",
>               	"action": {
>               		"status": 2004,
>               		"body": ""
>               	},
>               	"rules": [{
>               		"resource": "searchEngine.rankService",
>               		"limitApp": "searchEngine",
>               		"threshold": 1000,
>               		"grade": 1,
>               		"strategy": 0,
>               		"StatIntervalInMs": 500
>               	}],
>               	"system_rules": [{
>               		"metricType": 4,
>               		"strategy": 0,
>               		"triggerCount": 0.85
>               	}]
>               }
> ```

看了一下mosn加载xDS的逻辑，也是在LDS请求后，拿到了listener进行处理，目前看只支持http的listener，能不能新增一个特别的listener，接受multi runtime的所有配置，专门传递给layotto使用

```java
func HandleListenerResponse(resp *envoy_service_discovery_v3.DiscoveryResponse) []*envoy_config_listener_v3.Listener {
	listeners := make([]*envoy_config_listener_v3.Listener, 0, len(resp.Resources))
	for _, res := range resp.Resources {
		listener := &envoy_config_listener_v3.Listener{}
		if err := ptypes.UnmarshalAny(res, listener); err != nil {
			log.DefaultLogger.Errorf("ADSClient unmarshal listener fail: %v", err)
			continue
		}
		listeners = append(listeners, listener)
	}
	return listeners
}
```

**Comment by seeflood** [comment]
听起来可行？ @ZLBer @wenxuwan @rayowang @zhenjunMa @nejisama 帮忙一起看看哈

**Comment by nejisama** [comment]
没看懂 不知道说的什么

**Comment by seeflood** [comment]
@nejisama 我理解核心思想是：
1. 通过xDS 里面的 envoyFilter 下发一个字符串（这个字符串就是layotto配置），示例是上面的 https://github.com/mosn/layotto/issues/500#issuecomment-1186174824
2. 这个字符串下发到 mosn 后，怎么传递给layotto ？现在卡在这个问题上了

**Comment by nejisama** [comment]
xds 下发字符串的通道是什么？还是新的一种新的，和listener（lds）、cluster（cds）并列的资源类型？还是用某个资源的字段做特殊的解析？

**Comment by nejisama** [comment]
上面例子里 就是一个filter配置，那就是转换成一个标准的filter实现，比如是一个flowcontrol 的filter 那就只能转换成一个 对应实现的flowcontrol 的filter 。 如果是这样 那对应实现相关的filter就可以了

**Comment by seeflood** [comment]
@unionhu 最新进展，不用改控制面的方案:
1. 可以通过 udpa 里的 typedstruct 类型下发配置; mosn 处理下发配置的代码在 `convertUdpaTypedStructConfig` 函数里，可以搜下
2. mosn 提供了扩展机制，去解析自己下发的配置。参考 PR:  https://github.com/mosn/mosn/pull/2081


各位帮忙一起看下哈

**Comment by unionhu** [comment]
> @unionhu 最新进展，不用改控制面的方案:
> 
> 1. 可以通过 udpa 里的 typedstruct 类型下发配置; mosn 处理下发配置的代码在 `convertUdpaTypedStructConfig` 函数里，可以搜下
>    istio 文档里也有个示例，见 https://istio.io/latest/docs/reference/config/networking/envoy-filter/
>    ![image](https://user-images.githubusercontent.com/26001097/181473976-af123043-3167-4d32-b51c-408f91a5a796.png)
> 2. mosn 提供了扩展机制，去解析自己下发的配置。参考 PR:  [support xds for stream filter mosn#2081](https://github.com/mosn/mosn/pull/2081)
>    用这种方式，下发的配置数据可以自己用 proto 描述
> 
> 各位帮忙一起看下哈

但是这个并没有告知怎么传递给layotto的grpc filter

**Comment by seeflood** [comment]
@unionhu 我们有两个问题要解决：
1. 怎么通过 XDS 把配置项传下来，并且不用改控制面代码
上面的PR 演示了如何解决这个问题

2. Layotto 如果做配置热加载
这个我理解得让 Layotto 单独开一个接口

**Comment by unionhu** [comment]
> 

是的，第一个问题好处理
第二个问题mosn接收到配之后能不能触发一个event，layotto订阅了event 拿到配置进行热加载

**Comment by seeflood** [comment]
关于 "2. Layotto 如果做配置热加载"，有俩方案:

A. 通过 XDS 做配置变更后，mosn 下次接受新连接、创建新的 networkfliter 时，会自动用新配置创建
![image](https://user-images.githubusercontent.com/26001097/181702572-649f1907-ab52-4d40-a444-a5eaf22eefab.png)
好处：啥代码都不用改，mosn 自动帮忙搞定
缺点:  旧连接不受影响


B. 下发的 XDS 配置里，把 Layotto 相关的配置存到某个全局 map去，然后 Layotto 做个配置监听功能，监听这个全局 map，有变更则热加载

好处：轻量；旧连接也能更新

**Comment by unionhu** [comment]
> 关于 "2. Layotto 如果做配置热加载"，有俩方案:
> 
> 方案 A. 通过 XDS 做配置变更后，mosn 下次接受新连接、创建新的 networkfliter 时，会自动用新配置创建 ![image](https://user-images.githubusercontent.com/26001097/181702572-649f1907-ab52-4d40-a444-a5eaf22eefab.png) 好处：啥代码都不用改，mosn 自动帮忙搞定 缺点: 旧连接不受影响
> 
> @unionhu 如果先用这种方案呢？
> 
> 方案 B. 下发的 XDS 配置里，把 Layotto 相关的配置存到某个全局 map去，然后 Layotto 做个配置监听功能，监听这个全局 map，有变更则热加载
> 
> 好处：轻量；旧连接也能更新

偏向方案B，能否你先设计，如果代码量不多，我看看能不能搞定

**Comment by seeflood** [comment]
@unionhu 恩，按方案 B 去推演（把 Layotto 相关的配置存到某个全局 map去，然后 Layotto 做个配置监听功能，监听这个全局 map，有变更则热加载），其实就说回到了咱们一开始讨论的两种方案:

B1. 组件注入，比如支持把 config store 组件注入进 pubsub 组件
然后你就可以实现一个 XDS config store 组件，注入进 pubsub 组件

B2. Layotto 开一个抽象的 update 接口，见上面的讨论  https://github.com/mosn/layotto/issues/500#issuecomment-1129540626
![image](https://user-images.githubusercontent.com/26001097/181712125-582cba52-2871-42db-9278-5b3fc608b8ad.png)


目前看来，两种方案其实都要做（现在就有用户想用 B1 方案

**Comment by seeflood** [comment]
@ZLBer Hi, 要不继续搞 `component-ref` 这种组件注入的方案？因为最近聊下来发现，其实这两种方案都需要……

**Comment by ZLBer** [comment]
@seeflood  可以的，我试图理解下

**Comment by nejisama** [comment]
LDS更新旧连接的问题，由于layotto是grpc 应该可以考虑用goaway的方式通知旧连接断开，重新建新连接就可以了

**Comment by seeflood** [comment]
> LDS更新旧连接的问题，由于layotto是grpc 应该可以考虑用goaway的方式通知旧连接断开，重新建新连接就可以了

恩感觉这也是个思路。上次看mosn grpcFilter 的代码，发现其实注册进去的 handler 只会初始化、启动一次（如下图），所以按这个思路要新写个 Layotto 自己的 grpcFilter
![image](https://user-images.githubusercontent.com/26001097/183244833-839c67cd-6aad-4391-95da-849d423c2ede.png)

如果发 goaway、让app 重连，会影响业务么？

**Comment by unionhu** [comment]
> `component-ref`

配置组件注入的方案预计几时能搞定？

**Comment by seeflood** [comment]
> > `component-ref`
> 
> 配置组件注入的方案预计几时能搞定？

cc @ZLBer  🐶

**Comment by seeflood** [comment]
@unionhu 我在改启动生命周期的时候也遇到了配置下发的问题，见 https://github.com/mosn/layotto/issues/744#issuecomment-1207861342
我这两周搞下 "Layotto 开一个抽象的 update 接口" 这个方案 https://github.com/mosn/layotto/issues/500#issuecomment-1129540626
component-ref 方案看立斌时间

**Comment by ZLBer** [comment]
component-ref预计该周末提交pr

**Comment by seeflood** [comment]
action:
- [ ] 催下mosn 发版，方便发 layotto v0.5 @seeflood
