### ISSUE TITLE
pub/sub configure no metadata will be panic

### ISSUE THREAD

**Issue by wenxuwan** [mosn/layotto#501]
**What happened**:

这个地方如果配置文件里面没有metadata往里面写的时候就会panic了

![image](https://user-images.githubusercontent.com/11661906/165747488-66bb74bd-eaa4-401c-8c3c-0d5a108ed03e.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by seeflood** [comment]
This is one of [the bugs we found when testing v0.4-rc](https://github.com/mosn/layotto/milestone/2) .
After fixing all the bugs, we can move on to release v0.4

**Comment by seeflood** [comment]
This issue will be assigned to @akkw

**Comment by akkw** [comment]
我来做这个吧
