### ISSUE TITLE
aws file will panic 

### ISSUE THREAD

**Issue by wenxuwan** [mosn/layotto#503]
**What happened**:

aws oss file implement will panic 

![image](https://user-images.githubusercontent.com/11661906/165748034-03de0bf0-4b56-4745-9558-6dfb008db01d.png)

here can't use nil for option args 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by seeflood** [comment]
@akkw OK. Thanks for your help !

**Comment by seeflood** [comment]
This is one of [the bugs we found when testing v0.4-rc](https://github.com/mosn/layotto/milestone/2) .
After fixing all the bugs, we can move on to release v0.4
