### ISSUE TITLE
title validation workflow can't add a label

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#519]
**What happened**:
 The title validation workflow will get an error when adding labels to a pull request. 
https://github.com/mosn/layotto/runs/6244219201?check_suite_focus=true
![image](https://user-images.githubusercontent.com/26001097/166131194-4b135266-fa22-4a36-ac11-e70c6f3c0eca.png)
https://github.com/mosn/layotto/pull/515#issuecomment-1114119752

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by Xunzhuo** [comment]
In my view l, as I proposed before, the current PR title validator is not ideal to check Commit Style. To check the semantic style, we have a better choice:)

**Comment by seeflood** [comment]
@Xunzhuo Do you mean check every commit in a pull request?
I know projects like dapr will check commit style, for example, make sure there's sign-off information in every commit.
We discussed it before. The reason we don't check commit style is that it makes things harder for open-source beginners. As a new community, we want to be more friendly to beginners.
Maybe we can add this check after our community grows bigger :)

**Comment by seeflood** [comment]
As for this issue, I find the authorization weird. For example, I have to "approve" the CI to run in #517  and even #515 . Don't know whether it's github's bug or our CI's issue.
![image](https://user-images.githubusercontent.com/26001097/166144317-e0824581-12b1-4ced-8e9f-6dbaace08ce7.png)

**Comment by Xunzhuo** [comment]
> @Xunzhuo Do you mean check every commit in a pull request?
> 
> I know projects like dapr will check commit style, for example, make sure there's sign-off information in every commit.
> 
> We discussed it before. The reason we don't check commit style is that it makes things harder for open-source beginners. As a new community, we want to be more friendly to beginners.
> 
> Maybe we can add this check after our community grows bigger :)

no just PR title check:)

**Comment by Xunzhuo** [comment]
> As for this issue, I find the authorization weird. For example, I have to "approve" the CI to run in #517  and even #515 . Don't know whether it's github's bug or our CI's issue.
> 
> ![image](https://user-images.githubusercontent.com/26001097/166144317-e0824581-12b1-4ced-8e9f-6dbaace08ce7.png)
> 
> 
> 
> 
> 
> Let me read the github doc and try to find why 🤔 

Maybe not a bug, since we have new workflows to launch, maintainer needs to approve once, not every time:)

**Comment by seeflood** [comment]
> > @Xunzhuo Do you mean check every commit in a pull request?
> > I know projects like dapr will check commit style, for example, make sure there's sign-off information in every commit.
> > We discussed it before. The reason we don't check commit style is that it makes things harder for open-source beginners. As a new community, we want to be more friendly to beginners.
> > Maybe we can add this check after our community grows bigger :)
> 
> no just PR title check:)

Oh, I'm ok with replacing current checker with other one. Actually I'm not good at this area and can't tell the difference between current one and the one you proposed . It's up to you , we follow your advice :)

**Comment by Xunzhuo** [comment]
> Oh, I'm ok with replacing current title checker with other one. Actually I'm not good at this area and can't tell the difference between current one and the one you proposed . It's up to you , we follow your advice :)

I will start an issue to explain why, after fixing the missing version issue.

**Comment by Xunzhuo** [comment]
> As for this issue, I find the authorization weird. For example, I have to "approve" the CI to run in #517  and even #515 . Don't know whether it's github's bug or our CI's issue.
> 
> ![image](https://user-images.githubusercontent.com/26001097/166144317-e0824581-12b1-4ced-8e9f-6dbaace08ce7.png)
> 
> 
> 
> 
> 
> Let me read the github doc and try to find why 🤔 

https://github.com/mosn/layotto/pull/522

Like this PR, the authoration issue did not appear again, all jobs work fine.
