### ISSUE TITLE
FaaS quickstart fails

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#520]
**What happened**:
[The FaaS quickstart demo ](https://mosn.io/layotto/#/zh/start/faas/start) uses a `make` command to build layotto, which is deprecated by #483 and leads to a demo failure.
![image](https://user-images.githubusercontent.com/26001097/166143225-2ead04c3-5421-4a0c-a5a9-b63a425fa630.png)

We should replace this command.

**What you expected to happen**:
Run the demo successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Play the FaaS quickstart demo and you will got an error.

**Anything else we need to know?**:

**Comment by rayowang** [comment]
assign

**Comment by seeflood** [comment]
@rayowang assigned to u. Thanks!

**Comment by Xunzhuo** [comment]
Subtask of https://github.com/mosn/layotto/issues/533
