### ISSUE TITLE
Unit tests fail in `component` package; 修复ut报错

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#528]
**What happened**:
Run unit tests under `component` package:
![image](https://user-images.githubusercontent.com/26001097/166400288-c6a04e76-29c0-4b07-88e4-9a6d26082738.png)

Then you will get some errors:

![image](https://user-images.githubusercontent.com/26001097/166400096-a637a4b5-b172-4439-b3bf-37d7e4b452a3.png)

The test cases have dependency on remote environment (and even need some token to run). 
We should fix them by mocking all the remote environment.

The failed tests include:
- [ ] qiniu oss
~~- [ ] aws s3~~
- maybe others?

**What you expected to happen**:
Run unit tests locally with success

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by Xunzhuo** [comment]
Subtask of https://github.com/mosn/layotto/issues/529

**Comment by leemos-xx** [comment]
这个问题可以让我跟进下吗？

**Comment by seeflood** [comment]
@leemos-xx Ok. Thanks!

**Comment by leemos-xx** [comment]
你好，这个问题在 #529 中似乎被标记为fixed，目前我在`component`目录运行单测时，并没有失败的提示

**Comment by wangxingyu000** [comment]
> [<img alt="@seeflood" width="20" height="20" src="https://avatars.githubusercontent.com/u/26001097?s=60&amp;u=1517aec8152ced91e54a4bc543f1a4d7b75628f3&amp;v=4">](/seeflood) [seeflood](/seeflood) reopened this [5天前](#event-6790975569)



> 你好，这个问题在 #529 中似乎被标记为fixed，目前我在`component`目录运行单测时，并没有失败的提示

hello~ 领取任务后欢迎添加 SOFAGirl 微信:SOFAGirl180419，备注“飞船计划”，方便我们之后跟进任务以及发布奖品

**Comment by seeflood** [comment]
@leemos-xx 我现在本地不报错，但是看了下代码、以及上面的报错信息，猜测是：
ut会给 example.com 发http请求，如果在杭州运行，这个请求会被杭州电信拦截、跳转到 http://safe.zj.189.cn/ 
![image](https://user-images.githubusercontent.com/26001097/174257966-29c8e851-ea7b-426d-9627-497c68afbd3a.png)
我查了下这个域名，确实是电信拦截
https://www.v2ex.com/t/807511


anyway, 不管这个拦截的事情，ut其实不该依赖外部环境，或者说，这个ut 最好不要给 example.com发请求
因此可以修改下ut, 有两种改法:

A. mock掉发请求的部分，不发出真实请求
B. 不好mock的话，干脆让ut别测试发请求了
