### ISSUE TITLE
ci: stabilize new pipelines

### ISSUE THREAD

**Issue by Xunzhuo** [mosn/layotto#532]
**What would you like to be added**:

After bringing new pipelines, we have several tasks need to do, which makes our new pipelines stable.
- [x] **BUG**: fix amd 64 suffix when publishing
    - [x] https://github.com/mosn/layotto/issues/534
        - [x] https://github.com/mosn/layotto/pull/516
- [x] **BUG**: update version info:
    - [x] https://github.com/mosn/layotto/issues/521
        - [x] https://github.com/mosn/layotto/pull/522
        - [x] https://github.com/mosn/layotto/pull/517
- [x] **BUG**: fix wrong module name
    - [x] https://github.com/mosn/layotto/issues/535
        - [x] https://github.com/mosn/layotto/pull/527
- [x] **TEST**: Reopen Unit Tests After fixing:
    - [x] https://github.com/mosn/layotto/issues/529
        - [x] https://github.com/mosn/layotto/pull/546
- [x] **TEST**: Reopen Lint Tests After fixing:
    - [x] https://github.com/mosn/layotto/issues/531
        - [x] https://github.com/mosn/layotto/pull/536
- [x] **DOC**: update sidebar links to new docs
    - [x] https://github.com/mosn/layotto/pull/518
- [x] **DOC**:  update make file commands in docs
    - [x] https://github.com/mosn/layotto/issues/533
- [x] **OPT**: replace old validator with a stable one
    - [x] https://github.com/mosn/layotto/issues/485
        - [x] https://github.com/mosn/layotto/pull/526
- [x] **CHECK**: make sure no flags are missing ⚠️
    - [x] https://github.com/mosn/layotto/pull/522#issuecomment-1115849739

**Comment by seeflood** [comment]
Phase 2, we can make them more powerful after stabilizing new pipelines:
- [ ] Test all the quickstart docs 
  - [ ] #456 
- [ ] more integration test? 
  - [ ] #461
- [ ] Portability test. Use same demo to test different components. 
  - [ ] delete redundent demos. #455 
  - [ ] add portability test in our CI

**Comment by seeflood** [comment]
I'm going to close this issue.
We can track the subtasks using roadmap https://github.com/mosn/layotto/projects/12
