### ISSUE TITLE
🤔 UT of `mosn.io/layotto/components/rpc/invoker/mosn/channel` failed

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#550]
**What happened**: 
The UT of `mosn.io/layotto/components/rpc/invoker/mosn/channel` sometimes  fail. See https://github.com/mosn/layotto/runs/6341559789?check_suite_focus=true
I don't know why 🤔

**What you expected to happen**:
Run ut successfully

**How to reproduce it (as minimally and precisely as possible)**:
Run test cases under   `mosn.io/layotto/components/rpc/invoker/mosn/channel` 
**Anything else we need to know?**:

**Comment by akkw** [comment]
我也遇到这个问题了，有些单测基于的配置文件不一样，目前我发现这一个问题

**Comment by seeflood** [comment]
@akkw Did you find the reason?  🤔 
Do you wanna help fix this issue

**Comment by seeflood** [comment]
@NTH19 ok. Thanks !

**Comment by NTH19** [comment]
> @NTH19 hi, are u still working on it?

Sorry.I have the other things to do these days.

**Comment by seeflood** [comment]
@NTH19 That's fine. Shall we reassign it to others?

**Comment by NTH19** [comment]
> @NTH19 That's fine. Shall we reassign it to others?

Yes

**Comment by h3n4l** [comment]
We need to update the link refer action page, the origin page seems overdue.
<img width="2967" alt="CleanShot 2022-09-07 at 22 40 36@2x" src="https://user-images.githubusercontent.com/87714218/188906662-1f3e6b20-71a0-48bd-8fa6-113416aa1be4.png">

**Comment by seeflood** [comment]
@h3n4l Thanks for reminding me.
I checked other PRs but sadly found that we can't reproduce this issue 😢 
Let me close this issue. We can reopen it once the error occurs again
