### ISSUE TITLE
用 postgresql 实现分布式自增id 组件

### ISSUE THREAD

**Issue by azhsmesos** [mosn/layotto#554]
### Your question

我希望可以用postgresql实现一个分布式自增id组件

### Environment

- Layotto Version

### Logs

- Paste the logs you see.

**Comment by seeflood** [comment]
Cool ! Assigned to u

**Comment by azhsmesos** [comment]
> Cool ! Assigned to u

现在我可以fork 下来着手开发了吧～

**Comment by azhsmesos** [comment]
邮件已收到！thank you

**Comment by seeflood** [comment]
> 现在我可以fork 下来着手开发了吧～

是的~ 
fork ，开发，然后提交 pull request
