### ISSUE TITLE
quickstart tests error

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#558]
**What happened**:
Error occus when running the quickstart tests in #557 . 
But it didn't interrupt execution and finally report an success. See https://github.com/mosn/layotto/runs/6384572067?check_suite_focus=true
![image](https://user-images.githubusercontent.com/26001097/167829201-0bc7dfb9-5950-4448-be27-46590181e42f.png)

**What you expected to happen**:
1. The quickstart tests run successfully
2. If it fails , it should interrupt the execution and report an error

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by akkw** [comment]
这个我来做吧

**Comment by seeflood** [comment]
@akkw Sorry I already submitted PR for it #561  😢

**Comment by seeflood** [comment]
I found there is still error in https://github.com/mosn/layotto/runs/6491118102?check_suite_focus=true
and it didn't interrupt the execution 😢 
![image](https://user-images.githubusercontent.com/26001097/169201247-0b09bc32-a17f-476a-9e5d-fbdc9661141e.png)
