### ISSUE TITLE
ci: automatically upload binary files when releasing new version

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#563]
**What would you like to be added**:
Automatically upload binary files when releasing new version.
I find some tools but haven't look into them in details
https://github.com/marketplace/actions/upload-files-to-a-github-release
https://github.com/svenstaro/upload-release-action
https://github.com/prisma/prisma/issues/1841
https://web3.coach/golang-github-actions-release-binaries-tutorial

**Why is this needed**:
Currently we have to do it manually, and the network under GFW is so slow....

**Comment by seeflood** [comment]
sub task of #532

**Comment by SignorMercurio** [comment]
I would like to help with this. Could you please assign this to me?

**Comment by seeflood** [comment]
@SignorMercurio Thanks! Assigned to u

**Comment by Xunzhuo** [comment]
Great! @SignorMercurio
