### ISSUE TITLE
执行make all 格式化校验代码时报错

### ISSUE THREAD

**Issue by azhsmesos** [mosn/layotto#569]
![Uploading image.png…]()

已经配置了goproxy 代理，还是会报错

log：
zhaozhenhang@zhaozhenhangdeMacBook-Pro layotto % make all
===========> Installing missing goimports
package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports": https fetch: Get "https://golang.org/x/tools/cmd/goimports?go-get=1": dial tcp 172.217.160.113:443: i/o timeout
make: *** [go.format.verify] Error 1

**Comment by seeflood** [comment]
We can modify our `make` script to download goimports from github instead of golang.org

@azhsmesos Do you wanna help fix this issue?

**Comment by azhsmesos** [comment]
> We can modify our `make` script to download goimports from github instead of golang.org
> 
> @azhsmesos Do you wanna help fix this issue?

我目前有个pr还没完成：feat: implement sequencer API with postgresql #567 我先把这个解决哈~ 在考虑其他issue

**Comment by rayowang** [comment]
assign
