### ISSUE TITLE
参考proto文档生成go代码异常

### ISSUE THREAD

**Issue by unionhu** [mosn/layotto#587]
spec/proto/runtime/v1/README.md，protoc提示为3.11.2

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/6756158/169435449-16ad8abb-d185-40c5-b43f-51ea83b34081.png">

实际源码为v3.19.4版本

<img width="421" alt="image" src="https://user-images.githubusercontent.com/6756158/169435613-8fbf7bb0-d63a-43df-917f-21f2390a7bf0.png">

希望提供正确的对应的proc版本与protoc-gen-go版本，方便的话，安装命令贴一下

**Comment by seeflood** [comment]
感谢反馈，可以用这个命令试下：
```shell
protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative *.proto
```

后面可以做成一个 make 命令，再进一步可以用 docker 跑protoc生成 pb.go

**Comment by seeflood** [comment]
我提了个 pr ，用 docker 编译生成代码、文档，保证大家版本一致
https://github.com/mosn/layotto/pull/637
