### ISSUE TITLE
feature: layotto integration Zipkin

### ISSUE THREAD

**Issue by LXPWing** [mosn/layotto#593]
**What would you like to be added**:

layotto add ZipKin

**Comment by seeflood** [comment]
Cool!

**Comment by LXPWing** [comment]
@seeflood 
en: When the main function registers the zipkin, it calls mosn's RegisterTracerBuilder method, but the "driver" slice does not buffer the zipkin's key, so it skips the initialization.

ch: 当main函数注册zipkin时，会调用mosn的RegisterTracerBuilder方法，但是“driver”切片没有缓冲zipkin的key，所以跳过初始化流程。

![image](https://user-images.githubusercontent.com/65880844/173240267-e2a39229-11fd-47b6-8827-eb33b9509822.png)

![image](https://user-images.githubusercontent.com/65880844/173240272-96ed2473-2bb4-47e2-aa83-2b138c047cf5.png)

**Comment by seeflood** [comment]
> the "driver" slice does not buffer the zipkin's key
@LXPWing It's because we should write a driver and invoke the `RegisterDriver` first.
I found that mosn recently add a zipkin driver, we can upgrade mosn and get that feature
https://github.com/mosn/mosn/blob/bb9f0b53e466079c55862caba8729aca3ac6964f/pkg/trace/zipkin/driver.go#L33

**Comment by LXPWing** [comment]
mosn v1.0.2 is released and we are moving forward with this feature?

**Comment by seeflood** [comment]
@LXPWing I don't know when will mosn release 1.0.2
For now, we can upgrade mosn version using specific commit id , instead of waiting for 1.0.2
