### ISSUE TITLE
[draft]proposal: run services on wasm

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#610]
I propose that we compile micro-services into wasm modules and run them on wasm runtime.
These services should be smaller than traditional micro-services. Maybe we can call them "nano-service".
![image](https://user-images.githubusercontent.com/26001097/170481510-2b1b3aeb-85fd-4a8d-a853-b38f0f89b152.png)

We can assume that there's only one Layotto on one node:

![image](https://user-images.githubusercontent.com/26001097/170482570-c53d9dfd-ab5f-4e3e-a0f2-08760a5e25ce.png)

- How to "shrink to zero" when no request comes
Layotto runtime should monitor the workload of every wasm module. If the workload of service 2 decrease to zero, wasm runtime should offload the wasm module, or "swap the module to disk", so that the module won't consume memory.
The offload mechanism should be transparent to K8s.  In k8s view, there's still a service 2 running on this node.

- How to "cold start" when new request comes
If new requests come after "swapping to disk", Layotto runtime should:
   - hold the request
   - load the wasm module 
   - and then forward the request to the module.

- How to "scale out" on one node
a. Raise the resource limits of service 2
b. Load another service_2.wasm

- How to "scale out" to run service 2 on more nodes
Layotto should report metrics of service 2 to K8s, and it's K8s' business to decide whether to scale out to a new node.

- Milestones
At first ,we can run another [preview service](https://github.com/mosn/layotto/issues/471#issuecomment-1107511795) on wasm

**Comment by zhenjunMa** [comment]
What's the differences between a "nano-service" and a "function"?

**Comment by nobodyiam** [comment]
> What's the differences between a "nano-service" and a "function"?

Looks like they are quite similar concepts.

**Comment by seeflood** [comment]
This proposal is an idea for discussion. We need some ideas on "what's the next step of layotto+ wasm"  :)

> What's the differences between a "nano-service" and a "function"?

A service is "a group of functions" , like a pod is a group of containers. For example:
- a service might export 20 rpc endpoints
- these endpoints share same memory and connections 
- this "group of functions" is the minimum scheduling unit
- the computing model is "long-running services" , instead of "instantaneous function",  so that we don't have to work on hard things like "How to adapt the function model to k8s", "how to write another layer of scheduler", "how to do function orchestration"

**Comment by kevinten10** [comment]
Sounds like `function` + `layotto as daemonset`

> this "group of functions" is the minimum scheduling unit

How about `step function`, and then deploy layotto as daemonset to serve the group.

**Comment by seeflood** [comment]
>How about step function, and then deploy layotto as daemonset to serve the group.

Do you mean [aws step function](https://aws.amazon.com/cn/step-functions/?step-functions.sort-by=item.additionalFields.postDateTime&step-functions.sort-order=desc) ? I didn't know it. Let me learn and play it :P

**Comment by rayowang** [comment]
As said in the community meeting yesterday, whether it is an independent faas model or a nano-service model, I think both have great practical business value. As we all know, the former has many practical applications, such as Alibaba Cloud Function Compute. The latter will have higher practical value in search, recommendation, advertising and other businesses that require large-scale resources.

However, when it comes to resource isolation, I personally think that it is relatively certain that each wasm must have a certain degree of isolation, because it is necessary to ensure overall security and stability.

But for the resource problem of each layotto, in other words, how many layotto should a node deploy, more precisely in one or more ways such as container runtime, deamonset, microservice framework, etc., I think we need Discuss further.

**Comment by seeflood** [comment]
I just found that cloudflare open sourced their serverless runtime project "workerd" . They call their abstraction "nanoservice" too. Interesting 😆 

![image](https://user-images.githubusercontent.com/26001097/193715709-85ab4d9f-eb0f-4c20-a0d6-ed4684611537.png)

https://github.com/cloudflare/workerd
https://blog.cloudflare.com/workerd-open-source-workers-runtime/
