### ISSUE TITLE
bug: configuration API returns wrong `app_id` and `store_name`

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#613]
**What happened**:
When I play with [the configuration API demo](https://mosn.io/layotto/#/zh/start/configuration/start), I found that the demo printed some message with wrong `app_id` and `store_name`: 

![image](https://user-images.githubusercontent.com/26001097/170820085-71a0d16e-008d-4b64-b2fb-0688d401c0a2.png)

**What you expected to happen**:
Return correct app_id and store_name

**How to reproduce it (as minimally and precisely as possible)**:
Run the demo in https://mosn.io/layotto/#/zh/start/configuration/start

**Anything else we need to know?**:

**Comment by MichaelDeSteven** [comment]
plz assign the task to me

**Comment by seeflood** [comment]
@MichaelDeSteven ok. Thanks!
Your avatar is cool

**Comment by MichaelDeSteven** [comment]
@seeflood hhh，thanks

**Comment by seeflood** [comment]
https://github.com/mosn/layotto/pull/629 fixed the wrong app_id
Now the `store_name` is waiting to be fixed

**Comment by MichaelDeSteven** [comment]
> @MichaelDeSteven You can check the doc https://mosn.io/layotto/#/zh/start/configuration/start It should be "config_demo": ![image](https://user-images.githubusercontent.com/26001097/172429724-11921935-32d6-4f84-a157-63d81bf34192.png) It might be not easy to fix it. We can discuss

Got it.
