### ISSUE TITLE
can't open https://mosn.io/layotto

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#618]
**What happened**:
We got some feedbacks that users could not open the website
![image](https://user-images.githubusercontent.com/26001097/171027732-3426472e-5658-4502-9aa6-3c644367daf5.png)
It looks like that those js files are banned by the wall.
We need to replace these js url with some mirror sites or cdn

**What you expected to happen**:
Open https://mosn.io/layotto successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by azhsmesos** [comment]
please assigned it to me

**Comment by seeflood** [comment]
@azhsmesos Thanks!
