### ISSUE TITLE
无法正常在windows环境进行build

### ISSUE THREAD

**Issue by YoungMa962** [mosn/layotto#620]
### Your question
在  cmd\layotto\ 下执行  go build -o layotto  mosn.io/mosn/pkg/shm 报错
### Environment
windows10
- Layotto Version
main 分支
### Logs
![image](https://user-images.githubusercontent.com/104260107/171550194-af284adf-8517-46d6-8461-8c4cd6ba002c.png)
- Paste the logs you see.

**Comment by seeflood** [comment]
感谢反馈
windows下目前无法编译成功（因为依赖了Mosn,  mosn 没法在windows下编译
替代方案是可以直接用 layotto 的docker 镜像哈
```
docker pull layotto/layotto:latest
```

**Comment by seeflood** [comment]
@YoungMa962 hi, layotto 新加了用 docker-compose 启动的 quickstart 
https://mosn.io/layotto/#/zh/start/state/start
可以测试下能跑通么

**Comment by YoungMa962** [comment]
@seeflood 可以使用 docker-compose的方式跑通客户端demo，非常感谢！

**Comment by seeflood** [comment]
@YoungMa962 感谢反馈~
那先关闭 issue了哈
Welcome to the community!
