### ISSUE TITLE
ci: check that all code in `.proto` must have comments; 让 CI工具检查“proto 代码必须包含注释”

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#623]
**What would you like to be added**:
We can let CI to check that all code in `.proto` files must have comments.
For example, we have comments on state API, see https://github.com/mosn/layotto/blob/main/spec/proto/runtime/v1/runtime.proto#L440
![image](https://user-images.githubusercontent.com/26001097/171980027-b5624b66-e516-4c1e-9ad5-988188f02c37.png)

And these comments are used to generate document, see https://github.com/mosn/layotto/blob/main/docs/en/api_reference/runtime_v1.md#getstaterequest

But unfortunately, we don't have comments on File API. So the corresponding doc is empty. see https://github.com/mosn/layotto/blob/main/docs/en/api_reference/runtime_v1.md#getfilerequestmetadataentry
![image](https://user-images.githubusercontent.com/26001097/171980499-8dafbc00-ec70-41c0-bd87-309146d21944.png)

**Why is this needed**:
Make sure we have necessary comments on api spec

**Comment by MichaelDeSteven** [comment]
A bit of complex for me maybe. I can give it a try.

**Comment by seeflood** [comment]
@MichaelDeSteven ok. Thanks!
We need to search for any existing linter to achieve this goal.
I know there are some linters for proto files, but haven't look into details:
https://github.com/ckaznocha/protoc-gen-lint
https://github.com/uber/prototool
https://github.com/bufbuild/buf

**Comment by MichaelDeSteven** [comment]
> @MichaelDeSteven ok. Thanks! We need to search for any existing linter to achieve this goal. I know there are some linters for proto files, but haven't looked into details: https://github.com/ckaznocha/protoc-gen-lint https://github.com/uber/prototool https://github.com/bufbuild/buf

we can use [buf](https://docs.buf.build/lint/rules#comments) linters to achieve this goal.
here is my step:
1. config `buf.yaml` in project root directory.
``` ymal
version: v1
lint:
  use:
    - MINIMAL
    - COMMENT_ENUM
    - COMMENT_ENUM_VALUE
    - COMMENT_FIELD
    - COMMENT_MESSAGE
    - COMMENT_ONEOF
    - COMMENT_RPC
    - COMMENT_SERVICE
```
2. write makefile and dockfile
we can execute `buf lint` to check comment before compile proto files and generator the corresponding doc.

**Comment by seeflood** [comment]
@MichaelDeSteven Sounds great! We can run this linter in our CI
Could u submit a PR for it?

**Comment by seeflood** [comment]
@MichaelDeSteven Hi, how about you continue with this issue?
As for https://github.com/mosn/layotto/pull/669 , I will help do it

**Comment by MichaelDeSteven** [comment]
> @MichaelDeSteven Hi, how about you continue with this issue? As for #669 , I will help do it

Apologies for the delayed response.
ci task has some progress. 
1. `buf lint` will be executed when we use `make proto.doc`
![image](https://user-images.githubusercontent.com/51652084/180433597-ca560617-a07c-42ea-8d1e-4688f9320557.png)
here is result of the above pic.
empty comment item is more than 100, which will be fixed.

2. `buf lint` is not support check `trailing comments` but I found the [project doc](https://mosn.io/layotto/#/zh/api_reference/comment_spec_of_proto) says that trailing comments is support. Maybe we should only support leading comments to simplify issues?
<img width="382" alt="image" src="https://user-images.githubusercontent.com/51652084/180434879-5e937152-bdd6-4951-876e-9433b5d02d4b.png">

Looking forward to your reply.

**Comment by seeflood** [comment]
@MichaelDeSteven 
Regarding `trailing comments`: yes, we can only check leading comments to simplify it.

Regarding `make proto.doc` and `buf lint`: actually we want to check the comments automatically in the CI, so that when contributors want to modify the proto files, the CI can tell him "hey, please write some comments on them". 
Therefore, could you add this  `buf lint` check in the CI ?

Thanks a lot for your contribution!

**Comment by MichaelDeSteven** [comment]
Hi @seeflood, I hava two question.
1. The scope of comments. We just need to check the COMMENT_ENUM, right? If we check all of place including COMMENT_ENUM\COMMENT_MESSAGE\COMMENT_SERVICE and so on, I need take some time to add necessary comments.

2. I have not write CI file experience. The CI of the [buf](https://docs.buf.build/ci-cd/github-actions#buf-setup). I just need to follow them, right? Is that we need to provide makefile that developer can check `.proto` file in local env before pr?

**Comment by seeflood** [comment]
@MichaelDeSteven 
1. I think you can make it check all, including COMMENT_ENUM\COMMENT_MESSAGE\COMMENT_SERVICE.
You don't have to add comments for all of them yourself, which is tiring. 
We can add comments together in some other PR. Maybe just adding a simple comment "Required" or "Optional" is enough.

2. Yes you can follow the guide and modify the github workflow file
> we need to provide makefile that developer can check .proto file in local env before pr?

Yes, besides github workflow, I think a makefile script is helpful.

**Comment by MichaelDeSteven** [comment]
> @MichaelDeSteven
> 
> 1. I think you can make it check all, including COMMENT_ENUM\COMMENT_MESSAGE\COMMENT_SERVICE.
>    You don't have to add comments for all of them yourself, which is tiring.
>    We can add comments together in some other PR. Maybe just adding a simple comment "Required" or "Optional" is enough, which indicates whether this field is necessary or not .
> 2. Yes you can follow the guide and modify the github workflow file
> 
> > we need to provide makefile that developer can check .proto file in local env before pr?
> 
> Yes, besides github workflow, I think a makefile script is helpful. But if you find the makefile hard to write, you can split this issue into different PR, one PR for github workflow, another PR for makefile script.

I open a pr. Review it plz.
