### ISSUE TITLE
Develop a "basic" dockerfile

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#628]
**What would you like to be added**:
Currently there's a `runtime_config.json` in the Layotto dockerfile:
![image](https://user-images.githubusercontent.com/26001097/171994024-237cec34-f4ab-4119-88f4-9ccabac17082.png)

If users want to modify the json file, they have to write a new dockerfile and generate a new docker image, which is annoying.

We should provide a "basic" dockerfile, which is common enough and decoupled with the config.json, so that it can be used with any config.json files.
Users can deploy our "basic" docker image with their own config.json, by mounting volumes or writing their own dockerfile based on it

**Why is this needed**:
Make Layotto more user-friendly.
It's a subtask of #392

**Comment by Xunzhuo** [comment]
Sorry, I think the old dockerfile has been modified into a generic one? How does the IMAGEBUILD directory generate? I think I have removed them.

**Comment by seeflood** [comment]
@Xunzhuo Yes you are right!
I rechecked the project and found that the `IMAGEBUILD` is a legacy directory in my local file system.
I will close this issue and write a document on "how to play quickstart with docker"
