### ISSUE TITLE
the relative path in `secretFile` is error-prone;  限制 secretFile 能访问的路径

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#631]
**What happened**:
Currently we have `secretFile` configuration in config.json. 
https://github.com/mosn/layotto/blob/4f5a3e490663328c06b39c922c7e2b44427dab6e/configs/config_standalone.json#L62
This configuration uses relative path, which is error-prone.

- Case 1. Success
```
cd ${project_path}/cmd/layotto
go build -o layotto
./layotto start -c ../../configs/config_standalone.json
```

- Case 2. An error occurs if you run layotto under some other directory
```
# under project root path
go build -o layotto cmd/layotto

# run layotto, but the current path is different from the quickstart doc
./layotto start -c configs/config_standalone.json
```

error message:
![image](https://user-images.githubusercontent.com/26001097/172297427-b1cfb360-7126-4b9f-b30c-177888902c7c.png)

- Case 3. Security issues
If someone configurates some other path as the `secretFile`, security issues may arise.
For example, we can configurate a path where we don't have read permission, and leverage layotto to read the sensitive data.

**What you expected to happen**:
Restrict that the `secretFile` configuration can only refer to the files under same path.
For example:
```
 "secretsFile": "secret_local_file.json" 
```
And Layotto will try to read the `secret_local_file.json` under the same path with config.json

**How to reproduce it (as minimally and precisely as possible)**:
See case 2 above

**Anything else we need to know?**:

**Comment by akkw** [comment]
这个我来看一下吧

**Comment by seeflood** [comment]
@akkw Cool. Thanks!

**Comment by MichaelDeSteven** [comment]
plz assign it to me, thx

**Comment by seeflood** [comment]
@MichaelDeSteven Cool. Thanks!

**Comment by seeflood** [comment]
@MichaelDeSteven 是的，如果发现不在configs 目录就报错
