### ISSUE TITLE
proxy-wasm-go-host 在Apple M1 平台上无法启动

### ISSUE THREAD

**Issue by akkw** [mosn/layotto#634]
### Your question

Describe your question clearly.

### Environment

- Layotto Version

### Logs

- Paste the logs you see.
依次执行
go mod tidy
go mod vendor
go run .

<img width="804" alt="image" src="https://user-images.githubusercontent.com/54854743/172622807-331c09d9-e6fe-483c-915e-0efadb787c7b.png">

**Comment by seeflood** [comment]
related issue: https://github.com/wasmerio/wasmer-go/issues/167
