### ISSUE TITLE
use docker-compose to start minIO and layotto

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#636]
**What would you like to be added**:
We have File API quickstart document showing users how to build and start layotto locally:
https://mosn.io/layotto/#/zh/start/file/minio

And now we can add a docker-compose to start minIO and layotto with one command, and then improve the quickstart.

 Examples are redis&layotto quickstart. I modified those redis related quickstarts showing users how to use docker-compose to start redis and layotto:
https://mosn.io/layotto/#/zh/start/state/start
https://mosn.io/layotto/#/en/start/state/start
![image](https://user-images.githubusercontent.com/26001097/172752535-d99f8955-34dd-40fb-9d76-725ac811f84b.png)

and:
![image](https://user-images.githubusercontent.com/26001097/172752614-7ae3cf80-bb6e-464e-b396-f36d15ea0a78.png)

**Why is this needed**:
Make layotto more user friendly

**Comment by bxiiiiii** [comment]
Could be assigned to me.

**Comment by seeflood** [comment]
@bxiiiiii ok. Thanks!

**Comment by bxiiiiii** [comment]
@seeflood 
> layotto    | 2022-06-13 10:30:42,285 [DEBUG] [network] [read loop] Error on read. Connection = 3, Local Address = 172.20.0.3:34904, Remote Address = 172.20.0.1:51558, err = EOF
The error log is as above, the request from layotto to minIO cannot be sent, how should the IP address be changed to 127.0.0.1?

**Comment by seeflood** [comment]
@bxiiiiii Did you change the listener address in config.json from `127.0.0.1` to `0.0.0.0`?
![image](https://user-images.githubusercontent.com/26001097/173338389-7ffea208-564a-4dd4-8968-9c40b51dd553.png)

**Comment by bxiiiiii** [comment]
@seeflood Of course. layotto can already receive the request from the client, but it failed to send to minIO.

**Comment by seeflood** [comment]
@bxiiiiii Then remember to modify the minio address in the config.json:
![image](https://user-images.githubusercontent.com/26001097/173341792-cf9d06cc-10f0-41d4-a857-4708dd559cc2.png)
You can take `docker/layotto-redis/config_redis.json` as an example

**Comment by bxiiiiii** [comment]
@seeflood  It does work!
btw, there is a an unimportant question.
when using **get**, we will receive in client
> recv file failed
hello layotto

Is there a problem?

**Comment by seeflood** [comment]
>recv file failed

I think it is a problem 🤔 
Can you get same error even when running the existing demo in https://mosn.io/layotto/#/zh/start/file/minio ,without docker?
If so, you can submit an issue to track it

**Comment by bxiiiiii** [comment]
@seeflood yes, the problem still exists.
ok.
