### ISSUE TITLE
[draft]proposal: demo project

### ISSUE THREAD

**Issue by LXPWing** [mosn/layotto#647]
#### 环境
语言：Java 8
框架：Spring Boot 2.6.7
依赖如下：
```
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.mosn.layotto</groupId>
            <artifactId>layotto-sdk-springboot</artifactId>
            <version>1.1.0</version>
        </dependency>
    </dependencies>
```

#### 接口
preview service控制层(controller)开放File API和State API接口：

File API接口：调用layotto ali oss组件（或者可以是其他的存储系统，有待讨论）

State API接口：调用layotto redis组件

### product page页面

修改productpage包下的productpage.html页面和productpag.py代码

![1655111717542](https://user-images.githubusercontent.com/65880844/173327549-1c8fe0c4-f41c-4edd-ac13-52d42fd6a7d5.jpg)

![1655110659460](https://user-images.githubusercontent.com/65880844/173327587-16430b38-2adf-4754-b78f-4c85fb938cbc.jpg)

**Comment by LXPWing** [comment]
@seeflood 要不在Layotto group开一个新的preview service仓库，我好提交代码

**Comment by seeflood** [comment]
@LXPWing ok. 我理解需要:
- fork istio, 因为 bookinfo 在istio 仓库里，我们需要fork出来改product page页面
我 fork 好啦，在 https://github.com/layotto/istio
并且基于 1.10.6 tag 打了个新分支 preview_service, 作为仓库的默认分支，可以往这提交修改

- preview service，这个写在 java-sdk仓库的 examples 目录里如何？ https://github.com/layotto/java-sdk/tree/main/examples

**Comment by LXPWing** [comment]
👌

**Comment by seeflood** [comment]
todo:
- [ ] 确认下图片路径格式 @seeflood

**Comment by seeflood** [comment]
@LXPWing 存取图片可以先用 File API 实现 (因为 OSS API review、开发java sdk还需要一些时间）
路径格式是 `bucket/xxx/xxx/xx.jpg` 这样
@wenxuwan 可以补充下其他细节

**Comment by seeflood** [comment]
@LXPWing LGTM

**Comment by wenxuwan** [comment]
@LXPWing LGTM

**Comment by seeflood** [comment]
action:
- @LXPWing submit an issue to record the local development problem (python app can't invoke preview service without istio)
- @seeflood review python app https://github.com/layotto/istio/pull/1

**Comment by LXPWing** [comment]
`python app can't invoke preview service without istio`solved
