### ISSUE TITLE
add comments for File API in proto files; 给 proto 代码添加注释

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#652]
**What would you like to be added**:
add comments for [File API in proto files](https://github.com/mosn/layotto/blob/31dda6a27c9719dc33ab0d8e9f19c1e1f49972f8/spec/proto/runtime/v1/runtime.proto#L73) .
For example, add comments for code below:
![image](https://user-images.githubusercontent.com/26001097/173553694-98a12116-27db-4068-808f-1f136562c138.png)

**Why is this needed**:

chinese:
为 proto 文件中[file API 相关接口](https://github.com/mosn/layotto/blob/31dda6a27c9719dc33ab0d8e9f19c1e1f49972f8/spec/proto/runtime/v1/runtime.proto#L73) 补充注释. 
有了更多注释后，可以用工具根据注释生成[文档](https://github.com/mosn/layotto/blob/main/docs/en/api_reference/runtime_v1.md)

**Comment by XiaoYaoheihei** [comment]
Maybe I can help to add, could you assign it to me?
Thank you!

**Comment by seeflood** [comment]
@XiaoYaoheihei Sure, thanks!

**Comment by XiaoYaoheihei** [comment]
Do I need to provide comments for the .proto files of all branches, I see that the .proto files of the master branch have been completed.
