### ISSUE TITLE
Layotto integrate with istio 1.10; Layotto跟istio集成

### ISSUE THREAD

**Issue by zhenjunMa** [mosn/layotto#664]
### 1. Background

1. istio is a famous implementation of ServiceMesh, using Envoy as the data plane by default.
2. mosn can be integrated with istio as an alternative data plane to envoy.
3. layotto, as an implementation of Application Runtime, is based on mosn and hopes to combine Service Mesh and Application Runtime.

### 2. Desc

Since istio can integrate mosn, this task is to integrate Layotto as a data plane with istio. For example, when application call InvokeService API that provided by Layotto, we can use the traffic governance capacity of istio, such as traffic control, fault injection, and so on.

### 3. Reference

1. istio: https://github.com/istio/istio
2. mosn: https://github.com/mosn/mosn
3. layotto: https://github.com/mosn/layotto
4. mosn integrate with istio: https://istio.io/latest/zh/blog/2020/mosn-proxy/
5. doc of layotto integrate with istio 1.5.x : https://mosn.io/layotto/#/zh/start/istio/start
6. code of layotto integrate with istio 1.5.x: https://github.com/mosn/layotto/tree/istio-1.5.x

### 4. related issues

1. #467 
2. #311 

# 中文

### 1. 背景

1. istio 是 ServiceMesh 方向上一个非常火热的解决方案，默认使用 envoy 作为数据面。
2. mosn 作为一个对标 envoy 的另一种数据面实现，也可以跟 istio 集成，作为 envoy 的一种替代方案。
3. layotto 作为 Application Runtime 的一种实现，基于 mosn 开发，期望可以结合 Service Mesh 跟 Application Runtime 两种思想。

### 2. 描述

既然 istio 可以集成 mosn ，且 layotto 跟 mosn 是一体的，因此本次的任务是把 layotto 作为数据面跟 istio 进行集成，以服务调用为例，在应用通过 layotto 的 invokeService API 去调用目标服务时可以直接复用 istio 强大的治理能力，比如流量控制、故障注入等等。

layotto 之前就已经可以跟 istio 1.5.x 集成，由于落后当时的 istio 版本太多，最终没有合并到主干，本次任务希望可以集成 1.10.x 之后的istio。

### 3. 参考资料

1. istio: https://github.com/istio/istio
2. mosn: https://github.com/mosn/mosn
3. layotto: https://github.com/mosn/layotto
6. mosn集成istio参考文档: https://istio.io/latest/zh/blog/2020/mosn-proxy/
7. layotto集成istio参考文档: https://mosn.io/layotto/#/zh/start/istio/start
8. layotto集成istio 1.5.x分支: https://github.com/mosn/layotto/tree/istio-1.5.x

### 4. 相关issues

1. #467 
2. #311

**Comment by rayowang** [comment]
assign

**Comment by seeflood** [comment]
@rayowang Thanks!
