### ISSUE TITLE
[GLCC 2022 Draft] Integrate test

### ISSUE THREAD

**Issue by IRONICBo** [mosn/layotto#670]
# Layotto集成测试

### 课题理解与实现思路

1. **配置文件编写**：按照`config_XXX.json`的格式，增加启动配置文件`etcd`，`zookeeper`，`etcd`配置在`runtime_config.json`中作为配置中心已经被使用，`zookeeper`的配置在`config_zookeeper.json`中也已经被使用。
2. **组件测试代码编写**：`layotto/sdk/go-sdk/test/runtime`包下的`other_component_integrate_test.go`和`redis_integrate_test.go`，各个组件API的测试代码在`layotto/demo`包下有部分的功能测试函数。
3. **Github Actions配置文件编写**，Github Actions的配置文件中提供了`Container`属性，

<img width="759" alt="image" src="https://user-images.githubusercontent.com/47499836/175547293-c0185364-625e-484a-9760-896d0c2f213e.png">

Docker file的包路径在`docker/app/integrate`下，通过编写Dockerfile编写不同组件需要的的环境信息，完成docker容器的构建，并且使用Github Actions在容器中进行功能性测试。其次是配置触发事件为Pull Request。配置文件的编写参考`.github/workflows/layotto-ci.yml`

**Comment by seeflood** [comment]
@IRONICBo Hi, did u participate in GLCC?
