### ISSUE TITLE
fix unstable ut; 修复不稳定的单测

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#682]
**What would you like to be added**:
The UT in `components/lock/zookeeper/zookeeper_lock_test.go` is not stable. Sometimes some lines of `components/lock/zookeeper/zookeeper_lock.go` are not covered in the UT and will lead to decreased test coverage.
For example , codecov reports it in https://github.com/mosn/layotto/pull/678#issuecomment-1168279135 
![image](https://user-images.githubusercontent.com/26001097/176330029-27898ffe-99ab-41ff-8a53-84726a0cd7a4.png)

It's because some code runs in a seperated goroutine. At the end of the test, the goroutine has not been executed:
![image](https://user-images.githubusercontent.com/26001097/176327910-24db83b4-130e-4e55-aef9-1b95a892144c.png)

We should make the test coverage stable

**Why is this needed**:
No more codecov warning

**Comment by ZLBer** [comment]
@seeflood  who make who fix  😅

**Comment by seeflood** [comment]
![image](https://user-images.githubusercontent.com/26001097/177510752-28e2c77c-0a80-4064-bbac-54899a16f9b1.png)

This issue is one of the tasks in https://github.com/mosn/layotto/issues/654 and you can get some presents after fixing it
