### ISSUE TITLE
[Discussion] Integrate with polarismesh

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#693]
Background:
As far as I know, some mosn users are trying to integrate mosn with polaris mesh. It's possible because both mosn and polaris mesh support XDS 3.0 .
We can integrate layotto with polaris mesh officially and add an online lab showing users how to do it.

Details:
I think there are two aspects :
- Use polaris as the control plane of MOSN. Polaris is responsible for service registry/discovery and sends cluster information to mosn through xds protocol
- Use polaris as the "operation plane" of MOSN. For example, use polaris to inject MOSN sidecar into application pods.

These are just vague ideas and we're not sure right now. We need to talk with users 

PolarisMesh introduction:
https://github.com/polarismesh/polaris
https://mp.weixin.qq.com/s/YP8aXGwd_vyYSgL8QyomvQ

action:
- [ ] @Xunzhuo @ZLBer 打探一下，看看怎么集成、找谁
- [x] @seeflood 和生产用户聊一下场景
- [ ] How to deploy sidecar with Polarismesh? Can we reuse the controller/ operator ?

**Comment by ZLBer** [comment]
@seeflood  any detail message?

**Comment by seeflood** [comment]
@ZLBer I added some details. These are just vague ideas and we're not sure right now. I will talk with users

**Comment by seeflood** [comment]
User Scenario:
PolarisMesh runs as a xDs server or a "control plane". Users use it to do service registry/discovery and deliver xDS data to data plane
