### ISSUE TITLE
bug: errors occur during startup; 启动时有报错

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#700]
**What happened**:
There are errors during startup. See https://github.com/mosn/layotto/runs/7208132527?check_suite_focus=true
![image](https://user-images.githubusercontent.com/26001097/177466887-6988107f-21f3-462c-a4b0-1b6601ca5f32.png)

**What you expected to happen**:
No errors. Or make sure these errors can be ignored

**How to reproduce it (as minimally and precisely as possible)**:
Run the demo in https://mosn.io/layotto/#/zh/start/secret/start.md

**Anything else we need to know?**:

**Comment by seeflood** [comment]
It's because we import the xds package but don't have xds configuration in the json file:
![image](https://user-images.githubusercontent.com/26001097/182097203-c270c333-b14f-4df5-b000-f11fc48a51a4.png)
I think modifying the json can solve this problem.

Reference:
https://mosn.io/blog/code/mosn-xds/

**Comment by akkw** [comment]
这个我来看看

**Comment by seeflood** [comment]
@akkw 好呀 assign 给你了~ 之前我查了一下，是因为 json 里没配xds相关的配置，供参考

**Comment by akkw** [comment]
![image](https://user-images.githubusercontent.com/54854743/185779383-7364aee2-8afc-47d8-b4b3-a4ecbcad2777.png)
配置中的hosts字段没找到，查了一下好像变成load_assignment 字段了，不知道我理解的对不对

**Comment by seeflood** [comment]
@akkw I guess it's because we don't have the `static_resources` in the config.json:
![image](https://user-images.githubusercontent.com/26001097/186691109-71a10a94-1018-4bf6-ab73-1fd2fee33b7c.png)
You can try to modify the json and check if the errors disappear

**Comment by seeflood** [comment]
@akkw hi, any progress on this issue?

**Comment by rayowang** [comment]
Now xds should already be using v3 version.
