### ISSUE TITLE
demo库在哪里？

### ISSUE THREAD

**Issue by hongbaotong** [mosn/layotto#704]
### Your question

demo库在哪里啊？文档里只运行了demo，找了一圈也没找到源码，都不知道是怎么调用的

**Comment by seeflood** [comment]
hi, 你指哪些 demo 代码？
以 https://mosn.io/layotto/#/zh/start/state/start 为例，go demo 在项目的这个目录下:
![image](https://user-images.githubusercontent.com/26001097/177900485-c6a5babd-0b70-4c4d-b4fa-43a99ab1ebef.png)

java demo 在 https://github.com/layotto/java-sdk
![image](https://user-images.githubusercontent.com/26001097/177900539-69422be4-d82c-473d-b49e-66850565db19.png)

**Comment by hongbaotong** [comment]
抱歉，是我眼花

**Comment by seeflood** [comment]
没事，那先关 issue 啦 😄 有问题再提
