### ISSUE TITLE
secret ref not flexible enough

### ISSUE THREAD

**Issue by ZLBer** [mosn/layotto#707]
**What would you like to be added**:
Now we can inject secret to  the metadata of components  using secretref config:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/20033804/178098107-88aff479-bf1f-4df6-91a8-e1634cfad3c6.png">
But the key we inject into the metadata must be consistent with the key stored in the secret store, which is very inconvenient. We need to add another field `ref_name`to represent the name of the key injected into the metadata. 

**Why is this needed**:
more flexible

**Comment by ZLBer** [comment]
@seeflood  i find some problem, the secret component may return many secrets in one get, so how to use the `ref_name`?
```
type GetSecretResponse struct {
	Data map[string]string `json:"data"`
}
```

**Comment by seeflood** [comment]
@ZLBer 
Solution A.  Add a separate field to identify secretstore name, like dapr
https://docs.dapr.io/operations/components/component-secrets/
![image](https://user-images.githubusercontent.com/26001097/179350236-ac71411f-b966-4edf-88b0-0369d3a87e54.png)



Solution B. Add a `store_name` field in this structure, e.g.
```
"secret_ref": [
                            {
                              "store_name": "local.file",
								 "key": "redis-secrets",
                              "sub_key": "redisPassword"
                            }
                          ]
```

**Comment by ZLBer** [comment]
@seeflood  my falt, secret can get  like below:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/20033804/179360841-8c07474c-af30-4993-b9d0-30bb9bbf85d9.png">

**Comment by seeflood** [comment]
@ZLBer It still doesn't solve the problem. You need a subKey in it.
I modified solution B to show a demo:
```json
  "secret_ref": [
    {
      "store_name": "local.file",
      "key": "redis-secrets",
      "sub_key": "redis-password",
      "inject_as": "redisPassword"
    }
  ]
```
