### ISSUE TITLE
Add a layotto lab showing users how to do traffic management with istio; 

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#709]
**What would you like to be added**:
Currently [our lab](https://killercoda.com/mosn-tutorial/course/layotto) is simple. We can add more labs.

For example, we can add a layotto lab showing users how to do traffic management using istio .

It's a subtask of #471 

Reference:
lab: https://killercoda.com/mosn-tutorial/course/layotto
source code of the lab:  https://github.com/mosn/mosn-tutorial
We can copy-paste and modify the existing mosn tutorial:  https://github.com/mosn/mosn-tutorial/tree/master/istio/mosn-with-istio

**Why is this needed**:

**Comment by seeflood** [comment]
@leemos-xx Ok. Thanks!
I wrote an introduction to the online lab, see https://mosn.io/layotto/#/zh/start/lab
MOSN has some good tutorials at https://github.com/mosn/mosn-tutorial/tree/master/istio , which currently can not run on killercoda because of some incompatibility issues between katacoda and killercoda. 
You can take a look at the mosn tutorials and I believe there are many materials that you can reuse

**Comment by seeflood** [comment]
@leemos-xx Hi, are u still working on it? Do you need help?
Recently MOSN add some labs on killercoda. We can reuse those labs, but with layotto image. See https://killercoda.com/mosn-tutorial/course/istio

**Comment by leemos-xx** [comment]
sry, I've been too busy lately, it may last until the end of August, if this task is more urgent, you may need to assign it to someone else first.

**Comment by seeflood** [comment]
@leemos-xx That's OK, I can assign it to myself :)
