### ISSUE TITLE
Add a layotto lab showing users how to "run applications on multiple cloud"

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#710]
**What would you like to be added**:
Currently [our lab](https://killercoda.com/mosn-tutorial/course/layotto) is simple. We can add more labs.

For example, we can add a layotto lab showing users how to "run applications on multiple cloud".

This lab will be based on the "Bookinfo" project. After the bookinfo project is merged, we can add a lab for it

It's a subtask of https://github.com/mosn/layotto/issues/471

Reference:
lab: [killercoda.com/mosn-tutorial/course/layotto](https://killercoda.com/mosn-tutorial/course/layotto)
source code of the lab: [mosn/mosn-tutorial](https://github.com/mosn/mosn-tutorial)

**Why is this needed**:

**Comment by seeflood** [comment]
@LXPWing Hi, can I assign it to you?
After the bookinfo project is merged, we can add a lab for it

**Comment by seeflood** [comment]
@LXPWing Next we should solve this issue. 
As said in the https://github.com/mosn/layotto/issues/471#issuecomment-1107511795 , it includes:
- [ ] deploy the preview service on alibaba cloud and aws, with a public IP   @seeflood 
- [ ] build a docker image for the bookinfo project  @LXPWing 
- [ ] build a lab to show features  @LXPWing 
![image](https://user-images.githubusercontent.com/26001097/179906988-836b1325-8973-4f24-9fb6-da44558040a8.png)

**Comment by LXPWing** [comment]
@seeflood Java preview server needs an image in docker hub

**Comment by seeflood** [comment]
@LXPWing OK. So we need:
- [ ] 1. A dockerfile
- [ ] 2. Build and push docker image in the CI pipeline, like [what we did in the layotto repo](https://github.com/mosn/layotto/blob/c9e000dbd58a71d80f044ac8cafb7d44f5001d17/.github/workflows/layotto-ci.yml#L278)

Could u submit a PR for it?
If step 2 is too complex, we can only implement step 1 and push to dockerhub manually

**Comment by LXPWing** [comment]
@seeflood Where is my dockerfile push?

**Comment by seeflood** [comment]
@LXPWing We can tag it as `layotto/examples-preview-service` and push it to dockerhub.

As for the username/password to login to the dockerhub, you can configurate the github workflow to use the repo secret. An example is https://github.com/mosn/layotto/blob/c9e000dbd58a71d80f044ac8cafb7d44f5001d17/.github/workflows/layotto-ci.yml#L266
![image](https://user-images.githubusercontent.com/26001097/180370225-d7325c05-ea15-4613-849e-5c8d0304cc53.png)
