### ISSUE TITLE
notify API

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#712]
e.g. send SMS, send dingtalk message

action:
@kevinten10  give the first proposal

- IM API
  - issue: https://github.com/mosn/layotto/issues/715   
- SMS API
  - issue: https://github.com/mosn/layotto/issues/716  

- Email API
  - issue: https://github.com/mosn/layotto/issues/717
  - PR: https://github.com/mosn/layotto/pull/729
- PhoneCall API  @seeflood 
  - issue: https://github.com/mosn/layotto/issues/726
  - PR: https://github.com/mosn/layotto/pull/727

**Comment by kevinten10** [comment]
我认为notify API是具有实际业务价值的，它可以帮助用户更好的进行应用系统的监控告警通知，提高用户上云过程中的信心。

我之前写过一个java的工具库[vrml](https://github.com/project-vrml/vrml)，里面提供了使用IM/Email/SMS等进行通知的api。

这套工具在我们内部的系统中，目前得到了广泛的应用：

+ 当出现重要的exception/error时，仅使用日志error告警不及时，以及可能被淹没。所以这时候会通过IM/Email进行告警通知。
+ 一些job类的逻辑，在执行完毕后，会通过IM/Email进行report，避免开发人员去查看日志。

所以这套api的定位：仅做到'通知'这项能力就足以了，并不是通过这套api进行大批量的SMS/Email 推送/营销。

**Comment by seeflood** [comment]
>所以这套api的定位：仅做到'通知'这项能力就足以了，并不是通过这套api进行大批量的SMS/Email 推送/营销。

LGTM

**Comment by seeflood** [comment]
@kevinten10 萌新问下，像这种 发SMS/Email 的云服务，会允许跨云调用么？
比如应用部署到 aws 后，想继续调阿里云的服务发消息，这种情况可行么?

**Comment by kevinten10** [comment]
Hi，以我使用的经验，可能有以下几种情况：

#### 1. 阿里云的服务api是public的，aws允许出网访问

可以直接调用，这种一般是测试环境

#### 2. 阿里云的服务api是public的，aws不允许出网访问

需要在aws上借助proxy发起网络调用，一般生产环境的出网访问都要走proxy申请

#### 3. 阿里云的服务api仅允许内网访问

阿里云用户可能会将api设置为仅内网访问，或者像一些企业内部的SMS/Email等云服务也是仅私有云内网可访问。

这时候可能就需要在阿里云这边也部署一个proxy/gateway，aws的proxy访问到阿里云的这个proxy/gateway，再由这个proxy/gateway转发给内网服务。

#### 综上

可能要在component实现中，允许用户自定义proxy的能力，或者自定义发送行为逻辑（甚至用户自己重写component）的能力。

https://github.com/mosn/layotto/issues/715 ：

> 另，有这样一种场景：
> 
> IM api在私有云内部可以直接访问，但在公有云上无法直接访问，可能要通过转发/验证/代理等方式才能访问。
> 
> 这样哪怕我已有多语言的sdk，还是要为每种语言的sdk重新开发一套转发/代理的功能。
> 这时候我希望把这个逻辑放在sidecar中，这样只需要开发一次即可，对api也没有变动。
> 
> 综上，我个人觉得值得将IM api下沉到sidecar中，主要解决了多语言sdk的问题和后续自定义功能复用的问题。
> 
> 如果社区有成熟api，那复用也完全可以呢。

**Comment by seeflood** [comment]
@kevinten10 再请教下，你们有 phoneCall API的需求么（调接口给人打电话，发送文本语音

**Comment by kevinten10** [comment]
我们目前没有 phoneCall API的需求呢，我们做监控告警主要是 IM/SMS/EMail。

我们这边phoneCall一般是：触发了某个指标，由某个SRE系统/平台，监控到这个指标，再发起phoneCall。应该不会直接由业务应用调用sidecar发起。

不过我感觉phoneCall可能中小型公司会有使用场景吧，公司内部可能没有搭建一套专业的SRE平台，这时候业务应用判断发生重大故障时，可能会想发起phoneCall。

但如果可以使用"写入指标+监听指标+发起phoneCall"的方式，应该会更好，但不知道阿里云上是否有这种能力。（AWS上可以通过写入CloudWatch指标，然后给这个指标配一个告警，告警内容可以自己实现发起phoneCall）

说回来，这种可能存在重大故障的应用，一般也不会做成多语言吧？

**Comment by seeflood** [comment]
恩我理解监控系统可能有 phoneCall 的需求，就是设置不同的告警等级，低级别告警 发 SMS 就行，高级别告警要打电话
也不会多语言，就是单语言实现，但可能有多云部署需求（比如 AWS 上调用 AWS Pinpoint

**Comment by kevinten10** [comment]
> 但可能有多云部署需求（比如 AWS 上调用 AWS Pinpoint

那看起来，是的。PhoneCall API，应该是有客户用的，但可能比较少。

或者先集成到SMS API里面？

**Comment by seeflood** [comment]
@kevinten10 我单独提个 proposal 和 PR, 加 PhoneCall API 吧

另外，要不你给 IM API ，SMS API 和 Email API 各提个 PR?  PR 里只包含 proto 文件就行，这样方便根据讨论结果更新 proto

**Comment by seeflood** [comment]
I'm working on it
