### ISSUE TITLE
proposal: IM notify API [SaaS API]

### ISSUE THREAD

**Issue by kevinten10** [mosn/layotto#715]
Hi, This is `IM notify API` proposal.

### **What would you like to be added**:

saas api: IM notify api

### **Why is this needed**:

https://github.com/mosn/layotto/issues/712

### **Support situation**:

|IM|Docs|
|---|---|
|Dingtalk| https://open.dingtalk.com/document/group/send-a-dingtalk-robot-message |
|Dingtalk dapr| https://docs.dapr.io/zh-hans/reference/components-reference/supported-bindings/alicloud-dingtalk/ |

### **API spec**:

```proto
// Saas API
// Send the message to IM.
rpc SendIM(SendIMRequest) returns (SendIMResponse) {}

------

// SendIMRequest is the message send to im.
message SendIMRequest {

  // The invoke Id.
  string id = 1;

  // The saas service name, like 'dingtalk'/'wechat'/'...'
  string saas_name = 2;

  // The api access token.
  string secret = 3;

  // The IM sender tag.
  string sender_id = 4;

  // The IM receivers tag.
  repeated string receivers = 5;

  // The IM message type, like 'text'/'table'/'...'
  string message_type = 6;

  // The IM message data.
  bytes message_data = 7;

  // The metadata which will be sent to IM components.
  map<string, string> metadata = 8;
}

message SendIMResponse {
  // The saas requestId.
  string request_id = 1;

  // The data response from IM service.
  bytes data = 2;

  // The metadata returned from IM service.
  map<string, string> metadata = 3;
}
```

#### 1. IM原生API非常复杂，难取交集

无论是dingtalk，还是wechat等IM工具。在原生API设计上都有很多自己独特的请求参数，这取决于IM自身的一些设计。

例如：

+ 消息模板ID：有的IM具有模板，有的IM不需要模板即可发送。
+ 收件人格式：有的IM发送给自生成的ID，有的则使用 用户名/手机号 等进行发送。

#### 2. IM具有绑定性，弱移植性

一个公司，哪怕部署到混合云，大概率也只会使用一种IM工具，很少听说不同云的消息要发送给不同IM。

所以本身IM代码就不需要很强的可移植性，那么对于一些特有的字段，可以接受放在metadata中。

#### 3. Runtime API取核心字段，其他字段放metadata

尽可能取多种IM都有的一些概念，将这些字段放在API中，其他字段放metadata。

对于一次IM发送，有几个字段是必需的：

1. `sender_id`：发送账号的id/tag
2. `receivers`：接收账号的id/tag
3. `message_type`：如今的IM都支持多媒体，所以使用该字段标识消息类型
4. `message_data`：对应message_type的消息体

以及，设计两个基础字段：

1. `id`：用于进行一定的标识，从而可以实现基于id获取配置的功能。往往IM的配置相对静态，可以通过id获取IM的相关配置，减少在metadata中的字段
2. `saas_name`：多IM场景时使用，保留这样的可拓展性，但一般用不到该场景。当用到该场景时，由于不同IM的发送参数有巨大差异，如果在代码中传递metadata等字段，则可能无法移植，这时候就需要上述的 id 功能。

一个密钥字段：

1. `secret`：往往是accessToken，但也可通过上述 id 功能，由id获取对应的配置，在配置中获取accessToken。所以该字段往往不需要显式传入，但仍然在API中进行保留，以便于直接调用。

------

**Comment by seeflood** [comment]
我想先讨论确定下 scope。用户应该不止要调 IM，还要调邮件等渠道
scope:
a. 每类渠道有一个 API
b. 统一 API  for 所有渠道(IM、SMS、邮件、电话)

![image](https://user-images.githubusercontent.com/26001097/178277090-306cc865-ec34-4242-b536-aed75c5d3f92.png)

**Comment by kevinten10** [comment]
我个人比较倾向a方案。

因为这几种渠道，有大量的参数差异，无法被抹平。以及应用场景有明确的区别。
同时，可能有的场景逻辑会比较复杂，若采用b方案，则对其的改动可能会影响其他场景。

随着支持saas服务的增多，如果都统一到一个saas api中，将会膨胀为一个巨大api，增加了理解成本。

**Comment by seeflood** [comment]
@kevinten10 分析的有道理！a 方案更解耦
如果为每类能力设计一个 API，那么接下来的问题是: 
当前有必要设计 IM API 么？

具体来说:
1. 用户有从 A IM 透明切换到 B IM 的需求么（比如想不改代码从微信切到钉钉）？
（我这了解到的需求都是调钉钉，感觉通用的用户需求是“不管部署到阿里云还是aws，都是给 XXX IM 的YYY 群发消息”）
2. 如果 1 真有这需求，那真的有必要走 sidecar么？因为感觉 sidecar 的价值是”适配不同云服务”+“方便加字段改代码”，但发 IM 消息这事跟云服务无关，而且 API 长时间不变（比如钉钉发消息的接口，常年不变，似乎不会出现经常改的情况）。所以感觉更适合做成 sdk？
3. 如果确实要做到 sidecar 里，那 gRPC IM API 感觉是 wechaty 已经搞定的事情，我们是兼容 wechaty API 还是自己新设计一个呢？

以上只是抛出来问题，想听听你的意见哈

**Comment by kevinten10** [comment]
就我目前使用IM的场景来看：

> 用户有 “从 A IM 透明切换到 B IM ” 的需求么（比如想 "不改代码，从发微信消息切到发钉钉消息"）？
> 我这了解到的需求都是调钉钉，感觉通用的用户需求是“不管代码是部署到阿里云还是aws，都是给 XXX IM 的YYY 群发消息”

不太会有“从 A IM 透明切换到 B IM ”的场景，每个公司如果自己内部落地的话，可能是唯一指定的IM。
但如果将layotto/dapr/...放到云平台，作为托管服务呢？是否要支持不同用户的不同IM需求。

> 如果 1 真有这需求，那真的有必要走 sidecar么？因为感觉 sidecar 的价值是”适配不同云服务”+“方便加字段改代码”，但发 IM 消息这事跟云服务无关，而且 API 长时间不变（比如钉钉发消息的接口，常年不变，似乎不会出现经常改的情况）。所以感觉更适合做成 sdk？

就我的场景来看，我封装了一套java的im工具包，作为sdk提供给java应用使用。
但面临的问题是多语言的场景，要为每个im构建多语言的sdk吗？这是个不小的工作量。使用sidecar可以多语言复用一个逻辑。

> 如果确实要做到 sidecar 里，那 gRPC IM API 感觉是 wechaty 已经搞定的事情，我们是兼容 wechaty API 还是自己新设计一个呢？

如果它设计的足够好，足够通用，那我们就用它的吧。我粗略看了一下，发现它定义了很多的api，我们似乎只需要'发送消息'这一个，我目前还没有找到明确的这个api。

**Comment by kevinten10** [comment]
另，有这样一种场景：

IM api在私有云内部可以直接访问，但在公有云上无法直接访问，可能要通过转发/验证/代理等方式才能访问。

这样哪怕我已有多语言的sdk，还是要为每种语言的sdk重新开发一套转发/代理的功能。
这时候我希望把这个逻辑放在sidecar中，这样只需要开发一次即可，对api也没有变动。

综上，我个人觉得值得将IM api下沉到sidecar中，主要解决了多语言sdk的问题和后续自定义功能复用的问题。

如果社区有成熟api，那复用也完全可以呢。

**Comment by wenxuwan** [comment]
> 另，有这样一种场景：
> 
> IM api在私有云内部可以直接访问，但在公有云上无法直接访问，可能要通过转发/验证/代理等方式才能访问。
> 
> 这样哪怕我已有多语言的sdk，还是要为每种语言的sdk重新开发一套转发/代理的功能。 这时候我希望把这个逻辑放在sidecar中，这样只需要开发一次即可，对api也没有变动。
> 
> 综上，我个人觉得值得将IM api下沉到sidecar中，主要解决了多语言sdk的问题和后续自定义功能复用的问题。
> 
> 如果社区有成熟api，那复用也完全可以呢。

目前看来为了解决的问题：
1.解决多语言问题。
2.后续自定义功能复用（有可能会复用到）

那这个问题和dapr的outbinding是完全契合的。

可以参考一下：https://github.com/dapr/dapr/issues/3722

**Comment by kevinten10** [comment]
Hi，notify api确实在特征上，和dapr 的binding是契合的。

因为我个人比较大量的使用过notify api，所以我认为这套api具有实际意义，那对于这类api，我感觉从binding中拆出来会比较好呢：

bingding是一个较低级别的抽象，我们可以把任何东西都塞在里面。在初期，可能尽快的对接更多系统，先把东西放进去。但随着multi-runtime的发展，当我们发现一些领域的api具有更大使用价值时，我们可能要考虑将它们独立定义。

就sidecar中component的实现而言，我认为在layotto中基于binding写一个notify的组件，和单独定义一个notify的组件，可能没有什么大的不同。

但在用户层（或者说用户使用sdk时），这将有很大的不同：我们不可能要求用户使用原始的binding api，假如用户需要参照文档，自己往binding api中传那么多的参数/结构，这不够便利。那么就需要在这之上，为用户构建便捷易用的多语言的sdk api。

> 就这一点，我怀疑dapr binding api的实际用户有多少，上云应该是增效的过程，如果开发人员陷入了参考文档写binding api的困境，那为什么不使用开源已有的sdk呢，或者又要在这之上封装自己的sdk工具库了。

这就引入了以上问题，当我们在多语言sdk中定义这样的方法时，并将它们映射到binding api的grpc proto，那为什么不直接使用grpc proto来定义呢？

使用grpc proto，使该领域的api更加清晰，主要是使用户接入更加方便。

以及，可能涉及到另一个领域，那就是SDK模型，我们希望的是社区共用一套api（无论SDK/Sidecar...），这样用户在未来具有更多的可选择性，如果都放在binding api中，那似乎社区也就没有什么共同的api了，都是基于binding api，在上面再魔改自己的sdk api了。

**Comment by seeflood** [comment]
- 关于 Binding
我也觉得 proto 定义的接口 > binding 

- 关于是否要把 IM API 做在 sidecar 里
我纠结的还是这个 :(
举个例子，假如用户想给钉钉机器人发消息，每个语言的sdk 就是调 钉钉的 http 接口，感觉 sdk 也没有很重。如果为了节约一点调 http 的代码，就给 sidecar 增加复杂度，ROI 有点低

>就我的场景来看，我封装了一套java的im工具包，作为sdk提供给java应用使用。
但面临的问题是多语言的场景，要为每个im构建多语言的sdk吗？这是个不小的工作量。使用sidecar可以多语言复用一个逻辑。

@kevinten10 这部分代码量有多少呀，能贴个链接看看不？

**Comment by seeflood** [comment]
或者这样想：
如果没有 "随时能从 微信 换成 钉钉“ 这样的 ”可移植” 需求，那我们可以把钉钉的 http API 看成是一个“多语言 API”，你似乎不必维护多语言的 IM sdk，直接让业务方调 钉钉 的 http API 就行？

**Comment by kevinten10** [comment]
> @kevinten10 这部分代码量有多少呀，能贴个链接看看不？

代码是调用了私有云的IM的api，代码量不多的，主要是封装了http接口调用+通过configuration获取req参数。
复杂的是，当我在其他云上使用这个sdk时，我需要做改造（http接口只能在私有云内调用）

> 噢噢噢 刚看到 https://github.com/mosn/layotto/issues/715#issuecomment-1181264014
> 所以主要的多语言代码量在于代理转发逻辑？
> 好吧，那确实做在sidecar里是有价值的……

是的，我将为每种语言的sdk都添加一个跨云调用的功能，代码改造量很头疼。

**Comment by kevinten10** [comment]
> 或者这样想：
> 如果没有 "随时能从 微信 换成 钉钉“ 这样的 ”可移植” 需求，那……我们可以把钉钉的 http API 看成是一个“多语言 API”，我们似乎没必要“用 gRPC 再描述一遍钉钉 API”，你也似乎不必维护多语言的 IM sdk，直接让业务方调 钉钉 的 http API 就行？

恩恩，如果直接调用http api能解决问题也可以。

主要目前我们除了调用http API还有一些功能：

+ 通过configuration获取req参数，比如token、sender_id之类。这些参数一个是可能会变更，另一个是让业务使用方去了解这些也不太好，不够易用。
+ 如之前所述，跨云的代理逻辑

总结一下，直接http还是不够易用吧，要易用就要封装，封装就要 多语言+跨云代理 等功能。

> @kevinten10 如果 Layotto 支持了 IM API，你们有考虑迁移到 Layotto 上来么

如果我们后面使用了layotto，那是会使用它的IM API的。只不过我们可能要开发一个私有云IM的组件。

目前Capa的业务接入方，已经反馈过想在公有云上使用IM的功能，但之前封装的IM sdk没有支持跨云代理的功能，要开发一遍也挺费劲的（多语言开发一套），所以目前就没给接入方开放这个能力。
