### ISSUE TITLE
Deploy layotto pod in k8s.

### ISSUE THREAD

**Issue by kevinten10** [mosn/layotto#722]
**What would you like to be added**:

添加在k8s中快速部署一个layotto节点的方式。

就像k8s官方提供的示例，仅用一行kubectl即可完成部署：

https://kubernetes.io/zh-cn/docs/tasks/run-application/run-stateless-application-deployment/

```shell
kubectl apply -f https://k8s.io/examples/application/deployment.yaml
```

**Why is this needed**:

此部署并非layotto作为sidecar的部署方式，而是layotto作为一个单独pod的部署方式。

使用场景主要为：
+ 支持本地调试：https://mosn.io/layotto/#/zh/operation/local
+ quickstart，体验layotto
+ 作为独立节点模式，与k8s集成。see: https://github.com/mosn/layotto/issues/392

**Comment by kevinten10** [comment]
我觉得可以拆成3个yaml，提交到仓库中：

1. configmap.yaml：提供一份默认配置
2. deployment.yaml：同以上deployment
3. layotto-deploy-default.yaml：使用默认configmap，部署以上deployment

这样用户可以直接部署到k8s中，类似：

    kubectl apply -f https://layotto/deploy/layotto-deploy-default.yaml

如果想自行修改配置，也可以自己提供一个configmap，再使用上面的deployment.yaml

**Comment by seeflood** [comment]
>使用场景主要为：
>....
>作为独立节点模式，与k8s集成


如何理解“独立节点模式”?

**Comment by kevinten10** [comment]
Yes, I will submit a PR~

**Comment by kevinten10** [comment]
I plan to put the deployment yaml in this directory, please help to see if it is ok: 

`/layotto/demo/deploy/k8s/standalone/`

1. default_configmap.yaml
2. default_deployment.yaml
3. default_quickstart.yaml (1+2)

**Comment by seeflood** [comment]
@kevinten10 LGTM
