### ISSUE TITLE
Integrate with wasmtime; 集成 wasmtime 运行时

### ISSUE THREAD

**Issue by zhenjunMa** [mosn/layotto#732]
# 1. Background

Currently, Layotto supports load and run *.wasm files by integrating [wasmer-go](https://github.com/wasmerio/wasmer-go) and [wasmer](https://github.com/wasmerio/wasmer), now we want to support [wasmtime](https://github.com/bytecodealliance/wasmtime) as another WebAssembly Runtime.

# 2. Why is this needed?

Compared with wasmer, wasmtime has more advanced features, which allow us to make more settings for the running *.wasm files. For details, please refer to #607 

# 3. draft design

1. Related code paths
![image](https://user-images.githubusercontent.com/28104581/180602024-885e6624-9224-4363-a96c-110cf21c1174.png)

2. Reference Code

MOSN has provided extension points. the interface is located in the file: `pkg/types/wasm.go`. In theory, we can use the wasmtime API to implement several interfaces in Layotto.

# 4. Other references

1. https://github.com/bytecodealliance/wasmtime
2. https://github.com/bytecodealliance/wasmtime-go

## 中文

# 一、背景

目前 Layotto 是通过集成 [wasmer-go](https://github.com/wasmerio/wasmer-go) 跟 [wasmer](https://github.com/wasmerio/wasmer) 来支持 *.wasm 文件的加载运行，现在我们希望支持 [wasmtime](https://github.com/bytecodealliance/wasmtime) 来加载运行 *.wasm 文件

# 二、意义&价值

相比于 wasmer，wasmtime 具备更多的高级特性，可以让我们对运行着的 *.wasm 文件做更多设置，具体可以参考 #607 

# 三、设计草案

1. 相关代码路径
![image](https://user-images.githubusercontent.com/28104581/180602024-885e6624-9224-4363-a96c-110cf21c1174.png)

2. 参考代码

MOSN 已经留好了扩展点，接口所在文件：`pkg/types/wasm.go`，理论上应该在 Layotto 中结合 wasmtime 的 API 实现里面的几个接口即可。

# 四、其他参考资料

1. https://github.com/bytecodealliance/wasmtime
2. https://github.com/bytecodealliance/wasmtime-go

**Comment by seeflood** [comment]
进展：
- 不需要写到 mosn 仓库里，可以注册进去
- 函数有差异，有适配成本

**Comment by seeflood** [comment]
进展:
因为wasmtime对function注册相关的支持没有wasmer完备，还在单元测试

**Comment by rayowang** [comment]
目前集成wasmtime单测通过，集成测试有点问题，给bytecodealliance提了issue
https://github.com/bytecodealliance/wasmtime-go/issues/145

**Comment by rayowang** [comment]
https://github.com/bytecodealliance/wasmtime-go/issues/146

**Comment by rayowang** [comment]
目前demo中function2可以正常加载及运行，function1有点问题
https://github.com/bytecodealliance/wasmtime-go/issues/149

**Comment by rayowang** [comment]
https://github.com/bytecodealliance/wasmtime/issues/4194
