### ISSUE TITLE
Implement OSS API for java sdk; 让 java sdk 支持 OSS API

### ISSUE THREAD

**Issue by wenxuwan** [mosn/layotto#741]
**What would you like to be added**:
Implement OSS API for java sdk

**Why is this needed**:

Java users need it

**Comment by seeflood** [comment]
Reference:
java sdk: https://github.com/layotto/java-sdk
OSS API: https://github.com/mosn/layotto/blob/main/spec/proto/extension/v1/oss.proto
Layotto implements OSS API: https://github.com/mosn/layotto/pull/556
