### ISSUE TITLE
Issue with faas quickstart

### ISSUE THREAD

**Issue by nobodyiam** [mosn/layotto#745]
**What happened**:

I followed the [FaaS QuickStart](https://mosn.io/layotto/#/en/start/faas/start) documentation, but failed in the [Start Layotto](https://mosn.io/layotto/#/en/start/faas/start?id=a%e3%80%81start-layotto) step.

```
$ layotto start -c /home/docker/config.json
-bash: /usr/bin/layotto: cannot execute binary file: Exec format error
```

It looks like an issue caused in [Compile & install Layotto](https://mosn.io/layotto/#/en/start/faas/start?id=c%e3%80%81compile-amp-install-layotto) step since I compiled layotto in Mac but ran it in linux container, but I'm not sure about that.

**What you expected to happen**:

Users should walk through the documentation with no issue.

**How to reproduce it (as minimally and precisely as possible)**:
OS: macOS BigSur
Go: 1.15.6 darwin/amd64

**Comment by seeflood** [comment]
Thanks for your feedback!
I think there are several sub issues:
- [ ] fix `make wasm`. It should compile layotto in a docker container, successfully
- [ ] Build and push wasm image to dockerhub in our CI
@Xunzhuo Can we remove these comments and run this steps?

![image](https://user-images.githubusercontent.com/26001097/181727173-81ad57a3-7ac1-461b-9c1a-37306f89a800.png)

- [ ] move this quickstart to the online-lab

**Comment by Xunzhuo** [comment]
I will take a look this weekend
