### ISSUE TITLE
`GetNextId` in ZK component throw `zk: node does not exist`

### ISSUE THREAD

**Issue by zhenjunMa** [mosn/layotto#747]
**What happened**:

when I call `GetNextId` API in layotto that use zookeeper as its component, I got an error, `zk: node does not exist`, as below:

![image](https://user-images.githubusercontent.com/28104581/181876239-cb974830-b5b5-4304-a67d-33d9db91baa1.png)

**What you expected to happen**:

Get a unique ID

**How to reproduce it (as minimally and precisely as possible)**:

1. start a zookeeper server, maybe use docker
2. start layotto server, maybe execute this command: `./layotto start -c configs/config_zookeeper.json`
3. start a client to call `GetNextId`, maybe as follows:
```
cli, err := client.NewClientWithAddress("127.0.0.1:34904")
resp, err := cli.GetNextId(ctx, &runtimev1pb.GetNextIdRequest{
	StoreName: "sequencer_demo",
	Key:       sequencerKey,
})
```

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/28104581/181876336-22eb6db3-d861-4785-b06d-91228b73626b.png)

solution A:
we can add a method `createOrUpdate` to implement the logic that create a zk node when it doesn't exist or update it directly.

solution B:
add a method `isExist` to check if the request node has been created

**Comment by bxiiiiii** [comment]
方法的实现在这个文件里面进行吗
![1659168170743](https://user-images.githubusercontent.com/75570810/181887705-4f203940-6e50-4e44-b4ff-5046667e0ba9.jpg)

**Comment by zhenjunMa** [comment]
@bxiiiiii 不能在这里加，不然别人用不了，一个是你在我上面那个接口里面加，一个是你可以在GetNextId的实现里面不直接Set  而是先判断一下是否存在再set
