### ISSUE TITLE
关于状态资源配置模式的优化建议

### ISSUE THREAD

**Issue by HoHenSer** [mosn/layotto#759]
**What would you like to be added**: 
在设计状态存储的配置中模式中，如redis等相关的配置应该参照k8s中pvc和pv的设计模式，在代码中只需要什么申明存储类型和大小相关需求，具体的redis等地址的配置不应直接放在代码配置中，而是再抽象一层配置，用于运维或者自动化的方式创建绑定，做到业务代码和基础设施的具体配置分离：
   
![image](https://user-images.githubusercontent.com/8278941/184070721-cf7aa8a4-438e-45d1-bb06-022b1dae481a.png)

**Why is this needed**:代码逻辑和基础设施资源分离，研发和运维角色分离

**Comment by seeflood** [comment]
Hi, 这事儿我们一直想做，有段时间了 😄 
之前社区会议也聊过  https://www.bilibili.com/video/BV15Z4y1q7JL?spm_id_from=333.999.0.0&vd_source=65cf108a3fb8e9985d41bd64c5448f63&t=1040.7

核心思想就是：
- 应用声明类似 PVC 的”我需要什么feature“（比如叫 `feature set claim`)
- 组件有独立 CRD，以及有描述”我有什么 feature“ 的CRD ( 比如叫 `feature set`)
- 通过 K8s 部署应用的时候, 自动做 feature 协商、绑定组件；如果没有组件能满足 `feature set claim` 的需求，则部署报错


不过因为没有需求推动，就一直没启动搞这事……您感兴趣共建么，或者您现在有相关需求么~
