### ISSUE TITLE
bookinfo部署问题

### ISSUE THREAD

**Issue by LXPWing** [mosn/layotto#765]
### 环境
preview server k8s yaml:  https://github.com/LXPWing/preview-server-k8s-yml

线上实验室配置文件： https://github.com/LXPWing/mosn-tutorial/tree/master/layotto/layotto-with-bookinfo

bookinfo k8s yaml: https://github.com/LXPWing/layotto/tree/main/deploy/k8s/bookinfo

线上实验室演示：https://killercoda.com/lixingpeng/course/layotto/layotto-with-bookinfo

### 问题
preview server与bookinfo都部署在default namespace下， preview server yml中设置`replicas: 1`但实际部署中会超出1个pod且报错，同时preview server pod中的镜像数量会比yml中设置的多1个。bookinfo 的一些pod也会出现超出设置数量且报错。

![image](https://user-images.githubusercontent.com/65880844/184784734-54a64a7e-b837-45a0-ae36-0846721b0557.png)

### 尝试解决
preview server和bookinfo的namespace分离，但是preview serve一直处于ContainerCreating

![image](https://user-images.githubusercontent.com/65880844/184788023-b2445e88-3346-455d-80c6-7683c9c6811c.png)

**Comment by seeflood** [comment]
![image](https://user-images.githubusercontent.com/26001097/186802866-572e1cfe-d48a-4f27-bfac-f9ee3ca0bebd.png)
Try:
```
kubectl describe pods pod_name -n layotto
```
https://serverfault.com/questions/728727/kubernetes-stuck-on-containercreating

**Comment by seeflood** [comment]
It's ok now.
![image](https://user-images.githubusercontent.com/26001097/186804060-9ceb5701-3b6e-48c6-80eb-61889876f627.png)

I fixed it by adding a namespace for the configmap:
![image](https://user-images.githubusercontent.com/26001097/186803881-ed8e198a-51c9-4b17-a584-299fb390b0d4.png)


But we have new problems now:

![image](https://user-images.githubusercontent.com/26001097/186804474-a7d1a5cc-f151-47d7-b3f5-04f1748c6af1.png)

**Comment by seeflood** [comment]
You can try:
- run k8s with more nodes
- increase the resource limit

看着是资源不足，可以换成更多节点的k8s试试，以及调高对容器占用资源的限制

**Comment by seeflood** [comment]
Looks like we can't run K8s with more than 2 nodes in killercoda?
see https://killercoda.com/creators
![image](https://user-images.githubusercontent.com/26001097/186871337-c5d7c93e-e1f6-4849-85ab-97bc98617dde.png)

You can try to solve the problem by raise the limit on resources. If it can't solve the problem, we have to deploy the preview-server and the storage systems in other environment instead of in the lab. For example, we can deploy the preview-server and redis on alibaba-cloud and aws

**Comment by LXPWing** [comment]
Currently using "kubernetes-kubeadm-2nodes" store can be deployed in the lab but preview cannot be deployed

**Comment by LXPWing** [comment]
May need to use other cloud servers

**Comment by seeflood** [comment]
@LXPWing OK. Let me deploy it on alibaba-cloud first.

**Comment by seeflood** [comment]
@LXPWing I'm thinking about deploying the latest binary automatically in our CI/CD. Are u interested in doing some research on the solution?
This is not necessary, it doesn't matter if we can't implement it

**Comment by LXPWing** [comment]
I don't understand what this “the latest binary automatically in our CI/CD.”

**Comment by seeflood** [comment]
I mean: 
Currently, after a new PR get merged into the main branch, our github workflow will compile the code into a binary, and then upload the docker images and binary files to github. 
For example, you can see the uploaded binary files in https://github.com/mosn/layotto/actions/runs/2924861106 
![image](https://user-images.githubusercontent.com/26001097/188628988-4c6aff5e-9f03-4a9c-8d56-3f49cff07c74.png)

That's good. I'm thinking about making it better.
For example, after uploading the images and binary files, the tools can notify our preview server, and the preview server will download the new docker image or binary file and then deploy it.
I guess there are already tools about it ( they call it "continuous deployment")

**Comment by LXPWing** [comment]
Will jenkins be used？

**Comment by seeflood** [comment]
@LXPWing We don't have Jenkins yet :(   It's better that we achieve this goal using github action.
It's just an idea. As the first step, we only need to investigate "whether there are existing tools to do it". If not, or if the tools are too complex to use, we give up :)

**Comment by LXPWing** [comment]
“the tools can notify our preview server”github action may not be completed.stop containers -> delete image -> pull new image -> start Containers may jenkins can do it.

**Comment by seeflood** [comment]
@LXPWing Deploying jenkins sounds complex 😢 I hope there's some agent on the server, which:
-  listen to the webhook events
- download image
- remove the existing container
- start a new container

If there isn't a simple solution, let's give up and do something more important...

**Comment by seeflood** [comment]
https://github.com/layotto/java-sdk/pull/35
I added startup & stop scripts for preview service. But we still need several things to deploy preview service, including:
- correct `config.json` file to use redis as state store and local file system as `file` component.
- initialize the data in the storage system
![image](https://user-images.githubusercontent.com/26001097/189264239-208128ad-c620-4b74-9399-dffeac93efdc.png)
