### ISSUE TITLE
db link not open in mysql sequencer？

### ISSUE THREAD

**Issue by ZLBer** [mosn/layotto#777]
**What happened**:  
the db link did not initialized in mysql sequencer @GimmeCyy
related pr: https://github.com/mosn/layotto/pull/605
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by seeflood** [comment]
Thanks for your feedback
@GimmeCyy Could u help with this issue?

**Comment by GimmeCyy** [comment]
![image](https://user-images.githubusercontent.com/78087740/187845758-83c96dd5-1a0c-4b1a-97ed-4a9f670d5132.png)
这里的db是用sqlmock.New()出来的，所以没有去连接一个真实的数据库
