### ISSUE TITLE
编译构建Layotto时，检查envoyproxy/go-control-plane@v0.10.0校验和失败

### ISSUE THREAD

**Issue by ChloroplastYu** [mosn/layotto#782]
**What happened**:
![image](https://user-images.githubusercontent.com/51773819/189262082-4b906717-fef4-4ece-b5e2-07a9e1462b26.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
commit id：3fbcdf7d6d9a892a8becade088e643e6a99efab8

**Anything else we need to know?**:

**Comment by seeflood** [comment]
Sorry I can't reproduce it 😢 
![image](https://user-images.githubusercontent.com/26001097/189266405-16adb139-3390-4735-8659-01ef4893490e.png)
It seems that you have modified the `go.mod` or `go.sum`. You can try to revert them, or just `go mod tidy`

**Comment by ChloroplastYu** [comment]
> Sorry I can't reproduce it 😢 
> 
> ![image](https://user-images.githubusercontent.com/26001097/189266405-16adb139-3390-4735-8659-01ef4893490e.png)
> 
> It seems that you have modified the `go.mod` or `go.sum`. You can try to revert them, or just `go mod tidy`
> 
> 

Thank you for your reply！I clean my path variable and reinstall go then slove the problem
