### ISSUE TITLE
proposal: Cryption(Encrypt/Decrypt) API.

### ISSUE THREAD

**Issue by kevinten10** [mosn/layotto#794]
Hi, This is `Cryption(Encrypt/Decrypt) API` proposal.

### **What would you like to be added**:

add new api: Encryption and Decryption API

### **Support situation**:

|Cryption|Docs|
|---|---|
|AWS Encryption|https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html|
|Aliyun Encryption|https://help.aliyun.com/document_detail/189379.htm?spm=a2c4g.11186623.0.0.ea8a9b75VwOmNX#task-1995115|

### **API spec**:

```proto
// Cryption API

// Encrypt
rpc encrypt(CryptRequest) returns (CryptResponse) {}

// Decrypt
rpc decrypt(CryptRequest) returns (CryptResponse) {}

------

// CryptRequest is the message send to cryption.
message CryptRequest {

  // The cryption infos.
  repeated KeyInfo infos = 1; 

  // The metadata which will be sent to cryption components.
  map<string, string> metadata = 2;
}

message KeyInfo {

  // The cryption key.
  string key = 1;

  // The cryption type.
  string type = 2;

  // The properties for custom request.
  map<string, string> properties = 3;
}

// CryptResponse is the message return from cryption service.
message CryptResponse {

  // The cryption results.
  repeated DataInfo results = 1; 

  // The metadata which return from cryption components.
  map<string, string> metadata = 2;
}

message DataInfo {

    // The cryption invoke result.
    string status = 1;

    // The cryption raw key info.
    KeyInfo rawKey = 2;

    // The cryption result;
    string result = 3;
}
```

#### 1. 加解密核心字段

无论加密还是解密，核心字段主要有以下两个：

+ key：需要进行加解密的字符串
+ type：标识了，加解密的类型，例如 address/phone/mail...

#### 2. 返回体设计

1. rawKey：原始的加解密信息
2. status：调用加解密服务的调用结果，可能是 200/300/400/404/... 这种格式
3. result：对应原始key，其对应的加解密结果

#### 3. 可拓展性设计

首先，一次调用的参数设计为repeated数组形式，是考虑到批处理加解密的场景。

对于每一组 (key, type) ，提供了一个 `map<string, string> properties`，是考虑每个key可能有额外要求，例如是否和敏感信息等。

其次对于每一次调用，按照其他api的设计，保留了 metadata 字段。

**Comment by kevinten10** [comment]
AWS Enctyption Java SDK 示例：https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/java-example-code.html

Runtime API到AWS API的参数映射：

+ KeyInfo.key -> aws data
+ KeyInfo.type -> aws keyArn
+ KeyInfo.properties -> aws encryptionContext

**Comment by kevinten10** [comment]
Aliyun Encryption Java SDK 示例：https://help.aliyun.com/document_detail/189379.htm?spm=a2c4g.11186623.0.0.ea8a9b75VwOmNX#task-1995115

使用方式同AWS Encryption

**Comment by seeflood** [comment]
- 关于 type
>type：标识了，加解密的类型，例如 address/phone/mail...

所以这个是密钥的标识? 叫 key_id 如何?

**Comment by seeflood** [comment]
- 关于批量操作
@kevinten10 hi, 我最近也做了一些调研 https://www.jianshu.com/p/a02af15d3e41 
但是看下来似乎各厂商并不支持“一次加密多个明文”？

|Cryption| 对称加密 | 对称解密 | 非对称加密 | 非对称解密 | 批量加解密 | 字符串or 字节数组? | 其他 |
|---|---|---|---|---|---|---|---|
| [AWS Encryption](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html) | [Java示例代码](https://docs.aws.amazon.com/zh_cn/encryption-sdk/latest/developer-guide/java-example-code.html#java-example-strings) | [Java示例代码](https://docs.aws.amazon.com/zh_cn/encryption-sdk/latest/developer-guide/java-example-code.html#java-example-strings)  |   |    |  能[用多个key加密一份明文](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/examples/java/com/amazonaws/crypto/examples/MultipleCmkEncryptExample.java) ;<br>似乎不能一次加密多个明文 |  byte[]  | 文档太少
|[Aliyun Encryption SDK](https://help.aliyun.com/document_detail/189379.htm?spm=a2c4g.11186623.0.0.ea8a9b75VwOmNX#task-1995115)| [Encrypt API](https://help.aliyun.com/document_detail/28949.htm?spm=a2c4g.11186623.0.0.22305d7a0eqRK9#doc-api-Kms-Encrypt) | [Decrypt (aliyun.com)](https://help.aliyun.com/document_detail/28950.html)  | [AsymmetricEncrypt](https://help.aliyun.com/document_detail/148131.html) <br> 需要指定算法，但是对称加密不用，不知道为啥  | [AsymmetricDecrypt](https://help.aliyun.com/document_detail/148130.html)  | 不支持“一次加密多个明文” | byte[]   | 依赖[阿里云 KMS](https://help.aliyun.com/document_detail/28935.html)  | 
| Azure Key Vault |  |   |   |   |   |    | 
| Google Cloud KMS |  |   |   |   |   |    |

**Comment by seeflood** [comment]
- 关于 status
>status：调用加解密服务的调用结果，可能是 200/300/400/404/... 这种格式

感觉可以通过 grpc 的错误码来描述?

**Comment by kevinten10** [comment]
> 所以这个是密钥的标识? 叫 key_id 如何?

good idea~

**Comment by kevinten10** [comment]
> 感觉可以通过 grpc 的错误码来描述?

我上面写的是用http错误码，需要做成grpc的错误码吗？

**Comment by kevinten10** [comment]
> @kevinten10 hi, 我最近也做了一些调研 https://www.jianshu.com/p/a02af15d3e41
但是看下来似乎各厂商并不支持“一次加密多个明文”？

如果各大云厂商都不支持list格式，那我们就先做单个的？等未来有多个的，再新增一个list的？

**Comment by seeflood** [comment]
> > 感觉可以通过 grpc 的错误码来描述?
> 
> 你的意思是从proto里面提取出来，放到请求的响应状态中吗
> 
> 举一个例子：使用密文再次执行加密操作，应该返回一个成功的响应，但status应!=200。
> 
> 这样使用grpc响应状态码似乎没办法表示？

什么情况会有这种status 呀，因为我看了阿里云加密sdk，没返回这个 status

**Comment by kevinten10** [comment]
我没细看阿里云sdk，是私有云遇到的一种场景。不知道aws等其他sdk上会不会有这样的case，我去看一下。
