### ISSUE TITLE
proposal: Operation bot based on confidence score

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#800]
Since the bot is designed for chinese community, this issue is written in chinese

# 基于信心分的运营机器人
## 要解决的问题
高效推广 good first issue，为社区吸引贡献者

## 方案
![image](https://user-images.githubusercontent.com/26001097/192416290-f8ee9745-3dac-454f-a7d0-a37224810c9e.png)
1. 每个 good first issue 有一个初始"信心分"；信心分的范围是1--9。

Q: 如何标记该 issue 的信心分? 
加个label "confidence/数字"。例如 https://github.com/mosn/layotto/issues/797 有 "confidence/8"，代表信心分是8
![image](https://user-images.githubusercontent.com/26001097/192417718-8206b8f4-ea75-4fd6-89a2-d800adac8e28.png)

Q: 如果 good first issue 没打 label，信心分是多少?
如果 good first issue 没打 label，则视为默认值 5

Q: 信心分解决什么问题?
解决和运营同学的协作问题，见下

2. **运营同学发布大型活动时，可以选择信心分5以上的 good first issue，作为活动"任务"发布。** 或者选择少量 5以下的任务，实验性发布。

3. 每次新增 good first issue 时，由 bot 进行多渠道宣传、推广，发送到各种群聊，然后对 issue 打标

4. bot 定期 review 所有 good first issue，无人认领的 issue 的信心分随着时间衰减

## Bot 详细设计
使用 nodejs 开发。

Q: Bot 是推还是拉模式？
Bot 选择拉模式，这样有很多好处，例如时间可控，例如可重试

Q: Bot 的推广策略
一期可以无脑发到所有群聊
后续可以做一些优化，例如"猜你喜欢"功能，@ 可能感兴趣的人；例如在任务较多的时候，优先推荐信心分高的任务

**Comment by nobodyiam** [comment]
整体机制我觉得是可以的，不过比较模糊的是信心分根据哪些因素来评估？

**Comment by seeflood** [comment]
> 整体机制我觉得是可以的，不过比较模糊的是信心分根据哪些因素来评估？

靠录入 issue 的人主观判断 😄 

假设信心分的衰减策略是：每过2周，信心分下降1
那么录入 issue 的人的判断逻辑：
”如果这个 issue 录入后 2周内没人认领，那就不要在做活动时推广它了“  = 5分
”如果这个 issue 录入后 4周内没人认领，那就不要在做活动时推广它了“  = 6分
”如果这个 issue 录入后 6周内没人认领，那就不要在做活动时推广它了“  = 7分
依次类推

**Comment by seeflood** [comment]
感觉可以在 issue template 里加一些 good first issue模板，例如“组件开发模板”
  
![image](https://user-images.githubusercontent.com/26001097/197169541-dba8083f-2277-46ff-a9d1-c14ebdb5f541.png)

最终实现的效果：maintainer靠模板录入一个issue后，机器人自动推广，自动化运营

**Comment by seeflood** [comment]
进展:
- 新增若干 good first issue 模板，1分钟发布新任务
![image](https://user-images.githubusercontent.com/26001097/199180776-9e247d55-ac12-4001-ac41-fb5f72b5e1d0.png)


- 新增机器人，负责推广
![image](https://user-images.githubusercontent.com/26001097/199180613-f5fea5ba-70a8-4b99-984d-912aad487ff0.png)
