### ISSUE TITLE
Is Layotto doesn't support Windows?

### ISSUE THREAD

**Issue by helbing** [mosn/layotto#801]
### Your question

I didn't find the configuration about building on Windows in Github Action workflows. So, Is Layotto doesn't support Windows? Also future? And why? As far as I know, many developers are still working on Windows and not using WSL2. By the way, I work on macOS.

**Comment by seeflood** [comment]
Unfortunately, no. 
It's because MOSN doesn't support Windows.
But developers can run Layotto with docker
```
docker pull layotto/layotto:latest
```

Similar issue: https://github.com/mosn/layotto/issues/620

**Comment by helbing** [comment]
OK, got it. I will close the issue now.
