### ISSUE TITLE
what's the defference between "go build cmd/layotto/main.go  cmd/layotto/cmd.go" and “make build”

### ISSUE THREAD

**Issue by rayowang** [mosn/layotto#822]
### Your question

Introducing a new pkg and using go build can compile successfully, but using make build fails to compile

### Environment

macos and  linux

### Logs

make build 
which: no go-junit-report in (/opt/rh/devtoolset-7/root/usr/bin:/export/servers/jdk1.6.0_25/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/usr/Arcconf:/home/rayowang/.local/bin:/home/rayowang/bin:/home/rayowang/.istioctl/bin:/home/rayowang/go/go/bin:/home/rayowang/go/bin)
which: no buf in (/opt/rh/devtoolset-7/root/usr/bin:/export/servers/jdk1.6.0_25/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/usr/Arcconf:/home/rayowang/.local/bin:/home/rayowang/bin:/home/rayowang/.istioctl/bin:/home/rayowang/go/go/bin:/home/rayowang/go/bin)
make[1]: Entering directory '/export/rayowang/go/src/layotto'
which: no go-junit-report in (/opt/rh/devtoolset-7/root/usr/bin:/export/servers/jdk1.6.0_25/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/usr/Arcconf:/home/rayowang/.local/bin:/home/rayowang/bin:/home/rayowang/.istioctl/bin:/home/rayowang/go/go/bin:/home/rayowang/go/bin)
which: no buf in (/opt/rh/devtoolset-7/root/usr/bin:/export/servers/jdk1.6.0_25/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/usr/Arcconf:/home/rayowang/.local/bin:/home/rayowang/bin:/home/rayowang/.istioctl/bin:/home/rayowang/go/go/bin:/home/rayowang/go/bin)
===========> Building binary layotto v0.4.0.rc for linux amd64
// mosn.io/layotto/pkg/wasm/runtime/wasmtime
pkg/wasm/runtime/wasmtime/function.go:7:13: undefined: wasmtime.Func
pkg/wasm/runtime/wasmtime/instance.go:31:16: undefined: wasmtime.Store
pkg/wasm/runtime/wasmtime/instance.go:33:17: undefined: wasmtime.AsExtern
pkg/wasm/runtime/wasmtime/instance.go:34:16: undefined: wasmtime.Instance
pkg/wasm/runtime/wasmtime/instance.go:35:16: undefined: wasmtime.Linker
pkg/wasm/runtime/wasmtime/instance.go:45:13: undefined: wasmtime.Memory
pkg/wasm/runtime/wasmtime/instance.go:193:11: undefined: wasmtime.ValType
pkg/wasm/runtime/wasmtime/module.go:13:15: undefined: wasmtime.Module
pkg/wasm/runtime/wasmtime/module.go:19:42: undefined: wasmtime.Module
pkg/wasm/runtime/wasmtime/vm.go:15:10: undefined: wasmtime.Engine
pkg/wasm/runtime/wasmtime/module.go:19:42: too many errors
make[1]: *** [make/golang.mk:52: go.build.linux_amd64.layotto] Error 2
make[1]: Leaving directory '/export/rayowang/go/src/layotto'
make: *** [Makefile:90: build] Error 2

**Comment by seeflood** [comment]
I'm Makefile noob.  @Xunzhuo any idea on it?

**Comment by Xunzhuo** [comment]
I will take a look this later at this day:)

**Comment by Xunzhuo** [comment]
I did not reproduce it:
![Uploading image.png…]()
