### ISSUE TITLE
generate a cli tool for Layotto;  生成 Layotto 命令行工具

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#826]
**What would you like to be added**:
Develop a command-line tool for Layotto.
For example, we can use the command to invoke Layotto API:
```shell
./layotto-cli runtime sayHello '{"service_name":"hello", "name":"hello"}'
```

**How to implement it**:
We can use existing tools to generate all the code, see 
https://github.com/fiorix/protoc-gen-cobra

There are also some fork versions of this tool:
[NathanBaulch/protoc-gen-cobra: Cobra command line tool generator for gRPC clients (github.com)](https://github.com/NathanBaulch/protoc-gen-cobra)
[tetratelabs/protoc-gen-cobra: Cobra command line tool generator for gRPC clients (github.com)](https://github.com/tetratelabs/protoc-gen-cobra)

**Why is this needed**:
Easier to debug

**Comment by seeflood** [comment]
chinese description:
用链接里的工具（或者调研其他工具），自动根据proto文件生成cli 工具。cli 工具可以方便本地开发、debug

**Comment by akkw** [comment]
我来搞这个吧

**Comment by seeflood** [comment]
@akkw ok
要看下具体用哪个工具来生成，我贴的几个fork版好像比原版多一些功能

**Comment by akkw** [comment]
> @akkw ok 要调研下具体用哪个工具来生成，我贴的几个fork版好像比原版多一些功能

ok

**Comment by akkw** [comment]
写在layotto里面还是，新建一个仓库？

**Comment by seeflood** [comment]
> 写在layotto里面还是，新建一个仓库？

@akkw 我理解这个就是开发个脚本，脚本可以写在本仓库，生成的二进制感觉没必要放进仓库，要不放进[release页面](https://github.com/mosn/layotto/releases) ?
<img width="689" alt="image" src="https://user-images.githubusercontent.com/26001097/224468245-358c0ffb-030c-4420-8de6-3e19fd6e2a7b.png">

**Comment by seeflood** [comment]
可以看下这个工具生成的是二进制还是代码。代码的话可以维护一个单独仓库

**Comment by akkw** [comment]
> 可以看下这个工具生成的是二进制还是代码。代码的话可以维护一个单独仓库

我理解会有一些cli相关的代码，这些代码可以编译成一个可执行文件，现在想把cli相关的代码跟layotto代码放在一起，可执行文件可以放在release页面

**Comment by akkw** [comment]
> 可以看下这个工具生成的是二进制还是代码。代码的话可以维护一个单独仓库

我理解会有一些cli相关的代码，这些代码可以编译成一个可执行文件，现在想把cli相关的代码跟layotto代码放在一起，可执行文件可以放在release页面

**Comment by seeflood** [comment]
@akkw 也行

**Comment by Xunzhuo** [comment]
也不一定依赖于代码生成的项目，主要需要去设计一下这个 cli 有哪些功能，可以参考 istioctl

**Comment by Xunzhuo** [comment]
> > 可以看下这个工具生成的是二进制还是代码。代码的话可以维护一个单独仓库
> 
> 
> 
> 我理解会有一些cli相关的代码，这些代码可以编译成一个可执行文件，现在想把cli相关的代码跟layotto代码放在一起，可执行文件可以放在release页面

如何组织代码与release之间的关系 可以参考 envoy gateway

**Comment by akkw** [comment]
使用protoc-gen-cobra生成的cli已经初步完成了。
`./layotto-cli runtime sayHello '{"service_name":"hello", "name":"hello"}'` 已经实现，代码在我的仓库里面
不过感觉这个工具做出来的cli不够友好，在提示、功能、使用方面都有体现，功能受限与proto文件，在使用方面，所有的command都是以接口名平铺的，无法进行分类。
<img width="784" alt="image" src="https://user-images.githubusercontent.com/54854743/224530457-8af34cb0-b80e-4c1b-8de8-86e07803267f.png">
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/54854743/224530488-a4df7c38-c277-43dd-aac1-ff30f6fc96da.png">


现在还有另外一种思路是使用cobra来实现一个，封装laytoot go sdk的能力，看了istioctl感觉它的能力还是很丰富的。所以现在想使用cobra实现个cli，第一版实现对sdk中的api进行分类并实现所有功能 例如file、lock、emali等包括后续的metrics等能力

**Comment by seeflood** [comment]
我想了一下，这个自动生成的cli 和 istioctl 是两类东西：前者是方便开发debug用的，类postman工具；后者是运维工具。后者做起来就很复杂了，需要设计一下，而且后者可能就不需要支持“调 layotto api”的功能

如果要做前者，其实用那个代码生成器就行，至于"在使用方面，所有的command都是以接口名平铺的，无法进行分类。" 这个改下protoc插件的逻辑就行
