### ISSUE TITLE
Generate java-sdk automatically; 自动生成 java-sdk

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#829]
**What would you like to be added**:
Currently our code generator [p6](https://github.com/layotto/protoc-gen-p6) can generate golang-sdk & sidecar API code.
It's time to teach her how to generate java-sdk.

Reference:
https://mosn.io/layotto/#/zh/api_reference/how_to_generate_api_doc
https://github.com/layotto/protoc-gen-p6

**Why is this needed**:
Less work, more happiness

**Comment by LXPWing** [comment]
i want try it

**Comment by seeflood** [comment]
@LXPWing Coool! 
You can read the current p6 code first, and then we can discuss how to implement this feature

**Comment by seeflood** [comment]
There are some blog posts on "how to develop a protoc plugin". Hope they can help:
https://www.hitzhangjie.pro/blog/2017-05-23-protoc%E5%8F%8A%E6%8F%92%E4%BB%B6%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86%E5%88%86%E6%9E%90%E7%B2%BE%E5%8D%8E%E7%89%88/

https://www.jianshu.com/p/31c23353e32e?v=1666972094263

**Comment by zhenjunMa** [comment]
完成proto文件解析，正在编写生成java文件的模板
