### ISSUE TITLE
hope support http api, no just gRPC

### ISSUE THREAD

**Issue by unionhu** [mosn/layotto#832]
we use layotto  sink our  common platform capability，but I found most project use http protocol to provide its capability。
I dont want change  the usage pattern of engineer。

hope layotto support http api

**Comment by seeflood** [comment]
Yes, I think this feature is necessary.

Solution A: 
We can use the https://github.com/grpc-ecosystem/grpc-gateway project to convert http request to gRPC request, which is already implemented in some production environment.

Solution B:
Start a new http server in Layotto
