### ISSUE TITLE
sdk: layotto 为什么要开发 sdk ？sdk 中的功能代码为什么不可以迁移到 server 端？

### ISSUE THREAD

**Issue by canaan-wang** [mosn/layotto#859]
### Your question

Describe your question clearly.

### Environment

- Layotto Version

### Logs

- Paste the logs you see.

**Comment by wenxuwan** [comment]
对于一些熟悉grpc的用户来说，client端直接裸用grpc都可以，但这种方式对于应用开发者是有理解成本的，所以Layotto的sdk提供的更多的是接口定义，让用户编程的时候不需要直接面向裸漏的grpc。

举个简单的例子，假设用户可以往grpc的header里面塞一个字段“rpc-remote-address”该字段用来指定rpc访问的远端目标地址，那么如果没sdk，用户就得知道两件事：字段名和如何塞字段到grpc的header。

但如果有sdk，你可以提供一个函数SetRpcTargetAddress（address string）来直接给用户使用。

**Comment by canaan-wang** [comment]
ok
