### ISSUE TITLE
希望layotto提供高性能的通信交互能力

### ISSUE THREAD

**Issue by unionhu** [mosn/layotto#867]
最近对layotto性能压测，发现layotto未参数优化前，RT、tps、cpu维度数据不太满意
场景描述：
项目：spring boot
资源：业务 app4c 8g；sidecar 4c 2g
通信协议：grpc
压测接口：hello world
压测结果：tps 7000，spring boot cpu 占用90%，sidecar cpu占用30%，rt 增加0.3ms

测试过uds方案，相对上面结果可以增加1000 tps，sidecar减少 0.2cpu，rt减少0.1ms

通过pprof查看，耗损上面，grpc依然是大头，希望能在pb和网络库上面能优化，是否考虑字节的kitex开源的库替代优化

**Comment by seeflood** [comment]
Good idea!
感觉性能优化可以做的:
- layotto 支持 uds
- 换个性能更好的 grpc 库，比如调研下Kitex
cc @zhenjunMa @wenxuwan

**Comment by wenxuwan** [comment]
cc @canaan-wang

**Comment by canaan-wang** [comment]
ok

**Comment by unionhu** [comment]
了解到字节、蚂蚁、api six都实现了redis协议监听
和api six的交流，了解到这种方式rt延时最小，这种方案是否考虑

**Comment by MoonShining** [comment]
> 了解到字节、蚂蚁、api six都实现了redis协议监听 和api six的交流，了解到这种方式rt延时最小，这种方案是否考虑

之前在内部是提出过兼容redis协议的方案的，不过很多人都觉得API不太标准，最终没能说服他们

**Comment by seeflood** [comment]
> 了解到字节、蚂蚁、api six都实现了redis协议监听 和api six的交流，了解到这种方式rt延时最小，这种方案是否考虑

我觉得挺好，不过没找到人做
https://github.com/mosn/mosn/issues/2054

**Comment by wenxuwan** [comment]
@unionhu layotto/Mosn现在开源都没redis协议的代理能力，如果没有流量治理的需求，裸用redis sdk最好了，本身云厂商的缓存产品也都是redis。如果要下沉redis协议的代码里能力的话，还是得Mosn那边支持。。

**Comment by unionhu** [comment]
这两天也在测试kitex，发现cpu能优化很多，但是RT一直不能降下去

**Comment by seeflood** [comment]
@unionhu 看下rt的瓶颈在哪？估计再优化rt的话，需要做 IPC 优化

**Comment by wenxuwan** [comment]
> 

是把mosn里的grpc换成了kitex吗？

**Comment by unionhu** [comment]
> > 
> 
> 是把mosn里的grpc换成了kitex吗？

经过了一些参数调优，rt降低0.04，但是这个不是正式的，压测环境有时不稳定

**Comment by unionhu** [comment]
> IPC 优化

没玩过，要研究一下

**Comment by unionhu** [comment]
> 

没玩过，要研究一下

**Comment by unionhu** [comment]
> @unionhu 看下rt的瓶颈在哪？估计再优化rt的话，需要做 IPC 优化

没玩过IPC，要研究一下

**Comment by unionhu** [comment]
字节的cloudwego+uds方案初步有了结论，redis的get请求RT有0.04～0.08ms的降低，包大小1kb，随着并发的越高，效果约明显
后期会往这个方案走，也期待MOE的架构

**Comment by zhenjunMa** [comment]
@unionhu 具体是怎么搞的呢？应该是用了kitex监听uds还是处理layotto的proto定义的state API么？

**Comment by unionhu** [comment]
自定义的redis api，单独开了一个kitex的服务端监听，kitex本身大部分都兼容gGRPC，它的网络库和编码解码库相对优秀
现在只是在做验证，后期还有很多改造工作

**Comment by seeflood** [comment]
改造的话，可以基于 mosn 的grpcfilter 改一个 kitex filter?

**Comment by wenxuwan** [comment]
> 改造的话，可以基于 mosn 的grpcfilter 改一个 kitex filter?

现在mosn的filter是通过chan转给了layotto的grpc服务，如果基于Mosn的filter做，很可能瓶颈还是在的，我理解定朝现在是直接起了个kitex的服务端来压的，没有Mosn和layotto

**Comment by seeflood** [comment]
@wenxuwan 哦哦明白你意思了。
我忽然想起来，要优化grpc性能的话，最好重新实现下grpcfilter，让grpcfilter 只有编解码逻辑。
否则即使换成kitex还是会走kitex的通信逻辑，很多余，不见得能优化

**Comment by wenxuwan** [comment]
> 

即使换成kitex还是会走kitex的通信逻辑==》应该是还是会走mosn的通信逻辑吧

**Comment by wenxuwan** [comment]
> @wenxuwan 哦哦明白你意思了。 我忽然想起来，要优化grpc性能的话，最好重新实现下grpcfilter，让grpcfilter 只有编解码逻辑。 否则即使换成kitex还是会走kitex的通信逻辑，很多余，不见得能优化

即使换成kitex还是会走kitex的通信逻辑==》应该是还是会走mosn的通信逻辑吧

**Comment by unionhu** [comment]
> > 改造的话，可以基于 mosn 的grpcfilter 改一个 kitex filter?
> 
> 现在mosn的filter是通过chan转给了layotto的grpc服务，如果基于Mosn的filter做，很可能瓶颈还是在的，我理解定朝现在是直接起了个kitex的服务端来压的，没有Mosn和layotto

是直接在layotto工程开了个kitex的服务端

**Comment by unionhu** [comment]
> > 自定义的redis api，单独开了一个kitex的服务端监听，kitex本身大部分都兼容gGRPC，它的网络库和编码解码库相对优秀 现在只是在做验证，后期还有很多改造工作
> 
> layotto要切换到kitex是要对Mosn代码进行修改的，社区会议上一起来同步一下你们当前的做法以及压测的结果吧

可以的

**Comment by wenxuwan** [comment]
> > > 自定义的redis api，单独开了一个kitex的服务端监听，kitex本身大部分都兼容gGRPC，它的网络库和编码解码库相对优秀 现在只是在做验证，后期还有很多改造工作
> > 
> > 
> > layotto要切换到kitex是要对Mosn代码进行修改的，社区会议上一起来同步一下你们当前的做法以及压测的结果吧
> 
> 可以的

好的，下周三我们社区会议，你们有时间的话，可以一起聊一下。我这边也在压测，到时候我们一起对齐一下数据。你们也麻烦分享一下当前的一些尝试，看看后面走什么路线进行优化

**Comment by zhenjunMa** [comment]
目前尝试通过升级gRPC版本解决目前遇到的问题：https://github.com/mosn/layotto/issues/899

**Comment by wenxuwan** [comment]
![image](https://user-images.githubusercontent.com/11661906/233833142-0b2a6207-dabf-4445-89d7-89fe0c6740af.png)

https://redis.io/docs/management/optimization/benchmarks/

**Comment by wenxuwan** [comment]
https://github.com/dapr/dapr/issues/6008

**Comment by seeflood** [comment]
> [dapr/dapr#6008](https://github.com/dapr/dapr/issues/6008)

QUIC 对layotto没意义，他这个是优化 dapr 和 dapr通信用的

**Comment by wenxuwan** [comment]
> > [dapr/dapr#6008](https://github.com/dapr/dapr/issues/6008)
> 
> QUIC 对layotto没意义，他这个是优化 dapr 和 dapr通信用的; layotto 和 layotto 之间通信用的不是基于http的协议，享受不到优化

这个issue的借鉴意义在于能够让grpc支持QUIC协议，https://github.com/grpc/proposal/pull/256

**Comment by seeflood** [comment]
你是想把app 和 sidecar之间的grpc改成 grpc over h3么？emmmm这也没意义，因为不如grpc over UDS

**Comment by wenxuwan** [comment]
> 你是想把app 和 sidecar之间的grpc改成 grpc over h3么？emmmm这也没意义，因为不如grpc over UDS

是的，先观察一下，看grpc基于quic能不能复用当前Mosn的Listener，uds的话得修改Mosn里面的实现

**Comment by zhenjunMa** [comment]
> > [dapr/dapr#6008](https://github.com/dapr/dapr/issues/6008)
> 
> QUIC 对layotto没意义，他这个是优化 dapr 和 dapr通信用的; layotto 和 layotto 之间通信用的不是基于http的协议，享受不到优化

用chatGPT查了下QUIC跟HTTP2的差别：

QUIC和HTTP/2都是用于优化网络性能的协议，但它们的设计和实现方式有很大的不同。

传输层协议：QUIC是基于UDP协议的，而HTTP/2是基于TCP协议的。

握手协议：QUIC使用了0-RTT快速握手协议，可以在第一次握手时就发送数据，而HTTP/2则需要两次握手才能发送数据。

数据流复用：HTTP/2使用帧（frame）实现数据流的复用，而QUIC使用数据包（packet）对数据进行分组和复用。

错误恢复：QUIC可以快速恢复错误，因为它的数据包是独立的，而HTTP/2需要重新建立连接。

加密：QUIC在传输过程中对数据进行加密，而HTTP/2只在传输敏感数据时进行加密。

总之，QUIC相对于HTTP/2具有更快的传输速度、更好的安全性和更好的错误恢复能力。但由于QUIC协议还比较新，目前还没有被广泛支持。

**Comment by wenxuwan** [comment]
尝试让Mosn的listener支持uds， https://github.com/mosn/mosn/pull/2309

**Comment by wenxuwan** [comment]
UNIX和TCP压测结果对比
● CPU方面会有0.2左右的提升
● RT（AVG）上面会有0.1ms左右的提升
● RT（P95和P99）上面会有比较大的提升

![image](https://github.com/mosn/layotto/assets/11661906/74b8abd1-170c-491b-a8f4-bd891f368372)

![image](https://github.com/mosn/layotto/assets/11661906/4e975704-bf82-463a-95ae-c5495100a9c5)

![image](https://github.com/mosn/layotto/assets/11661906/7687f18b-9592-4efe-b85d-044439896d39)

![image](https://github.com/mosn/layotto/assets/11661906/55193346-9c42-4954-9b74-558ec465be5c)

**Comment by seeflood** [comment]
@wenxuwan good job

**Comment by unionhu** [comment]
@wenxuwan 效果满满，点赞
