### ISSUE TITLE
要不要去掉“2票approve才能merge”的限制, 改用k8s风格的 /lgtm /approve

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#882]
要不要去掉“2票approve才能merge”的限制, 改用k8s风格的 /lgtm /approve ？
## k8s风格的 /lgtm /approve 怎么玩？
仓库有很多reviewer（没有仓库的写权限）；
当有新 pr 时，reviewer 可以 /lgtm 投票（会往pr上添加一个 <img width="52" alt="image" src="https://user-images.githubusercontent.com/26001097/222461949-5e2b623f-e3f0-444d-99e1-a8b3379c67ff.png"> label)；
maintainer 可以 /approve 投票(会往仓库上添加一个 <img width="76" alt="image" src="https://user-images.githubusercontent.com/26001097/222462174-7e7eaeab-46ef-4a4d-a855-382ef8e627f6.png"> label )
如果机器人看到一个pr 同时有“lgtm”和"approved"这两个 label，就会自动merge pr（所以本质上还是两票制）
<img width="341" alt="image" src="https://user-images.githubusercontent.com/26001097/222461258-23cfcd3d-383a-4d71-b251-99e1da4a6be2.png">

## 和现在的区别
<img width="350" alt="image" src="https://user-images.githubusercontent.com/26001097/222465313-4326b3c4-1a00-4d9a-972d-36f755a4cf4a.png">

<img width="444" alt="image" src="https://user-images.githubusercontent.com/26001097/222465198-fad0a49c-a86d-410e-82df-8390a75314a9.png">

## pros & cons
这样设计的好处是：有更多的人有权限 review投票（没有仓库写权限，也能投票）；
坏处是：如果 maintainer 偷懒，次次一人投两票（maintainer 可以 /lgtm /approve 一次打两个label），可能会降低代码质量

## 更详细的讨论
https://github.com/mosn/layotto/pull/868#issuecomment-1451464421
![image](https://user-images.githubusercontent.com/26001097/222464362-8481758c-41e1-4b69-82a9-72e6c9d231cd.png)
![image](https://user-images.githubusercontent.com/26001097/222464412-94cb8f00-e374-4f43-8df6-4de35924e628.png)
![image](https://user-images.githubusercontent.com/26001097/222464471-af86e9ee-2fec-4a5f-8220-22ba3737fc80.png)

**Comment by seeflood** [comment]
和 @wenxuwan 商量了下，先把限制关掉了，如果后面觉得不好再开

**Comment by wenxuwan** [comment]
> 

嗯，可以先尝试一下
