### ISSUE TITLE
SOFAStack五周年活动-优秀贡献者评选

### ISSUE THREAD

**Issue by zhenjunMa** [mosn/layotto#893]
# 活动概况
- 主题：SOFAStack 社区开源五周年：Live Long and Prosper
- 关键词：有趣、健康、开放
- 时间：04 月 15 日 12:00
- 地点：北京市朝阳区恒通国际创新园 C6 栋 C work
- 合作伙伴
   - 主办方：SOFAStack 社区
   - 合作伙伴：掘金、思否、开源中国、开源社、InfoQ、活动行、示说网

欢迎感兴趣的同学到现场参与活动。

# 社区评选
本次活动为积极参与 Layotto 项目建设的同学准备了A/B/C三类纪念品，人数为1:2:3，我们按照过去一年（2022年）外部参与者的贡献度进行了排序如下：
1. [seeflood](https://github.com/seeflood)
2. [Xunzhuo](https://github.com/Xunzhuo)
3. [stulzq](https://github.com/stulzq)
4. [rayowang](https://github.com/rayowang)
5. [ZLBer](https://github.com/ZLBer)
6. [LXPWing](https://github.com/LXPWing)

其中 [seeflood](https://github.com/seeflood) 同学因个人原因自愿选择了B类纪念品，因此初步确定纪念品分发如下：
- A类纪念品：
   - [Xunzhuo](https://github.com/Xunzhuo)
- B类纪念品：
   - [seeflood](https://github.com/seeflood)
   - [stulzq](https://github.com/stulzq)
- C类纪念品：
   - [rayowang](https://github.com/rayowang)
   - [ZLBer](https://github.com/ZLBer)
   - [LXPWing](https://github.com/LXPWing)

对上述活动或者人员名单有任何疑问或建议，欢迎直接在下面留言讨论。

**Comment by seeflood** [comment]
Thanks!

**Comment by zhenjunMa** [comment]
人员名单已经确认。
