### ISSUE TITLE
You will define L8, v0.1.0 requirement gathering 由你定义L8,需求征集

### ISSUE THREAD

**Issue by seeflood** [mosn/layotto#90]
## You will define L8, v0.1.0 requirement gathering
Layotto is currently landing inside Alipay, and the future roadmap is still in discussion. We sincerely invite all of you who are interested in service mesh and multi-runtime architecture: What feature do you think should be developed in the v0.1.0 version of Layotto?
You are welcome to put forward your needs and ideas, and you are also welcome to vote on other people’s needs (you can send your vote directly to the comment)
We will choose the features that you(and alipay inner users) need most to implement first, and if necessary, we can also hold a community meeting for everyone to have a discussion~

Requirements that have been collected so far:
| feature | scenario | issue | pr |
|  ----  | ----  | ----  | ----  |
| NoSQL API(such as Hbase) | Users say that there are scenarios where hbase is used by multiple languages, and the routing logic is relatively special, and the open source SDK cannot meet their needs. They ask whether it can be supported by Layotto  |   |   |
| Object storage API(such as OSS in aliyun) | Users say that there are scenarios where Object storage is used by multiple languages. They ask whether it can be supported by Layotto | #98    |   |
|  SQL API(DB Mesh)| Users pass sql to Layotto, Layotto handles the logic of db sharding and shields the implementation layer  |   |   |
| Service registration and discovery API | app performs service registration and discovery through API |   |   |
| Distributed lock API |  | #96   | #100   |
 | Leader election API |  |   |   |
 | Demo of Layotto+istio | Provide a demo showing how Layotto can be integrated with istio,so that a single sidecar can be used as both the data plane of the service mesh and the application runtime |   |   |
 | mini project based on Layotto | Use Layotto to implement a mini project, similar to istio's bookshop demo project, to demonstrate the usage of Layotto and to run integration tests |   |   |
 | java sdk |  | #79   |   |

chinese version:
## 由你定义L8,v0.1.0需求征集
Layotto目前在蚂蚁内部落地中，下一步的演进方向还在摸索。我们诚邀各位对service mesh和multi-runtime架构感兴趣的同学，你觉得Layotto的v0.1.0版应该做哪些需求？
欢迎提出你的需求和idea，也欢迎对其他人提的需求投票哈（投票直接发到comment里即可）
我们会选择大家最有需求的功能优先实现，如有需要也可以开个社区会议大家聊一聊~

目前已经征集到的需求：
| feature | scenario | issue | pr |
|  ----  | ----  | ----  | ----  |
| NoSQL API(比如Hbase) | 用户反馈有多语言调用hbase的场景，而且路由逻辑比较特殊、开源sdk不能满足需求，询问能否通过Layotto支持 |   |   |
| 对象存储API（比如OSS）| 用户反馈有多语言调用OSS的场景，能否通过Layotto支持 | #98  |   |
|  SQL API (DB Mesh)| 用户传sql给Layotto,Layotto处理分库分表逻辑，屏蔽实现层 |   |   |
| 服务注册发现API | app通过API进行服务注册、发现 |   |   |
| 分布式锁API |  | #96   | #100   |
 | Leader选举API |  |   |   |
 | 集成layotto和istio的demo | 提供Layotto和istio整合的demo，演示同一个sidecar既能作为service mesh的data plane又能作为应用运行时 |   |   |
 | mini project based on Layotto | 使用Layotto实现一个迷你项目，类似于istio的bookshop演示项目，用于演示Layotto的用法、用于跑集成测试 |   |   |
 | java sdk |  | #79   |   |

**Comment by alpha-baby** [comment]
对象存储API（比如OSS）我觉得还是比较有意义的，我以前也想过支持对象存储的api，作为开发者我以前也困惑过，我会使用例如阿里云的对象存储，但是切换其他云厂商后又要学习一遍。

**Comment by ujjboy** [comment]
对象存储API +1
服务注册发现API  +1

**Comment by taoyuanyuan** [comment]
集成layotto和istio的demo  +1

**Comment by MoonShining** [comment]
sql api+1

layotto作为runtime， 如果对现有的标准协议，或者事实上的标准协议提供支持， 可以将很大的复杂度下沉。

比如做db从单库到分片的路由，同时又对应用无感

**Comment by seeflood** [comment]
集成layotto和istio的demo +1
这个方便我做marketing 去推荐给国外社区哈哈

**Comment by nejisama** [comment]
动态配置/组件加载的能力吧，这个也是集成istio的基础

**Comment by seeflood** [comment]
> 动态配置/组件加载的能力吧，这个也是集成istio的基础

@nejisama 现在想集成istio的话，还差哪些功能呀，是只要完成动态配置/组件加载就可以了么

**Comment by alpha-baby** [comment]
> > 动态配置/组件加载的能力吧，这个也是集成istio的基础
> 
> @nejisama 现在想集成istio的话，还差哪些功能呀，是只要完成动态配置/组件加载就可以接Istio了么

动态配置/组件加载的能力，我理解就是dapr项目中的Operator程序的功能

**Comment by nejisama** [comment]
> > > 动态配置/组件加载的能力吧，这个也是集成istio的基础
> > 
> > 
> > @nejisama 现在想集成istio的话，还差哪些功能呀，是只要完成动态配置/组件加载就可以接Istio了么
> 
> 动态配置/组件加载的能力，我理解就是dapr项目中的Operator程序的功能

是的，dapr中的operator就是一个旁路的动态插拔能力，目前layotto 应该还没有支持动态配置的能力，然后就是有了动态能力以后怎么触发的问题，也不一定就是要基于operator的做法 @seeflood
