### ISSUE TITLE
Discussion: 自建各种 Component 

### ISSUE THREAD

**Issue by zhenjunMa** [mosn/layotto#902]
### 背景
目前 Layotto 依赖了一些 dapr 的组件，由于两个社区的开发节奏不同，我们发现兼容这些组件变得越来越困难，比如双方对于 Go 版本的诉求，因此是否要考虑完全自建这些组件？

自建的优势：
- 自主可控

自建的劣势：
- 需要做一部分重复的工作

*** 
### background
At present, Layotto relies on some dapr components. Due to the different development plan of the two communities, we find that it is becoming more and more difficult to be compatible with these components, such as the Go version. Therefore, should we consider building these components entirely by ourselves?

Advantages of self-built:
- Autonomous and controllable

Disadvantages of self-built:
- Need to do some repetitive work

**Comment by seeflood** [comment]
不可行的，组件太多了维护不过来
如果只是为了解决蚂蚁的问题、不想和蚂蚁代码依赖的go版本有冲突，可以把layotto 做模块化解耦，分离开高版本模块和低版本模块，确保蚂蚁代码只依赖低版本的模块

**Comment by wenxuwan** [comment]
拆分一下也可以，把component的依赖从Layotto的主仓库踢出去，放到一个第三方仓库

**Comment by seeflood** [comment]
不一定要拆成多仓库，可以拆成多个 go module。
layotto 的主module 不需要依赖dapr的东西；可以新起一个 main module ，依赖 layotto module 和 dapr component module ，负责做启动
>dapr的component在做改动的时候因为默认只有它自己会import，会做很多不兼容改动，如果时间长了，layotto需要适配的东西就很多了。

具体哪些要适配呢？感觉 component 包没啥要适配的啊

**Comment by seeflood** [comment]
别自己重写组件
1. 组件太多了维护不过来
2. 以现在的人力（对比下dapr的人力），结果必然是功能大幅缩水，比dapr 少很多很多组件的支持，和dapr相比完全失去竞争力。结果就是花很大功夫，把自己产品的功能做小了，负 ROI

通过模块解耦能解决问题的

**Comment by wenxuwan** [comment]
> 不一定要拆成多仓库，可以拆成多个 go module。 layotto 的主module 不需要依赖dapr的东西；可以新起一个 main module ，依赖 layotto runtime module 和 dapr component module ，负责做启动。 蚂蚁内部只依赖 layotto runtime module，不依赖 main module、dapr component module，这样完全不需要担心依赖冲突
> 
> > dapr的component在做改动的时候因为默认只有它自己会import，会做很多不兼容改动，如果时间长了，layotto需要适配的东西就很多了。
> 
> 具体哪些要适配呢？感觉 component 包没啥要适配的啊

升级一下看看，现在版本太低了，肯定要升级，你本地升一下看看有哪些报错，不多的话就拆一下 😊

**Comment by seeflood** [comment]
你说的是类似 https://github.com/mosn/layotto/pull/897/files 这里的报错?
这很好解决，按照上面的描述拆分模块就行
>不一定要拆成多仓库，可以拆成多个 go module。
layotto 的主module 不需要依赖dapr的东西；可以新起一个 main module ，依赖 layotto runtime module 和 dapr component module ，负责做启动。
蚂蚁内部只依赖 layotto runtime module，不依赖 main module、dapr component module，这样完全不需要担心依赖冲突

**Comment by wenxuwan** [comment]
> 你说的是类似 [#897 (files)](https://github.com/mosn/layotto/pull/897/files) 这里的报错? 这很好解决，按照上面的描述拆分模块就行，让 runtime module 不依赖dapr，真的不难。
> 
> > 不一定要拆成多仓库，可以拆成多个 go module。
> > layotto 的主module 不需要依赖dapr的东西；可以新起一个 main module ，依赖 layotto runtime module 和 dapr component module ，负责做启动。
> > 蚂蚁内部只依赖 layotto runtime module，不依赖 main module、dapr component module，这样完全不需要担心依赖冲突

我是升级grpc的过程中发现需要升级component，然后升级component又出现了一堆报错，没仔细看现在有哪些冲突，我觉的把runtime拆出来也可以的

**Comment by zhenjunMa** [comment]
1. 希望通过新版本gRPC解决压测发现的性能问题
2. dapr Component 跟新版gRPC不兼容
