### ISSUE TITLE
Some suggestion of go-sdk and components

### ISSUE THREAD

**Issue by cyb0225** [mosn/layotto#904]
After simple use of go-sdk, I have found the following "problems".
reference to #213

# 1. The hello function haven't support `Name` 
In the hello components, the `Hello` function allows client to send `Name` field. And the proto file supports this field as well.
But in go-sdk, it only allows `ServiceName` which is used to get `hello` instance but not the `Name` field.

**The hello components**
https://github.com/mosn/layotto/blob/6fd80a081074b4a0847b64954539418910a47bbf/components/hello/helloworld/helloworld.go#L66-L74
**The grpc server**
https://github.com/mosn/layotto/blob/6fd80a081074b4a0847b64954539418910a47bbf/spec/proto/runtime/v1/runtime_grpc.pb.go#L89-L96

**The grpc request struct**
https://github.com/mosn/layotto/blob/6fd80a081074b4a0847b64954539418910a47bbf/spec/proto/runtime/v1/runtime.pb.go#L1671-L1682

**The go-sdk request struct**
https://github.com/mosn/layotto/blob/6fd80a081074b4a0847b64954539418910a47bbf/sdk/go-sdk/client/hello.go#L25-L42

**The useage of `go-sdk` and  `row grpc`.**
```go

// with go-sdk. I can only set the ServiceName field, but not the Name field.
func main() {
	cli, err := client.NewClient()
	if err != nil {
		log.Fatal(err)
	}

	defer cli.Close()

	//say hello
	res, err := cli.SayHello(context.Background(), &client.SayHelloRequest{
		ServiceName: "hellowrld",
	})
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(res.Hello)
}

/*
output: greeting
*/


// with grpc connection
func main() {
	conn, err := grpc.Dial("127.0.0.1:34904", grpc.WithInsecure())
	if err != nil {
		fmt.Printf("conn build failed,err:%+v", err)
		panic(err)
	}
	c := runtimev1pb.NewRuntimeClient(conn)
	req := &runtimev1pb.SayHelloRequest{
		ServiceName: "helloworld",
		Name:        "yeebing",  
	}
	
	hello, err := c.SayHello(context.Background(), req)
	if err != nil {
		log.Fatal(err)
	}
	
	fmt.Println(hello.Hello)
}

/*
output: greeting, yeebing
*/

```

# 2. Some interfaces are not yet supported by the Go SDK.
For example, go-sdk haven't support `file` module. (I'm not sure if it's because of not familiar enough with the program, but I couldn't find the corresponding file interface in the `go-sdk`, and the demos also use gRPC connections to operate the `file interface`.)

So, if I need to use such interface, I need to **init a row grpc connection to layotto.** 
https://github.com/mosn/layotto/blob/6fd80a081074b4a0847b64954539418910a47bbf/demo/file/client.go#L66-L76

If I need to use go-sdk with the same `row grpc conn`, I can use thit function to get a wrap client.
https://github.com/mosn/layotto/blob/6fd80a081074b4a0847b64954539418910a47bbf/sdk/go-sdk/client/client_generated.go#L57-L78

I think that why not have the `go-sdk` provide a function that returns the `RuntimeClient`.
Here is a function for a proposed solution, along with a demo showcasing its usage.
```go
// the new function
func (g *GRPCClient)GetRuntimeClient() v1.RuntimeClient {
	conn := g.connection
	c := v1.NewRuntimeClient(conn)
	return c
}

```

useage demo， which  is modifying the following function.
https://github.com/mosn/layotto/blob/6fd80a081074b4a0847b64954539418910a47bbf/demo/file/client.go#L26-L62
```go
func TestClientGet(fileName string) {
	cli, err := client.NewClient()
	if err != nil {
		fmt.Printf("conn build failed,err:%+v", err)
		panic(err)
	}

	c := cli.GetRuntimeClient()
	// Make a request to get a file
	req := &runtimev1pb.GetFileRequest{StoreName: storeName, Name: fileName}
	res, err := c.GetFile(context.Background(), req)
	if err != nil {
		fmt.Printf("get file error: %+v", err)
		panic(err)
	}

	// Receive data from the server and store in pic
	pic := make([]byte, 0)
	for {
		resp, err := res.Recv()
		if err != nil {
			if err.Error() != "EOF" {
				fmt.Println("recv file failed")
				panic(err)
			}
			break
		}
		pic = append(pic, resp.Data...)
	}

	// Print the result of the GetFile request
	fmt.Println("GetFile successfully. Result:")
	fmt.Println(string(pic))
}

```
I added the function to the `go-sdk` and modified some parameters in `demo/file/client.go` to test the local type, which resulted in the correct output.
```shell
cyb@DESKTOP-6AOA5PJ:~/project/ospp/layotto/demo/file$ ./client put hello world
[./client put hello world]
cyb@DESKTOP-6AOA5PJ:~/project/ospp/layotto/demo/file$ ./client get hello
[./client get hello]
GetFile successfully. Result:
world
cyb@DESKTOP-6AOA5PJ:~/project/ospp/layotto/demo/file$ ./client get-cli hello
[./client get-cli hello]
runtime client initializing for: 127.0.0.1:34904
GetFile successfully. Result:
world
```

So that, users can use default configurations to init a gRPC connections with go-sdk. Additionally, obtaining the corresponding gRPC client can provide certain expandability in cases where go-sdk updates are not available yet.

These two are very small problems, I can't weigh whether it is necessary to modify.

**Comment by wenxuwan** [comment]
You are right. In theory, golang-sdk should shield the user from the pb changes of the underlying grpc, including the changes of the grpc client you mentioned. To give a simple example, if you use the grpc client directly. Once the definition of Layotto's pb file changes, users need to modify their own code to adapt to the changes in layotto (these adaptations should be done by golang sdk), so your idea is right, you can use golang -sdk for further abstraction and encapsulation.

**Comment by cyb0225** [comment]
> You are right. In theory, golang-sdk should shield the user from the pb changes of the underlying grpc, including the changes of the grpc client you mentioned. To give a simple example, if you use the grpc client directly. Once the definition of Layotto's pb file changes, users need to modify their own code to adapt to the changes in layotto (these adaptations should be done by golang sdk), so your idea is right, you can use golang -sdk for further abstraction and encapsulation.

Yes. I have found that layotto have packaged the runtimeAPI, but still use the request and response struct from grpc. And dapr write a new struct in go-sdk, which helps users save the complexity of grpc. I think it's a great way to update our go-sdk.

https://github.com/mosn/layotto/blob/6fd80a081074b4a0847b64954539418910a47bbf/sdk/go-sdk/client/client.go#L107-L114

https://github.com/dapr/go-sdk/blob/main/client/client.go#L62-L191

**Comment by cyb0225** [comment]
Should I solve the two tiny problems, I think he is insensitive to users

**Comment by wenxuwan** [comment]
> Should I solve the two tiny problems, I think he is insensitive to users

Any improvements you think will help the project are welcome. 😊
