### ISSUE TITLE
undefined: syscall.GetsockoptIPv6Mreq

### ISSUE THREAD

**Issue by huayangchan** [mosn/layotto#914]
下载layotto-0.5.0源码，在本地windows系统编译启动时，报一些函数和变量未定义错误，如undefined: syscall.GetsockoptIPv6Mreq，这应该是unix系统才调用的函数，为甚么在Windows系统运行会调unix系统相关的函数，还说源码只能在unix系统上便已启动?

**Comment by wenxuwan** [comment]
layotto是基于Mosn为底座的，用到了linux的系统函数，所以不支持windows上的编译。可以参考 #801

**Comment by seeflood** [comment]
windows developers can run Layotto with docker

docker pull layotto/layotto:latest
