### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by nobodyiam** [mosn/layotto#92]
As an open source project, we need to attach a proper license to this project.

Typically this is done by adding a LICENSE file in the root directory and attach the licensen declaration in every files.

I suggest we apply [Apache2](https://www.apache.org/licenses/LICENSE-2.0) to the project.

How do you think?

**Comment by zhenjunMa** [comment]
yeah,  Apache2.0 license is really a good choice,  i will add it to our project.
