### ISSUE TITLE
为 configure API 开发nacos组件 

### ISSUE THREAD

**Issue by wenxuwan** [mosn/layotto#921]
**What would you like to be added**:

为 configure API 提供 [nacos](https://github.com/alibaba/nacos)  支持

**Reference(FIXME)**:

Here are some resources to help you work on this issue.

API quickstart doc: 

可以参考  https://mosn.io/layotto/#/zh/start/configuration/start-apollo 

API definition(the `.proto` file):

当前配置的pb定义在：https://github.com/mosn/layotto/blob/main/spec/proto/runtime/v1/runtime.proto#L22

Component development guide: https://mosn.io/layotto/#/en/development/developing-component

Component development guide(in chinese): https://mosn.io/layotto/#/zh/development/developing-component

An example pull request to develop a new component:  https://github.com/mosn/layotto/pull/133

**Why is this needed**:

让layotto支持nacos

We need more components to make this API useful

**Comment by cyb0225** [comment]
I can help to add, could you assign it to me?

**Comment by seeflood** [comment]
@cyb0225 Sure, thanks!
Could you briefly describe your design before coding?  We can start a discussion on that

**Comment by cyb0225** [comment]
> @cyb0225 Sure, thanks! Could you briefly describe your design before coding? We can start a discussion on that

Sure, I will show you my code design later.  I am viewing the code of apollo component  and found [the code](https://github.com/mosn/layotto/blob/f90a3380b63b78b20672580e201e87118c906134/components/configstores/apollo/configstore.go#L161-L165) implementation dosen't match the comments. It is used as baseurl, so I think the `open_api_address` is required.

**Comment by cyb0225** [comment]
I think it is a better choice to directly use the official [go-sdk](https://github.com/nacos-group/nacos-sdk-go). Nacos needs a client config which is used to set the way to operate on config, and a slice of serice config to connect to the nacos instance.

```go
type ClientConfig struct {
	TimeoutMs            uint64                   // timeout for requesting Nacos server, default value is 10000ms
	ListenInterval       uint64                   // Deprecated
	BeatInterval         int64                    // the time interval for sending beat to server,default value is 5000ms
	NamespaceId          string                   // the namespaceId of Nacos.When namespace is public, fill in the blank string here.
	AppName              string                   // the appName
	AppKey               string                   // the client identity information
	Endpoint             string                   // the endpoint for get Nacos server addresses
	RegionId             string                   // the regionId for kms
	AccessKey            string                   // the AccessKey for kms
	SecretKey            string                   // the SecretKey for kms
	OpenKMS              bool                     // it's to open kms,default is false. https://help.aliyun.com/product/28933.html
	CacheDir             string                   // the directory for persist nacos service info,default value is current path
	DisableUseSnapShot   bool                     // It's a switch, default is false, means that when get remote config fail, use local cache file instead
	UpdateThreadNum      int                      // the number of goroutine for update nacos service info,default value is 20
	NotLoadCacheAtStart  bool                     // not to load persistent nacos service info in CacheDir at start time
	UpdateCacheWhenEmpty bool                     // update cache when get empty service instance from server
	Username             string                   // the username for nacos auth
	Password             string                   // the password for nacos auth
	LogDir               string                   // the directory for log, default is current path
	LogLevel             string                   // the level of log, it's must be debug,info,warn,error, default value is info
	ContextPath          string                   // the nacos server contextpath
	AppendToStdout       bool                     // if append log to stdout
	LogSampling          *ClientLogSamplingConfig // the sampling config of log
	LogRollingConfig     *ClientLogRollingConfig  // log rolling config
	TLSCfg               TLSConfig                // tls Config
}

type ServerConfig struct {
	Scheme      string // the nacos server scheme,default=http,this is not required in 2.0
	ContextPath string // the nacos server contextpath,default=/nacos,this is not required in 2.0
	IpAddr      string // the nacos server address
	Port        uint64 // nacos server port
	GrpcPort    uint64 // nacos server grpc port, default=server port + 1000, this is not required
}
```
There are too many fields to fill in here, especially `ClientConfig`, I think we only need to expose some necessary fields to users, and choose default values ​​for others, what do you think? 

On the other hand, nacos client supports two types of connection methods: one is the connection method for users who deploy Nacos locally, and the other is the paid service provided by [Alibaba Cloud acm](https://help.aliyun.com/document_detail/130146.html). They have mixed all configuration fields here. I think we can use a simple switch field or two structures to provide configuration for the two sets of clients for users.

**Comment by cyb0225** [comment]
```go
// layotto needed
// ====================================================
// GetRequest is the object describing a get configuration request
type GetRequest struct {
	AppId    string
	Group    string
	Label    string
	Keys     []string
	Metadata map[string]string
}

// ConfigurationItem represents a configuration item with key, content and other information.
type ConfigurationItem struct {
	Key      string
	Content  string
	Group    string
	Label    string
	Tags     map[string]string
	Metadata map[string]string
}



// nacos supported
// ====================================================
type ConfigParam struct {
	DataId           string `param:"dataId"`  //required
	Group            string `param:"group"`   //required
	Content          string `param:"content"` //required
	Tag              string `param:"tag"`
	AppName          string `param:"appName"`
	BetaIps          string `param:"betaIps"`
	CasMd5           string `param:"casMd5"`
	Type             string `param:"type"`
	EncryptedDataKey string `param:"encryptedDataKey"`
	OnChange         func(namespace, group, dataId, data string)
}
```

Most of the fields are kept consistent with Nacos, but there are still several fields that need to be made compatible by us.

1. nacos dose not have support `Label` field. 
I think we can use the `Type` field to stroe the `Label` message. 
https://nacos.io/zh-cn/docs/open-api.html

2. nacos dose not have support AppId

nacos has a filed called `[Namespace](https://nacos.io/zh-cn/docs/architecture.html)`, it more likes the namespace in k8s. But I think it's not suitable to use it here. The namespace is configured when the program initializes the client, and it is not convenient to modify it later. 
```go
	cc := *constant.NewClientConfig(
		constant.WithNamespaceId(""),
		constant.WithTimeoutMs(5000),
		constant.WithNotLoadCacheAtStart(true),
		constant.WithLogDir("/tmp/nacos/log"),
		constant.WithCacheDir("/tmp/nacos/cache"),
		constant.WithLogLevel("debug"),
	)
```

Using `AppName` may be more suitable.
![](https://kamaoj-1312361098.cos.ap-guangzhou.myqcloud.com/%E6%88%AA%E5%9B%BE%202023-05-14%2021-41-56.png)

3. nacos dose not have key

We can use `DataId` to implement it.

**Comment by cyb0225** [comment]
nacos go sdk has already support the following methods  which can help me to implement layotto config interface easily.

```go
type IConfigClient interface {
	// GetConfig use to get config from nacos server
	// dataId  require
	// group   require
	// tenant ==>nacos.namespace optional
	GetConfig(param vo.ConfigParam) (string, error)

	// PublishConfig use to publish config to nacos server
	// dataId  require
	// group   require
	// content require
	// tenant ==>nacos.namespace optional
	PublishConfig(param vo.ConfigParam) (bool, error)

	// DeleteConfig use to delete config
	// dataId  require
	// group   require
	// tenant ==>nacos.namespace optional
	DeleteConfig(param vo.ConfigParam) (bool, error)

	// ListenConfig use to listen config change,it will callback OnChange() when config change
	// dataId  require
	// group   require
	// onchange require
	// tenant ==>nacos.namespace optional
	ListenConfig(params vo.ConfigParam) (err error)

	//CancelListenConfig use to cancel listen config change
	// dataId  require
	// group   require
	// tenant ==>nacos.namespace optional
	CancelListenConfig(params vo.ConfigParam) (err error)

	// SearchConfig use to search nacos config
	// search  require search=accurate--精确搜索  search=blur--模糊搜索
	// group   option
	// dataId  option
	// tenant ==>nacos.namespace optional
	// pageNo  option,default is 1
	// pageSize option,default is 10
	SearchConfig(param vo.SearchConfigParam) (*model.ConfigPage, error)

	// CloseClient Close the GRPC client
	CloseClient()
}
```
we can use `GetConfig` to get the config value.
use `ListenConfig` and `CancelListenConfig` to implement  `Subscribe` and `StopSubscribe`. 

However, I found that we should use `SearchConfig` to get a list of configs.  
It provides two search modes, blur search and accurate search. His blur search cannot use prefixes, but returns keys that match all characters. Therefore, if using string prefixes to implement the `label` field, we may need to first fuzzy search them out and then filter them in the program.
And now It only support search with `dataid` and `group`, without `tags`.

**Comment by wenxuwan** [comment]
> I think it is a better choice to directly use the official [go-sdk](https://github.com/nacos-group/nacos-sdk-go). Nacos needs a client config which is used to set the way to operate on config, and a slice of serice config to connect to the nacos instance.
> 
> ```go
> type ClientConfig struct {
> 	TimeoutMs            uint64                   // timeout for requesting Nacos server, default value is 10000ms
> 	ListenInterval       uint64                   // Deprecated
> 	BeatInterval         int64                    // the time interval for sending beat to server,default value is 5000ms
> 	NamespaceId          string                   // the namespaceId of Nacos.When namespace is public, fill in the blank string here.
> 	AppName              string                   // the appName
> 	AppKey               string                   // the client identity information
> 	Endpoint             string                   // the endpoint for get Nacos server addresses
> 	RegionId             string                   // the regionId for kms
> 	AccessKey            string                   // the AccessKey for kms
> 	SecretKey            string                   // the SecretKey for kms
> 	OpenKMS              bool                     // it's to open kms,default is false. https://help.aliyun.com/product/28933.html
> 	CacheDir             string                   // the directory for persist nacos service info,default value is current path
> 	DisableUseSnapShot   bool                     // It's a switch, default is false, means that when get remote config fail, use local cache file instead
> 	UpdateThreadNum      int                      // the number of goroutine for update nacos service info,default value is 20
> 	NotLoadCacheAtStart  bool                     // not to load persistent nacos service info in CacheDir at start time
> 	UpdateCacheWhenEmpty bool                     // update cache when get empty service instance from server
> 	Username             string                   // the username for nacos auth
> 	Password             string                   // the password for nacos auth
> 	LogDir               string                   // the directory for log, default is current path
> 	LogLevel             string                   // the level of log, it's must be debug,info,warn,error, default value is info
> 	ContextPath          string                   // the nacos server contextpath
> 	AppendToStdout       bool                     // if append log to stdout
> 	LogSampling          *ClientLogSamplingConfig // the sampling config of log
> 	LogRollingConfig     *ClientLogRollingConfig  // log rolling config
> 	TLSCfg               TLSConfig                // tls Config
> }
> 
> type ServerConfig struct {
> 	Scheme      string // the nacos server scheme,default=http,this is not required in 2.0
> 	ContextPath string // the nacos server contextpath,default=/nacos,this is not required in 2.0
> 	IpAddr      string // the nacos server address
> 	Port        uint64 // nacos server port
> 	GrpcPort    uint64 // nacos server grpc port, default=server port + 1000, this is not required
> }
> ```
> 
> There are too many fields to fill in here, especially `ClientConfig`, I think we only need to expose some necessary fields to users, and choose default values ​​for others, what do you think?
> 
> On the other hand, nacos client supports two types of connection methods: one is the connection method for users who deploy Nacos locally, and the other is the paid service provided by [Alibaba Cloud acm](https://help.aliyun.com/document_detail/130146.html). They have mixed all configuration fields here. I think we can use a simple switch field or two structures to provide configuration for the two sets of clients for users.

If the user wants to switch from the local mode to the remote mode, the configuration file also needs to be changed, and we do not need to provide a switch for mode switching.

Regarding the configuration fields, you can abstract the necessary parameters, and use default values for others. Then provide metadata for expansion，eg. https://github.com/mosn/layotto/blob/main/configs/config_apollo.json#L43

**Comment by wenxuwan** [comment]
> ```go
> SearchConfig
> ```

I don't understand what you mean, what kind of scene do you want to correspond to the interface of Layotto for the fuzzy matching here?

**Comment by cyb0225** [comment]
> > I think it is a better choice to directly use the official [go-sdk](https://github.com/nacos-group/nacos-sdk-go). Nacos needs a client config which is used to set the way to operate on config, and a slice of serice config to connect to the nacos instance.
> > ```go
> > type ClientConfig struct {
> > 	TimeoutMs            uint64                   // timeout for requesting Nacos server, default value is 10000ms
> > 	ListenInterval       uint64                   // Deprecated
> > 	BeatInterval         int64                    // the time interval for sending beat to server,default value is 5000ms
> > 	NamespaceId          string                   // the namespaceId of Nacos.When namespace is public, fill in the blank string here.
> > 	AppName              string                   // the appName
> > 	AppKey               string                   // the client identity information
> > 	Endpoint             string                   // the endpoint for get Nacos server addresses
> > 	RegionId             string                   // the regionId for kms
> > 	AccessKey            string                   // the AccessKey for kms
> > 	SecretKey            string                   // the SecretKey for kms
> > 	OpenKMS              bool                     // it's to open kms,default is false. https://help.aliyun.com/product/28933.html
> > 	CacheDir             string                   // the directory for persist nacos service info,default value is current path
> > 	DisableUseSnapShot   bool                     // It's a switch, default is false, means that when get remote config fail, use local cache file instead
> > 	UpdateThreadNum      int                      // the number of goroutine for update nacos service info,default value is 20
> > 	NotLoadCacheAtStart  bool                     // not to load persistent nacos service info in CacheDir at start time
> > 	UpdateCacheWhenEmpty bool                     // update cache when get empty service instance from server
> > 	Username             string                   // the username for nacos auth
> > 	Password             string                   // the password for nacos auth
> > 	LogDir               string                   // the directory for log, default is current path
> > 	LogLevel             string                   // the level of log, it's must be debug,info,warn,error, default value is info
> > 	ContextPath          string                   // the nacos server contextpath
> > 	AppendToStdout       bool                     // if append log to stdout
> > 	LogSampling          *ClientLogSamplingConfig // the sampling config of log
> > 	LogRollingConfig     *ClientLogRollingConfig  // log rolling config
> > 	TLSCfg               TLSConfig                // tls Config
> > }
> > 
> > type ServerConfig struct {
> > 	Scheme      string // the nacos server scheme,default=http,this is not required in 2.0
> > 	ContextPath string // the nacos server contextpath,default=/nacos,this is not required in 2.0
> > 	IpAddr      string // the nacos server address
> > 	Port        uint64 // nacos server port
> > 	GrpcPort    uint64 // nacos server grpc port, default=server port + 1000, this is not required
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There are too many fields to fill in here, especially `ClientConfig`, I think we only need to expose some necessary fields to users, and choose default values ​​for others, what do you think?
> > On the other hand, nacos client supports two types of connection methods: one is the connection method for users who deploy Nacos locally, and the other is the paid service provided by [Alibaba Cloud acm](https://help.aliyun.com/document_detail/130146.html). They have mixed all configuration fields here. I think we can use a simple switch field or two structures to provide configuration for the two sets of clients for users.
> 
> If the user wants to switch from the local mode to the remote mode, the configuration file also needs to be changed, and we do not need to provide a switch for mode switching.
> 
> Regarding the configuration fields, you can abstract the necessary parameters, and use default values for others. Then provide metadata for expansion，eg. https://github.com/mosn/layotto/blob/main/configs/config_apollo.json#L43

ok

**Comment by cyb0225** [comment]
> > ```go
> > SearchConfig
> > ```
> 
> I don't understand what you mean, what kind of scene do you want to correspond to the interface of Layotto for the fuzzy matching here?

我英文不是特别好, 表述起来有点歧义, 就直接用中文了.
这里是因为 nacos go-sdk 提供的 getconfig 接口是没办法按照分组获取批量数据的, 所以需要使用他提供的 search 函数去搜索 group. 这里搜索 group 是可以使用他的等值比较.

我看 config 接口还有一个 label 字段, 这个 nacos 也是没有的, 我感觉就要用字符串拼接来实现了. 然后 nacos 也是没有支持前缀查询的, 要实现的话要用他 search 接口的模糊匹配先查出来, 在本地再过滤一下.

**Comment by wenxuwan** [comment]
@cyb0225 这个没什么问题的话，有时间可以写起来了

**Comment by cyb0225** [comment]
> > 
> 
> 明白了，getconfig的按照组获取和search里面制定group应该是一样的吧？ label不支持的话可以不做支持，前缀查询当前的接口定义里面应该没有前缀这个字段。不需要关心

对的, 使用 search 实现 Get 接口. 
后面没太理解, 我看到 Get 接口的请求参数是需要传递这些信息的. 
```go
type GetRequest struct {
	AppId    string
	Group    string
	Label    string
	Keys     []string
	Metadata map[string]string
}
```
然后前缀查询的话不是给这个component Get 接口写的, 是想使用类似前缀查询的操作, 实现配置的 label 字段. 我看 etcd 实现 component 的时候是这么做的.

```go
func (c *EtcdV3ConfigStore) Get(ctx context.Context, req *configstores.GetRequest) ([]*configstores.ConfigurationItem, error) {
	targetString := []string{req.AppId, "*", "*", "*"}
	//TODO: the imp read all keys under app, then do match operation, should change later.
	keyValues, err := c.client.Get(ctx, "/"+req.AppId, clientv3.WithPrefix())
	res := make([]*configstores.ConfigurationItem, 0)
	if err != nil {
		log.DefaultLogger.Errorf("fail get all group key-value,err: %+v", err)
		return nil, err
	}
	targetString[configstores.Group] = req.Group
	targetString[configstores.Label] = req.Label
	if len(req.Keys) == 0 {
		return c.GetItemsFromAllKeys(keyValues.Kvs, targetString), nil
	}
	for _, key := range req.Keys {
		targetString[configstores.Key] = key
		res = append(res, c.GetItemsFromAllKeys(keyValues.Kvs, targetString)...)
	}
	trace.SetExtraComponentInfo(ctx, fmt.Sprintf("method: %+v, store: %+v", "Get", "etcd"))
	return res, nil
}
```

> @cyb0225 这个没什么问题的话，有时间可以写起来了

关于 tag 的支持我需要再研究一下, 他这个很奇怪, 可视化界面是支持 tag 创建和 tag 查找的, 但是在 sdk 的文档中没有找到任何 tag 相关的字段, 包括 http 接口也没有. 这样的话, 关于 tag 字段我需要另外实现.

**Comment by wenxuwan** [comment]
> > > 
> > 
> > 
> > 明白了，getconfig的按照组获取和search里面制定group应该是一样的吧？ label不支持的话可以不做支持，前缀查询当前的接口定义里面应该没有前缀这个字段。不需要关心
> 
> 对的, 使用 search 实现 Get 接口. 后面没太理解, 我看到 Get 接口的请求参数是需要传递这些信息的.
> 
> ```go
> type GetRequest struct {
> 	AppId    string
> 	Group    string
> 	Label    string
> 	Keys     []string
> 	Metadata map[string]string
> }
> ```
> 
> 然后前缀查询的话不是给这个component Get 接口写的, 是想使用类似前缀查询的操作, 实现配置的 label 字段. 我看 etcd 实现 component 的时候是这么做的.
> 
> ```go
> func (c *EtcdV3ConfigStore) Get(ctx context.Context, req *configstores.GetRequest) ([]*configstores.ConfigurationItem, error) {
> 	targetString := []string{req.AppId, "*", "*", "*"}
> 	//TODO: the imp read all keys under app, then do match operation, should change later.
> 	keyValues, err := c.client.Get(ctx, "/"+req.AppId, clientv3.WithPrefix())
> 	res := make([]*configstores.ConfigurationItem, 0)
> 	if err != nil {
> 		log.DefaultLogger.Errorf("fail get all group key-value,err: %+v", err)
> 		return nil, err
> 	}
> 	targetString[configstores.Group] = req.Group
> 	targetString[configstores.Label] = req.Label
> 	if len(req.Keys) == 0 {
> 		return c.GetItemsFromAllKeys(keyValues.Kvs, targetString), nil
> 	}
> 	for _, key := range req.Keys {
> 		targetString[configstores.Key] = key
> 		res = append(res, c.GetItemsFromAllKeys(keyValues.Kvs, targetString)...)
> 	}
> 	trace.SetExtraComponentInfo(ctx, fmt.Sprintf("method: %+v, store: %+v", "Get", "etcd"))
> 	return res, nil
> }
> ```
> 
> > @cyb0225 这个没什么问题的话，有时间可以写起来了
> 
> 关于 tag 的支持我需要再研究一下, 他这个很奇怪, 可视化界面是支持 tag 创建和 tag 查找的, 但是在 sdk 的文档中没有找到任何 tag 相关的字段, 包括 http 接口也没有. 这样的话, 关于 tag 字段我需要另外实现.

可以对比看下nacos的http接口或者java sdk有没有类似的能力，我看了一下目前的golang-sdk功能不一定全面，如果server本身支持的话，可以给golang-sdk提pr增加能力

**Comment by cyb0225** [comment]
> > > > 
> > > 
> > > 
> > > 明白了，getconfig的按照组获取和search里面制定group应该是一样的吧？ label不支持的话可以不做支持，前缀查询当前的接口定义里面应该没有前缀这个字段。不需要关心
> > 
> > 
> > 对的, 使用 search 实现 Get 接口. 后面没太理解, 我看到 Get 接口的请求参数是需要传递这些信息的.
> > ```go
> > type GetRequest struct {
> > 	AppId    string
> > 	Group    string
> > 	Label    string
> > 	Keys     []string
> > 	Metadata map[string]string
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后前缀查询的话不是给这个component Get 接口写的, 是想使用类似前缀查询的操作, 实现配置的 label 字段. 我看 etcd 实现 component 的时候是这么做的.
> > ```go
> > func (c *EtcdV3ConfigStore) Get(ctx context.Context, req *configstores.GetRequest) ([]*configstores.ConfigurationItem, error) {
> > 	targetString := []string{req.AppId, "*", "*", "*"}
> > 	//TODO: the imp read all keys under app, then do match operation, should change later.
> > 	keyValues, err := c.client.Get(ctx, "/"+req.AppId, clientv3.WithPrefix())
> > 	res := make([]*configstores.ConfigurationItem, 0)
> > 	if err != nil {
> > 		log.DefaultLogger.Errorf("fail get all group key-value,err: %+v", err)
> > 		return nil, err
> > 	}
> > 	targetString[configstores.Group] = req.Group
> > 	targetString[configstores.Label] = req.Label
> > 	if len(req.Keys) == 0 {
> > 		return c.GetItemsFromAllKeys(keyValues.Kvs, targetString), nil
> > 	}
> > 	for _, key := range req.Keys {
> > 		targetString[configstores.Key] = key
> > 		res = append(res, c.GetItemsFromAllKeys(keyValues.Kvs, targetString)...)
> > 	}
> > 	trace.SetExtraComponentInfo(ctx, fmt.Sprintf("method: %+v, store: %+v", "Get", "etcd"))
> > 	return res, nil
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > @cyb0225 这个没什么问题的话，有时间可以写起来了
> > 
> > 
> > 关于 tag 的支持我需要再研究一下, 他这个很奇怪, 可视化界面是支持 tag 创建和 tag 查找的, 但是在 sdk 的文档中没有找到任何 tag 相关的字段, 包括 http 接口也没有. 这样的话, 关于 tag 字段我需要另外实现.
> 
> 可以对比看下nacos的http接口或者java sdk有没有类似的能力，我看了一下目前的golang-sdk功能不一定全面，如果server本身支持的话，可以给golang-sdk提pr增加能力

我昨天看了 java sdk 的文档和 open api 的文档, 也没发现支持, 给他们提了一个 issue.

**Comment by wenxuwan** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 明白了，getconfig的按照组获取和search里面制定group应该是一样的吧？ label不支持的话可以不做支持，前缀查询当前的接口定义里面应该没有前缀这个字段。不需要关心
> > > 
> > > 
> > > 对的, 使用 search 实现 Get 接口. 后面没太理解, 我看到 Get 接口的请求参数是需要传递这些信息的.
> > > ```go
> > > type GetRequest struct {
> > > 	AppId    string
> > > 	Group    string
> > > 	Label    string
> > > 	Keys     []string
> > > 	Metadata map[string]string
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 然后前缀查询的话不是给这个component Get 接口写的, 是想使用类似前缀查询的操作, 实现配置的 label 字段. 我看 etcd 实现 component 的时候是这么做的.
> > > ```go
> > > func (c *EtcdV3ConfigStore) Get(ctx context.Context, req *configstores.GetRequest) ([]*configstores.ConfigurationItem, error) {
> > > 	targetString := []string{req.AppId, "*", "*", "*"}
> > > 	//TODO: the imp read all keys under app, then do match operation, should change later.
> > > 	keyValues, err := c.client.Get(ctx, "/"+req.AppId, clientv3.WithPrefix())
> > > 	res := make([]*configstores.ConfigurationItem, 0)
> > > 	if err != nil {
> > > 		log.DefaultLogger.Errorf("fail get all group key-value,err: %+v", err)
> > > 		return nil, err
> > > 	}
> > > 	targetString[configstores.Group] = req.Group
> > > 	targetString[configstores.Label] = req.Label
> > > 	if len(req.Keys) == 0 {
> > > 		return c.GetItemsFromAllKeys(keyValues.Kvs, targetString), nil
> > > 	}
> > > 	for _, key := range req.Keys {
> > > 		targetString[configstores.Key] = key
> > > 		res = append(res, c.GetItemsFromAllKeys(keyValues.Kvs, targetString)...)
> > > 	}
> > > 	trace.SetExtraComponentInfo(ctx, fmt.Sprintf("method: %+v, store: %+v", "Get", "etcd"))
> > > 	return res, nil
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > > @cyb0225 这个没什么问题的话，有时间可以写起来了
> > > 
> > > 
> > > 关于 tag 的支持我需要再研究一下, 他这个很奇怪, 可视化界面是支持 tag 创建和 tag 查找的, 但是在 sdk 的文档中没有找到任何 tag 相关的字段, 包括 http 接口也没有. 这样的话, 关于 tag 字段我需要另外实现.
> > 
> > 
> > 可以对比看下nacos的http接口或者java sdk有没有类似的能力，我看了一下目前的golang-sdk功能不一定全面，如果server本身支持的话，可以给golang-sdk提pr增加能力
> 
> 我昨天看了 java sdk 的文档和 open api 的文档, 也没发现支持, 给他们提了一个 issue.

好的，如果不支持的话，可以先不用管其他的能力，先实现掉最基本的get、set、sub能力，现在dapr的configure的api设计原则就是保证最基本的上述能力，后面慢慢演进

**Comment by cyb0225** [comment]
> 

好的, 我先实现这些功能

**Comment by zhenjunMa** [comment]
关于label  tag这些能力设计的思考可以参考：https://github.com/dapr/dapr/issues/2988

**Comment by cyb0225** [comment]
他们 issue 也回我了，tag 在 sdk 确实还不支持，那个web里的界面是给运维用的。后面要实现的话我觉得可以参考 apollo 组件的那种实现方式，自己维护一对多的关系。
https://github.com/alibaba/nacos/issues/10531

**Comment by wenxuwan** [comment]
> 他们 issue 也回我了，tag 在 sdk 确实还不支持，那个web里的界面是给运维用的。后面要实现的话我觉得可以参考 apollo 组件的那种实现方式，自己维护一对多的关系。 [alibaba/nacos#10531](https://github.com/alibaba/nacos/issues/10531)

这个有开始做吗

**Comment by cyb0225** [comment]
> > 他们 issue 也回我了，tag 在 sdk 确实还不支持，那个web里的界面是给运维用的。后面要实现的话我觉得可以参考 apollo 组件的那种实现方式，自己维护一对多的关系。 [alibaba/nacos#10531](https://github.com/alibaba/nacos/issues/10531)
> 
> 这个有开始做吗

嗯，上周二阳了所以搁置了一会，目前 level1 功能基本实现了，我晚些时候以 draft 的形式发一个 pr。

**Comment by wenxuwan** [comment]
> > > 他们 issue 也回我了，tag 在 sdk 确实还不支持，那个web里的界面是给运维用的。后面要实现的话我觉得可以参考 apollo 组件的那种实现方式，自己维护一对多的关系。 [alibaba/nacos#10531](https://github.com/alibaba/nacos/issues/10531)
> > 
> > 
> > 这个有开始做吗
> 
> 嗯，上周二阳了所以搁置了一会，目前 level1 版本（没有 tag 和 label）功能基本实现了，我晚些时候以 draft 的形式发一个 pr。

先注意休息，不急

**Comment by zhenjunMa** [comment]
layotto计划6月底发布新版本，看看能不能赶上这个版本release

**Comment by cyb0225** [comment]
> layotto计划6月底发布新版本，看看能不能赶上这个版本release

没问题的，来得及

**Comment by cyb0225** [comment]
@wenxuwan，这个 `Set` 我觉得除了有新增配置外还有修改已存在配置的语意，下面这样设计会不会导致用户如果想要清空 tags 无法实现。

https://github.com/mosn/layotto/blob/91415599f4ffa43fdd6e53e210c52d78c0a1f746/components/configstores/apollo/configstore.go#L273-L275

**Comment by wenxuwan** [comment]
> @wenxuwan，这个 `Set` 我觉得除了有新增配置外还有修改已存在配置的语意，下面判断 tags 如果为空则跳过的逻辑会不会导致用户如果想要清空 tags 无法实现。
> 
> https://github.com/mosn/layotto/blob/91415599f4ffa43fdd6e53e210c52d78c0a1f746/components/configstores/apollo/configstore.go#L264-L287

这个apollo的实现本身有问题，put上去的value都是错误的，不用管他的实现。有空提个bugfix好了。

![image](https://github.com/mosn/layotto/assets/11661906/49f9d5de-803d-4d47-86fb-7cab4239cea2)


![image](https://github.com/mosn/layotto/assets/11661906/127fc46b-6628-4b60-bfaf-06dacd0a8582)

**Comment by wenxuwan** [comment]
> layotto/components/configstores/apollo/configstore.go

是的，的确会造成tags无法修改了。

![image](https://github.com/mosn/layotto/assets/11661906/d6f654f8-cd19-4ec0-8619-d636968f37a7)

当前的实现是在apollo的上面做了这一套映射，让客户端能用label，tags能力，但从apollo的管控端来看，理解成本太高了，nacos保持原生的特性即可。即管控端看到的是什么就是什么，不要像apollo这样去做实现了。

**Comment by cyb0225** [comment]
> 
那我还是将 label 和 tag 的功能回滚了吗，目前支持 level1 级别的 config 功能就行（因为 nacos 目前也还没支持）

**Comment by cyb0225** [comment]
> 支持的特性给用户返

那我还是将 label 和 tag 的功能回滚了吗，目前支持 level1 级别的 config 功能就行（因为 nacos 目前也还没支持）

nacos 应该还有一个分页的功能，目前需要通过 request 结构体中的 metadata 支持吗，比如加个页码和每页个数的字段。

**Comment by wenxuwan** [comment]
> > 支持的特性给用户返
> 
> 那我还是将 label 和 tag 的功能回滚了吗，目前只需要支持 level1 级别的 config 功能（因为 nacos 目前也还没支持）
> 
> nacos 应该还有一个分页的功能，目前需要通过 request 结构体中的 metadata 支持吗，比如加个页码和每页个数的字段。

apollo的先不动吧，nacos保持它原生能力就可以，分页的能力可以通过metadata做拓展，本身nacos支持的能力我们可以支持掉。
