### ISSUE TITLE
Links related to File API in official documents are invalid

### ISSUE THREAD

**Issue by XiaoYaoheihei** [mosn/layotto#922]
### Links related to File API in official documents are invalid

When I wanted to view the examples of the File API in the official documentation, I found that the link was invalid.
I would like to ask if there is a new link?
Thank you!

**Comment by seeflood** [comment]
Try these links:
https://mosn.io/layotto/#/zh/start/file/minio
https://mosn.io/layotto/#/zh/design/file/file-design
https://github.com/mosn/layotto/blob/f90a3380b63b78b20672580e201e87118c906134/spec/proto/runtime/v1/runtime.proto#L73
