### ISSUE TITLE
How to run layotto with congfig_mongo.json?

### ISSUE THREAD

**Issue by huayangchan** [mosn/layotto#932]
when running layotto with congfig_mongo.json, there is a error message that "runtime error:invalid  memory address or nil pointer dereference. How to run layotto with congfig_mongo.json?

**Comment by seeflood** [comment]
Do you mean config_mongo.json ? Can you list the steps to reproduce this error?
BTW, make sure that you start a mongo before starting layotto
https://mosn.io/layotto/#/zh/component_specs/lock/mongo?id=%e9%85%8d%e7%bd%ae%e9%a1%b9%e8%af%b4%e6%98%8e

**Comment by huayangchan** [comment]
> Do you mean config_mongo.json ? Can you list the steps to reproduce this error? BTW, make sure that you start a mongo before starting layotto https://mosn.io/layotto/#/zh/component_specs/lock/mongo?id=%e9%85%8d%e7%bd%ae%e9%a1%b9%e8%af%b4%e6%98%8e

Step1、 pull and run mongo:
docker pull mongo:latest
docker run --name mongoDB -d -p 27017:27017 mongo:latest
Step 2、 Check mongo 
docker ps -a

CONTAINER ID   IMAGE              COMMAND                  CREATED         STATUS                     PORTS                                           NAMES
9984d23d044c   mongo:latest       "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes               0.0.0.0:27017->27017/tcp, :::27017->27017/tcp   mongoDB
ae5245209446   zookeeper:latest   "/docker-entrypoint.…"   25 hours ago    Up 25 hours                2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp          zookeeper-test
48fcbd2640be   redis              "docker-entrypoint.s…"   28 hours ago    Up 28 hours                0.0.0.0:6380->6379/tcp, :::6380->6379/tcp       redis-test

Step3、 build and run layotto

cd ${project path}/layotto/cmd/layotto
go build -o layotto
## I directly use config_mongo.json wittout any modification
./layotto start -c ../../configs/config_mongo.json


the below is startup log
2023-05-30 15:52:05,431 [INFO] register a new handler maker, name is default, is default: true
2023-05-30 15:52:05,537 [INFO] [config] processor added to configParsedCBMaps
2023-05-30 15:52:05,537 [INFO] [network] [ register pool factory] register protocol: Http1 factory
2023-05-30 15:52:05,590 [INFO] [admin server] [register api] register a new api /server_info
2023-05-30 15:52:05,590 [INFO] [admin server] [register api] register a new api /config_dump
2023-05-30 15:52:05,592 [INFO] [network] [ register pool factory] register protocol: Http2 factory
2023-05-30 15:52:05,604 [DEBUG] [server] [init] add server conn handler, server name =
2023-05-30 15:52:05,604 [INFO] parsing listen config:tcp
2023-05-30 15:52:05,604 [WARN] [streamfilter] createStreamFilterFactoryFromConfig return nil factories
2023-05-30 15:52:05,604 [INFO] [streamfilter] AddOrUpdateStreamFilterConfig add filter chain key: grpc
2023-05-30 15:52:05,605 [DEBUG] grpc server filter: create a grpc server name: runtime
2023-05-30 15:52:05,606 [INFO] [runtime] start initializing SecretStores components
2023-05-30 15:52:05,606 [INFO] [runtime] init config service
2023-05-30 15:52:05,606 [INFO] [runtime] start initializing custom components
2023-05-30 15:52:05,606 [INFO] [runtime] init hello service
2023-05-30 15:52:05,606 [INFO] [runtime] start initializing state components
2023-05-30 15:52:05,606 [INFO] [runtime] init rpc service
2023-05-30 15:52:05,606 [INFO] [runtime] start initializing OutputBinding components
2023-05-30 15:52:05,606 [INFO] [runtime] start initializing pubsub components
2023-05-30 15:52:05,606 [INFO] [runtime] init file service
2023-05-30 15:52:05,606 [INFO] [runtime] init oss service
2023-05-30 15:52:05,606 [INFO] [runtime] start initializing lock components
2023-05-30 15:52:05,602 [INFO] register a grpc server named: runtime, success: true
2023-05-30 15:52:05,603 [INFO] [mosn start] create an empty mosn structure
2023-05-30 15:52:05,603 [INFO] [stagemanager] state changed to 1
2023-05-30 15:52:05,603 [INFO] [network] [ register pool factory] register protocol: bolt factory
2023-05-30 15:52:05,603 [INFO] [network] [ register pool factory] register protocol: dubbo factory
2023-05-30 15:52:05,603 [INFO] load config from :  ../../configs/config_mongo.json
2023-05-30 15:52:05,604 [INFO] parameters parsed stage cost: 771.576µs
2023-05-30 15:52:05,604 [INFO] [stagemanager] state changed to 2
2023-05-30 15:52:05,604 [INFO] [mosn] [start] xds service type is not router/sidecar, use config only
2023-05-30 15:52:05,604 [INFO] [mosn] [init tracing] disable tracing
2023-05-30 15:52:05,604 [INFO] [server] [reconfigure] not reconfigure: dial unix /home/chy/src/go-learning/layotto/configs/reconfig.sock: connect: no such file or directory
2023-05-30 15:52:05,604 [INFO] [mosn] [NewMosn] new mosn created
2023-05-30 15:52:05,604 [INFO] [mosn start] init the members of the mosn
2023-05-30 15:52:05,604 [INFO] [mosn start] mosn init cluster structures
2023-05-30 15:52:05,604 [WARN] [config] [parse cluster] No Cluster provided in cluster config
2023-05-30 15:52:05,604 [INFO] [mosn start] mosn init server structures
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x33f5cb7]

goroutine 1 [running]:
mosn.io/layotto/components/pkg/utils.SetCollection({0x0, 0x0}, {0x64806b0, 0x8aeb290}, {{0xc000de89b0, 0xf}, {0x0, 0x0}, {0x0, 0x0}, ...})
        /home/chy/src/go-learning/layotto/components/pkg/utils/mongo.go:263 +0xb7
mosn.io/layotto/components/lock/mongo.(*MongoLock).Init(0xc000de1320, {0x5864240?})
        /home/chy/src/go-learning/layotto/components/lock/mongo/mongo_lock.go:89 +0x2e7
mosn.io/layotto/pkg/runtime.(*MosnRuntime).initLocks(0xc000dcc4e0, {0xc000ddc780, 0x7, 0x8})
        /home/chy/src/go-learning/layotto/pkg/runtime/runtime.go:517 +0x232
mosn.io/layotto/pkg/runtime.DefaultInitRuntimeStage(0xc000155e00, 0xc000dcc4e0)
        /home/chy/src/go-learning/layotto/pkg/runtime/runtime.go:284 +0x2f3
mosn.io/layotto/pkg/runtime.(*MosnRuntime).initRuntime(0xc000dcc4e0, 0xff?)
        /home/chy/src/go-learning/layotto/pkg/runtime/runtime.go:683 +0x166
mosn.io/layotto/pkg/runtime.(*MosnRuntime).Run(0xc000dcc4e0, {0xc000b8ecd8, 0xf, 0x0?})
        /home/chy/src/go-learning/layotto/pkg/runtime/runtime.go:193 +0x166
main.NewRuntimeGrpcServer({0xc000dd23c0, 0x1ca, 0x1e0}, {0xc000db88a0, 0x2, 0x2})
        /home/chy/src/go-learning/layotto/cmd/layotto/main.go:257 +0x1a45
mosn.io/mosn/pkg/filter/network/grpc.(*Handler).New(0xc0005434b8, {0xc000dca270, 0xf}, {0xc000dd23c0, 0x1ca, 0x1e0}, {0xc000db88a0, 0x2, 0x2})
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/filter/network/grpc/factory.go:235 +0x267
mosn.io/mosn/pkg/filter/network/grpc.(*grpcServerFilterFactory).Init(0xc000dc4ed0, {0x56bc320?, 0xc000dc1200?})
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/filter/network/grpc/factory.go:84 +0x2f3
mosn.io/mosn/pkg/configmanager.AddOrUpdateNetworkFilterFactories({0xc000dca260, 0x4}, 0xc000dc1200)
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/configmanager/parser.go:423 +0x2a8
mosn.io/mosn/pkg/server.(*connHandler).AddOrUpdateListener(0xc000dc4b70, 0xc000dc1200)
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/server/handler.go:122 +0x145
mosn.io/mosn/pkg/server.(*server).AddListener(0xc000dc1200?, 0x0?)
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/server/server.go:92 +0x22
mosn.io/mosn/pkg/mosn.(*Mosn).initServer(0xc000c4c240)
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/mosn/mosn.go:220 +0x5dc
mosn.io/mosn/pkg/mosn.(*Mosn).Init(0xc000c4c240, 0x2?)
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/mosn/mosn.go:84 +0x7d
mosn.io/mosn/pkg/stagemanager.(*StageManager).runInitStage(0x88fdd80)
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/stagemanager/stage_manager.go:213 +0xb0
mosn.io/mosn/pkg/stagemanager.(*StageManager).Run(0x1?)
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/stagemanager/stage_manager.go:301 +0x28
mosn.io/mosn/pkg/stagemanager.(*StageManager).RunAll(0x88fdd80)
        /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/stagemanager/stage_manager.go:585 +0x1e
main.glob..func1(0xc000cde9a0)
        /home/chy/src/go-learning/layotto/cmd/layotto/cmd.go:201 +0x165
github.com/urfave/cli.HandleAction({0x53d5380?, 0x5ed05c8?}, 0x5?)
        /home/chy/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0x50
github.com/urfave/cli.Command.Run({{0x5d18771, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x5e36062, 0x4e}, {0x0, ...}, ...}, ...)
        /home/chy/go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:174 +0x67b
github.com/urfave/cli.(*App).Run(0xc0007d36c0, {0xc000074080, 0x4, 0x4})
        /home/chy/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:276 +0xbc7
main.main()
        /home/chy/src/go-learning/layotto/cmd/layotto/main.go:492 +0x4e

**Comment by wenxuwan** [comment]
> > Do you mean config_mongo.json ? Can you list the steps to reproduce this error? BTW, make sure that you start a mongo before starting layotto [mosn.io/layotto/#/zh/component_specs/lock/mongo?id=%e9%85%8d%e7%bd%ae%e9%a1%b9%e8%af%b4%e6%98%8e](https://mosn.io/layotto/#/zh/component_specs/lock/mongo?id=%e9%85%8d%e7%bd%ae%e9%a1%b9%e8%af%b4%e6%98%8e)
> 
> Step1、 pull and run mongo: docker pull mongo:latest docker run --name mongoDB -d -p 27017:27017 mongo:latest Step 2、 Check mongo docker ps -a
> 
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES 9984d23d044c mongo:latest "docker-entrypoint.s…" 3 minutes ago Up 3 minutes 0.0.0.0:27017->27017/tcp, :::27017->27017/tcp mongoDB ae5245209446 zookeeper:latest "/docker-entrypoint.…" 25 hours ago Up 25 hours 2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp zookeeper-test 48fcbd2640be redis "docker-entrypoint.s…" 28 hours ago Up 28 hours 0.0.0.0:6380->6379/tcp, :::6380->6379/tcp redis-test
> 
> Step3、 build and run layotto
> 
> cd ${project path}/layotto/cmd/layotto go build -o layotto ./layotto start -c ../../configs/config_mongo.json
> 
> I directly use config_mongo.json without any modification, the below is startup log:
> 
> 2023-05-30 15:52:05,431 [INFO] register a new handler maker, name is default, is default: true 2023-05-30 15:52:05,537 [INFO] [config] processor added to configParsedCBMaps 2023-05-30 15:52:05,537 [INFO] [network] [ register pool factory] register protocol: Http1 factory 2023-05-30 15:52:05,590 [INFO] [admin server] [register api] register a new api /server_info 2023-05-30 15:52:05,590 [INFO] [admin server] [register api] register a new api /config_dump 2023-05-30 15:52:05,592 [INFO] [network] [ register pool factory] register protocol: Http2 factory 2023-05-30 15:52:05,604 [DEBUG] [server] [init] add server conn handler, server name = 2023-05-30 15:52:05,604 [INFO] parsing listen config:tcp 2023-05-30 15:52:05,604 [WARN] [streamfilter] createStreamFilterFactoryFromConfig return nil factories 2023-05-30 15:52:05,604 [INFO] [streamfilter] AddOrUpdateStreamFilterConfig add filter chain key: grpc 2023-05-30 15:52:05,605 [DEBUG] grpc server filter: create a grpc server name: runtime 2023-05-30 15:52:05,606 [INFO] [runtime] start initializing SecretStores components 2023-05-30 15:52:05,606 [INFO] [runtime] init config service 2023-05-30 15:52:05,606 [INFO] [runtime] start initializing custom components 2023-05-30 15:52:05,606 [INFO] [runtime] init hello service 2023-05-30 15:52:05,606 [INFO] [runtime] start initializing state components 2023-05-30 15:52:05,606 [INFO] [runtime] init rpc service 2023-05-30 15:52:05,606 [INFO] [runtime] start initializing OutputBinding components 2023-05-30 15:52:05,606 [INFO] [runtime] start initializing pubsub components 2023-05-30 15:52:05,606 [INFO] [runtime] init file service 2023-05-30 15:52:05,606 [INFO] [runtime] init oss service 2023-05-30 15:52:05,606 [INFO] [runtime] start initializing lock components 2023-05-30 15:52:05,602 [INFO] register a grpc server named: runtime, success: true 2023-05-30 15:52:05,603 [INFO] [mosn start] create an empty mosn structure 2023-05-30 15:52:05,603 [INFO] [stagemanager] state changed to 1 2023-05-30 15:52:05,603 [INFO] [network] [ register pool factory] register protocol: bolt factory 2023-05-30 15:52:05,603 [INFO] [network] [ register pool factory] register protocol: dubbo factory 2023-05-30 15:52:05,603 [INFO] load config from : ../../configs/config_mongo.json 2023-05-30 15:52:05,604 [INFO] parameters parsed stage cost: 771.576µs 2023-05-30 15:52:05,604 [INFO] [stagemanager] state changed to 2 2023-05-30 15:52:05,604 [INFO] [mosn] [start] xds service type is not router/sidecar, use config only 2023-05-30 15:52:05,604 [INFO] [mosn] [init tracing] disable tracing 2023-05-30 15:52:05,604 [INFO] [server] [reconfigure] not reconfigure: dial unix /home/chy/src/go-learning/layotto/configs/reconfig.sock: connect: no such file or directory 2023-05-30 15:52:05,604 [INFO] [mosn] [NewMosn] new mosn created 2023-05-30 15:52:05,604 [INFO] [mosn start] init the members of the mosn 2023-05-30 15:52:05,604 [INFO] [mosn start] mosn init cluster structures 2023-05-30 15:52:05,604 [WARN] [config] [parse cluster] No Cluster provided in cluster config 2023-05-30 15:52:05,604 [INFO] [mosn start] mosn init server structures panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x33f5cb7]
> 
> goroutine 1 [running]: mosn.io/layotto/components/pkg/utils.SetCollection({0x0, 0x0}, {0x64806b0, 0x8aeb290}, {{0xc000de89b0, 0xf}, {0x0, 0x0}, {0x0, 0x0}, ...}) /home/chy/src/go-learning/layotto/components/pkg/utils/mongo.go:263 +0xb7 mosn.io/layotto/components/lock/mongo.(*MongoLock).Init(0xc000de1320, {0x5864240?}) /home/chy/src/go-learning/layotto/components/lock/mongo/mongo_lock.go:89 +0x2e7 mosn.io/layotto/pkg/runtime.(*MosnRuntime).initLocks(0xc000dcc4e0, {0xc000ddc780, 0x7, 0x8}) /home/chy/src/go-learning/layotto/pkg/runtime/runtime.go:517 +0x232 mosn.io/layotto/pkg/runtime.DefaultInitRuntimeStage(0xc000155e00, 0xc000dcc4e0) /home/chy/src/go-learning/layotto/pkg/runtime/runtime.go:284 +0x2f3 mosn.io/layotto/pkg/runtime.(*MosnRuntime).initRuntime(0xc000dcc4e0, 0xff?) /home/chy/src/go-learning/layotto/pkg/runtime/runtime.go:683 +0x166 mosn.io/layotto/pkg/runtime.(*MosnRuntime).Run(0xc000dcc4e0, {0xc000b8ecd8, 0xf, 0x0?}) /home/chy/src/go-learning/layotto/pkg/runtime/runtime.go:193 +0x166 main.NewRuntimeGrpcServer({0xc000dd23c0, 0x1ca, 0x1e0}, {0xc000db88a0, 0x2, 0x2}) /home/chy/src/go-learning/layotto/cmd/layotto/main.go:257 +0x1a45 mosn.io/mosn/pkg/filter/network/grpc.(*Handler).New(0xc0005434b8, {0xc000dca270, 0xf}, {0xc000dd23c0, 0x1ca, 0x1e0}, {0xc000db88a0, 0x2, 0x2}) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/filter/network/grpc/factory.go:235 +0x267 mosn.io/mosn/pkg/filter/network/grpc.(*grpcServerFilterFactory).Init(0xc000dc4ed0, {0x56bc320?, 0xc000dc1200?}) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/filter/network/grpc/factory.go:84 +0x2f3 mosn.io/mosn/pkg/configmanager.AddOrUpdateNetworkFilterFactories({0xc000dca260, 0x4}, 0xc000dc1200) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/configmanager/parser.go:423 +0x2a8 mosn.io/mosn/pkg/server.(*connHandler).AddOrUpdateListener(0xc000dc4b70, 0xc000dc1200) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/server/handler.go:122 +0x145 mosn.io/mosn/pkg/server.(*server).AddListener(0xc000dc1200?, 0x0?) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/server/server.go:92 +0x22 mosn.io/mosn/pkg/mosn.(*Mosn).initServer(0xc000c4c240) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/mosn/mosn.go:220 +0x5dc mosn.io/mosn/pkg/mosn.(*Mosn).Init(0xc000c4c240, 0x2?) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/mosn/mosn.go:84 +0x7d mosn.io/mosn/pkg/stagemanager.(*StageManager).runInitStage(0x88fdd80) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/stagemanager/stage_manager.go:213 +0xb0 mosn.io/mosn/pkg/stagemanager.(*StageManager).Run(0x1?) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/stagemanager/stage_manager.go:301 +0x28 mosn.io/mosn/pkg/stagemanager.(*StageManager).RunAll(0x88fdd80) /home/chy/go/pkg/mod/mosn.io/mosn@v1.3.0/pkg/stagemanager/stage_manager.go:585 +0x1e main.glob..func1(0xc000cde9a0) /home/chy/src/go-learning/layotto/cmd/layotto/cmd.go:201 +0x165 github.com/urfave/cli.HandleAction({0x53d5380?, 0x5ed05c8?}, 0x5?) /home/chy/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0x50 github.com/urfave/cli.Command.Run({{0x5d18771, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x5e36062, 0x4e}, {0x0, ...}, ...}, ...) /home/chy/go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:174 +0x67b github.com/urfave/cli.(*App).Run(0xc0007d36c0, {0xc000074080, 0x4, 0x4}) /home/chy/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:276 +0xbc7 main.main() /home/chy/src/go-learning/layotto/cmd/layotto/main.go:492 +0x4e

Forgetting to assign client to MongoLock resulted in panic，I raise a pr, you can try it with the fix.
