### ISSUE TITLE
ospp | layotto 支持 pluggabel component 组件

### ISSUE THREAD

**Issue by cyb0225** [mosn/layotto#959]
# ospp 项目
> 相关 issue: #888 

## 开发节奏：
1. 完成 layotto 支持 pluggable component 的基础代码设计，在 #888 中给出了 demo 设计。
2. 相关组件到 proto 文件定义
3. 编写 grpc 服务到组件 interface 的实现。
4. 相关拓展实现讨论（如日志、健康检查 actuator）
5. 相关测试（多语言集成测试）及文档编写。

**Comment by zhenjunMa** [comment]
完成开发，测试中

**Comment by zhenjunMa** [comment]
1. 升级dapr component依赖
2. api.go适配
